### ISSUE TITLE
Core Plot 1.4 compile issue.

### ISSUE THREAD

**Issue by PMaverick** [core-plot/core-plot#129]
What would be work around for this error:

/Users/pwalker/Downloads/CorePlot_1.4/Source/framework/iPhoneOnly/CPTTextStylePlatformSpecific.m:69:38: error: implicit conversion from enumeration type 'NSTextAlignment' (aka 'enum NSTextAlignment') to different enumeration type 'CPTTextAlignment' (aka 'enum _CPTTextAlignment') [-Werror,-Wenum-conversion]
            newStyle.textAlignment = paragraphStyle.alignment;
                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/pwalker/Downloads/CorePlot_1.4/Source/framework/iPhoneOnly/CPTTextStylePlatformSpecific.m:115:40: error: implicit conversion from enumeration type 'CPTTextAlignment' (aka 'enum _CPTTextAlignment') to different enumeration type 'NSTextAlignment' (aka 'enum NSTextAlignment') [-Werror,-Wenum-conversion]
        paragraphStyle.alignment     = self.textAlignment;
                                     ~ ^~~~~~~~~~~~~~~~~~
/Users/pwalker/Downloads/CorePlot_1.4/Source/framework/iPhoneOnly/CPTTextStylePlatformSpecific.m:171:38: error: implicit conversion from enumeration type 'NSTextAlignment' (aka 'enum NSTextAlignment') to different enumeration type 'CPTTextAlignment' (aka 'enum _CPTTextAlignment') [-Werror,-Wenum-conversion]
            newStyle.textAlignment = paragraphStyle.alignment;
                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

**Comment by dkamdar** [comment]
Hi Eric,
I downloaded the latest version yesterday. I am still getting these errors.
```
/Users/devangkamdar/Desktop/iOS/CorePlot/CorePlot_1.4/Source/framework/iPhoneOnly/CPTTextStylePlatformSpecific.m:69:38: Implicit conversion from enumeration type 'NSTextAlignment' (aka 'enum NSTextAlignment') to different enumeration type 'CPTTextAlignment' (aka 'enum _CPTTextAlignment')
/Users/devangkamdar/Desktop/iOS/CorePlot/CorePlot_1.4/Source/framework/iPhoneOnly/CPTTextStylePlatformSpecific.m:115:40: Implicit conversion from enumeration type 'CPTTextAlignment' (aka 'enum _CPTTextAlignment') to different enumeration type 'NSTextAlignment' (aka 'enum NSTextAlignment')
/Users/devangkamdar/Desktop/iOS/CorePlot/CorePlot_1.4/Source/framework/iPhoneOnly/CPTTextStylePlatformSpecific.m:171:38: Implicit conversion from enumeration type 'NSTextAlignment' (aka 'enum NSTextAlignment') to different enumeration type 'CPTTextAlignment' (aka 'enum _CPTTextAlignment')
```
Also, I am trying to re-compile the source as I am getting this warning in my project - 
```
"(null): Ignoring file /Users/devangkamdar/Desktop/iOS/Greyloft/Assignment/CorePlotTest/CorePlotTest/resources/external libs/CorePlot/libCorePlot-CocoaTouch.a, missing required architecture x86_64 in file /Users/devangkamdar/Desktop/iOS/Greyloft/Assignment/CorePlotTest/CorePlotTest/resources/external libs/CorePlot/libCorePlot-CocoaTouch.a (3 slices)"
```
As suggested in this thread - 
http://stackoverflow.com/questions/20264574/missing-required-architecture-x86-64-in-file-libcoreplot-cocoatouch-a

The strange thing is I am using core plot in a new project and this is the first time I am seeing this warning. The same .a files I added to another project yesterday and never got any warnings.
Please advice.

**Comment by eskroch** [comment]
As noted above, 1.4 is far from the latest version. Release packages are linked on [this page](https://github.com/core-plot/core-plot/releases). Version 1.6 should be out soon—I'm just cleaning up the last few known bugs.

**Comment by dkamdar** [comment]
ah ... I was downloading from Google code site where 1.4 was the latest. 
Thanks! :)
