### ISSUE TITLE
CPTScatterPlotInterpolationCurved problem

### ISSUE THREAD

**Issue by claesjacobsson** [core-plot/core-plot#131]
When using CPTScatterPlotInterpolationCurved and [plotSpace scaleToFitPlots:[self.graph allPlots]] I get a problem (see image).  Is it possible to make the scaling allow for the top of the highest/lowest curve top to fit?

Is there a workaround except for setting my PlotRange manually?

![interpolationcurved bug](https://cloud.githubusercontent.com/assets/507101/5217479/4254ea5e-7641-11e4-85a7-46d4cc35402e.png)

**Comment by prince-ugwuh-volusion** [comment]
I found that this code here http://stackoverflow.com/a/25324819 works really well with the curve that doesn't go below zero. I have used this to replace what is in the current build of core plot. If you like it maybe it can be another option or a good replacement for the curve interpolation

**Comment by maciejburda** [comment]
@prince-ugwuh-volusion 
where exactly did you replaced the code?
