### ISSUE TITLE
Sub-pixel antialiasing in fonts

### ISSUE THREAD

**Issue by ElDeveloper** [core-plot/core-plot#135]
It doesn't seem like sub-pixel antialiasing is enabled for the text presented in tick labels and or the plot title.

I have a looked around and the only thing I was able to find was this [issue](https://code.google.com/p/core-plot/issues/detail?id=22).

I am using the latest version in master.

**Comment by ivmirx** [comment]
Sorry about bumping the old issue but I'm getting awkward  `CPTTextLayer` rendering on non-retina screens when LCD font smoothing is enabled.

`defaults -currentHost write -globalDomain AppleFontSmoothing -int 2`
![image](https://cloud.githubusercontent.com/assets/10554114/16363808/c1e5f524-3bac-11e6-8380-e0f306f3567f.png)

`defaults -currentHost write -globalDomain AppleFontSmoothing -int 0`
![image](https://cloud.githubusercontent.com/assets/10554114/16363824/16a6278c-3bad-11e6-9125-6e55e275c345.png)

I tried rounding frame positions and calling `pixelAlign` on the `CPTTextLayer` but it didn't help.

Calling `CGContextSetShouldSmoothFonts(context, false);` from `renderAsVectorInContext:` in `CPTTextLayer` fixes the problem but I need to modify code inside Core Plot.

Is there any other workaround? Thanks!
