### ISSUE TITLE
PlotBar with overlap when zoom out graph.

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#140]
Hi, 

   
       Firstly I  initialize the bar width,  and when  zoom out the plot graph, 
the bar width will be set as current width * interactiveScale,  but bars will overlap with its neighbor, 
so how should i set the bar width to avoid this issue?

Thanks a lot.

**Comment by eskroch** [comment]
Set the [`barWidthsAreInViewCoordinates`](http://core-plot.github.io/iOS/interface_c_p_t_bar_plot.html#adcf9f3593603002d91d97c3e4dc9bc87) to `YES`. That tells the plot that the `barWidth` is given in view points (pixels on non-Retina screens, 2x pixels on Retina screens).
