### ISSUE TITLE
how to draw discontinuity line?

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#141]
I want draw a line with the middle two points disconnect with each other, but others connect as normal.

how to do that, should I must draw two lines?.

Thanks a lot.

**Comment by eskroch** [comment]
Including `nil` or `[NSNull null]` in the plot data will cause the scatter plot to break the plot line around the missing data points.

**Comment by Toanso** [comment]
Thanks a lot, eskroch.
