### ISSUE TITLE
Core-plot-master Universal lib build fail on static link with iOS project

### ISSUE THREAD

**Issue by mjm555** [core-plot/core-plot#142]
I downloaded the core-plot-master files via zip download button today 01-22-2015.
I successfully built the Universal libCorePlot-CocoaTouch.a file.
I have a project  MyProject that uses the 1.5.1 released file libCorePlot-CocoaTouch.a.
When I replaced the 1.5.1 libCorePlot-CocoaTouch.a file with the one I built from core-plot-master project the MyProject fails on link with an i386 error shown below.

All discussions I found with regards to a link error are old, 2013 or earlier. The discussions were for Xcode 4.5 or Xcode 5.1. I am using Xcode 6.1. Did this error creep back since it was fixed previously by chance? Thanks.

Undefined symbols for architecture i386:
  "_vDSP_maxvD", referenced from:
      -[CPTPlot plotRangeForField:] in libCorePlot-CocoaTouch.a(CPTPlot.o)
  "_vDSP_minvD", referenced from:
      -[CPTPlot plotRangeForField:] in libCorePlot-CocoaTouch.a(CPTPlot.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by eskroch** [comment]
The vDSP functions are part of the Accelerate framework. Newer versions of Core Plot require iOS apps to link against the Accelerate framework. Add it to your app target to fix this error.

**Comment by mjm555** [comment]
Yup. That was it! Thank you so much!!!

My motivation for looking at the source and re-building the library was to implement up/down color for the OHLC plot style (like the candlestick plot style). This is a very popular feature with charting apps.
I was able to accomplish this by making 2 changes to the drawOHLCInContext method.

1. make the lifestyle mutable at the top of the method like so:
    CPTMutableLineStyle *theLineStyle = [CPTMutableLineStyle lineStyle];
    theLineStyle.lineWidth = self.lineStyle.lineWidth;

2. adding these few lines to the drawOHLCInContext right before the call to CGContextBeginPath at the bottom of the function.
        if( closeValue > openValue ){
            theLineStyle.lineColor = [CPTColor greenColor];
        }
        else if (closeValue < openValue ){
            theLineStyle.lineColor = [CPTColor redColor];
        }
        else{
            theLineStyle.lineColor = self.lineStyle.lineColor;
        }

Of course the colors should not be hard-coded and the mutable lifestyle should make a more complete copy of the actual lifestyle, but for my purposes this is a quick hack that does the job.

My other option was to sub-class CPTTradingRangePlot and override the drawOHLCInContext method, but it would be nice if this were a built-in feature of the library itself.

Thanks much again!

**Comment by eskroch** [comment]
That sounds like a useful feature. Either clean up your solution and submit a pull request or open an enhancement request here on the issue tracker.
