### ISSUE TITLE
why kline plot don't show anything on iPhone 5 or lower version device.

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#143]
Hi, 

  I draw a CPTTradingRangePlotStyleCandleStick type plot on my graph, it can be shown well on iPhone 5s, iPhone 6 and iPhone 6 plus, but  it show nothing on iPhone 5 or iPhone 4s, 
axis can be shown as normal, only plot can not.
 I use same OS version and same code when i test on iPhone 6 and iPhone 5. What's the possible reason to cause this issue?
any suggestion will be welcomed.

Thanks a lot.

**Comment by eskroch** [comment]
The 64-bit devices are working but 32-bit are not. Check your build settings and make sure the app includes both architectures.

**Comment by Toanso** [comment]
Thanks a lot eskroch.
