### ISSUE TITLE
how to make two graphs share same X axis?

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#145]
Hi , 

  I have two graph wanna to be draw, but I want them share same x axis, when move one, another will follow, they will have same plot x range at any time, just like they are at same plot area.

  My solution now is:
  override
 -(CGPoint)plotSpace:(CPTPlotSpace *)space willDisplaceBy:(CGPoint)displacement delegate,
 in which implement set two graphs with same x range. but when move faster, another will not move together sometimes, also can see another delay change its x range.

 Another question is about performance optimization:

 When draw CPTTradingRangePlot, if points count is larger that 2000 or more, UIPinchGestureRecognizer, UIPanGestureRecognizer will not as smooth as normal, 
is there any suggestion to optimize that to make it feels smooth when data source has 4000 points on iPhone 5s.

Thanks in advance.

**Comment by eskroch** [comment]
Try using the `-plotSpace:willChangePlotRangeTo:forCoordinate:` or `-plotSpace:didChangePlotRangeForCoordinate:` delegate methods instead. These tell you the actual range being updated, so the other graph doesn't miss a displacement update and get out of sync.

Filter the plot data if possible. Only provide points within the plot ranges. Add more if the graph zooms or scrolls to uncover new points. Remove extra points that are not visible any more.

**Comment by Toanso** [comment]
Hi eskroch, 
how about UIPinchGesture ? 
my current solution now is override -(BOOL)plotSpace:(CPTPlotSpace *)space shouldScaleBy:(CGFloat)interactionScale aboutPoint:(CGPoint)interactionPoint delegate.

should I use -plotSpace:willChangePlotRangeTo:forCoordinate: or -plotSpace:didChangePlotRangeForCoordinate:    instead ?

Thanks a lot.

**Comment by eskroch** [comment]
The `willChange` and `didChange` delegate methods are called for any change to the plot ranges, no matter the source.

**Comment by Toanso** [comment]
Thanks a lot eskroch.
