### ISSUE TITLE
Point Release for 1.x branch

### ISSUE THREAD

**Issue by shortstuffsushi** [core-plot/core-plot#146]
I hate to be that guy, but do you plan on having a final release for the 1.x branch? I've seen a few issues get pushed to master that would be nice to have a release for (namely the Cocoapods 0.36.0 issue w/ selectors). I can see that you're working steadily on 2.0, but it's currently unlikely my team will be taking that release when it does come out (the project is in maintenance mode now, but compile errors are still relevant). So, I can change the project to point at the latest master commit, but obviously an official release would be preferable. Do you have any opinions or intentions around doing so?

**Comment by eskroch** [comment]
I've had the same thought, but haven't gotten around to it. I want to do a final release on the 1.x branch (next release is 1.6) and follow that shortly with the 2.0. We definitely need both because there are some changes in 2.0 that will require significant changes to some client apps.

**Comment by shortstuffsushi** [comment]
Yeah, that probable API breakage is why we were hoping not to make the jump (at least right away). Glad you're feeling the same way. Whenever you're ready is fine, just wanted to know what the plan was.

**Comment by eskroch** [comment]
[Release 1.6](https://github.com/core-plot/core-plot/releases/tag/release_1.6) is out now.

**Comment by shortstuffsushi** [comment]
Awesome, thanks.
