### ISSUE TITLE
Too many Arguments to function call,expected 0,have 3

### ISSUE THREAD

**Issue by elliotxin** [core-plot/core-plot#147]
today my boss give me one App, this app builded on IOS SDK 8.1 and xocde 6.1.the Podfile include: 

# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

def import_pods
    pod 'AFNetworking', '~>2.5.0'
    pod 'SDWebImage', '~>3.7.1'
    pod 'CocoaLumberjack', '~> 1.9'
    pod 'EasyMapping', '~> 0.6.3'
    pod 'ReactiveCocoa', '~> 2.3.1'
    pod 'libextobjc', '~>0.4.1'
    pod 'CorePlot', '~>1.5.1'
    
    #    pod 'ActionSheetPicker-3.0', '~>1.3.5'
    #    pod 'MBProgressHUD', '~> 0.9'
end

After i finished pod install, run this apps, the error message was coming like this:
setterMethod(boundObject, boundSetter, buffer); Too many arguments to function call, expected 0, have 3
setterMethod(boundObject, boundSetter, tweenedValue);Too many arguments to function call, expected 0, have 3
and this issue from "CPTAnimation.m" file
anyone can tell me whats happen for this,please help me to fix it.thanks so munch.

**Comment by eskroch** [comment]
I added this podfile to a new project. I'm not seeing this error, even with pedantic warnings enabled.

**Comment by elliotxin** [comment]
I put the project to another computer,after install whole cocoapods, the project can running already.so i think its my computer environment problem.so i will re-intall Xcode and cocoapods, after that try it again.By the way, thanks to your responds.

**Comment by carllindberg** [comment]
Apple no longer wants developers to use the IMP type directly and make function calls with it; they want code to locally type a function pointer with the actual argument types so that the compiler sets up the frame correctly.  In objc.h, unless OBJC_OLD_DISPATCH_PROTOTYPES is defined, then IMP will now be typed differently to have void parameters.   Sounds like that setting may be changed in newer cocoapods versions.  CPTAnimation really should be fixed though.

**Comment by mikeantonelli** [comment]
+1 @carllindberg. FWIW, I also see this issue when installing using cocoapods v0.36.0 but not when using 0.35.0.

**Comment by eskroch** [comment]
This was fixed after the 1.5.1 release. Use the following line in your podfile to get the latest (fixed) code:

    pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'

**Comment by mikeantonelli** [comment]
Thanks @eskroch! Is there a targeted release version/date for this?

**Comment by eskroch** [comment]
I hope to have 1.6 out soon.
