### ISSUE TITLE
multiple plots in one graph

### ISSUE THREAD

**Issue by veronicaTsao** [core-plot/core-plot#148]
Hello, 
from the documentation, it seems that core-plot supports
"It is important to realize that a single graph may contain multiple plots, and that these plots may be plotted on different scales. For example, one plot may need to be drawn with a logarithmic scale, and a separate plot may be drawn on a linear scale. There is nothing to prevent both plots appearing in a single graph.

For this reason, a single CPTGraph instance can have multiple instances of CPTPlotSpace. In the most common cases, there will only be a single instance of CPTPlotSpace, but the flexibility exists within the framework to support multiple spaces in a single graph."

Do you have an example for how to use the feature?
Thanks,
Veronica

**Comment by eskroch** [comment]
Core Plot includes several example apps that demonstrate various capabilities. The *Plot Gallery* is a good overview of most of them. It includes demos with multiple plots and with multiple plot spaces. The Mac version of CPTTestApp includes both at the same time in one graph.
