### ISSUE TITLE
Build a dynamic framework on iOS

### ISSUE THREAD

**Issue by timmorey** [core-plot/core-plot#150]
I have a need to build CorePlot as a dynamic framework on iOS.  We want to use it in a swift app that uses a swift framework.  In order to use CorePlot at both the app and framework level, we need to link to CorePlot dynamically.

I have forked CorePlot and configured a dynamic framework target here: https://github.com/timmorey/core-plot/tree/DynamicFramework.  I'm not positive that I did everything right, since this is my first attempt at configuring a dynamic framework target, but its working in my app.  It would be nice to get this functionality added/merged into the release-2.0 branch.

**Comment by eskroch** [comment]
I'm working on combining the Mac and iOS code into one Xcode project. On the release-2.0 branch, I moved the iOS static library into the Mac project (`CorePlot.xcodeproj`). I also added an iOS framework target to this project. I will deprecate the separate iOS project file with the 2.0 release and remove it in a later release.
