### ISSUE TITLE
example to use dataLabelForPlot in swift

### ISSUE THREAD

**Issue by veronicaTsao** [core-plot/core-plot#151]
Can you provide a simple example to use dataLabelForPlot in swift?

Thanks,
Veronica

**Comment by eskroch** [comment]
The iPhone CPTTestApp example app on the release-2.0 branch is written in Swift. There's a demo of `dataLabelForPlot ` in the [pie chart](https://github.com/core-plot/core-plot/blob/release-2.0/examples/CPTTestApp-iPhone/Classes/PieChartController.swift#L73).
