### ISSUE TITLE
iPhone 6: Real Time Plot demo error: "Assertion failure in -[CPTXYPlotSpace setXRange:]"

### ISSUE THREAD

**Issue by briansayer** [core-plot/core-plot#152]
Hi - I've been unable to get the plot space to animate from one xRange to another in my app due to this error. 

I downloaded the latest code (v. 2) from github because this issue (seen on iPad) was previously reported as fixed after version 1.5 (http://stackoverflow.com/questions/22540754/real-time-plot-in-plot-gallery-ios-does-not-update-plot-range-in-ipad), but it's still not working on my iPhone 6.

Error output:
Plot Gallery[2217:344296] *** Assertion failure in -[CPTXYPlotSpace setXRange:], /Users/brian/Development/ExternalTools/core-plot-master/framework/Source/CPTXYPlotSpace.m:377

**Comment by eskroch** [comment]
Did you do a clean build to verify that your app is linked with the new Core Plot library?

**Comment by briansayer** [comment]
Hi Eric - thanks for responding. Yes, I've done a clean and a build. As I said it plots the graph from left to right but when it gets to the right edge of the screen and begins to animate the xRange I get the assertion failure and the plot disappears off screen. I downloaded the code from github today. 

I get the same problem trying to animate the xRange in my own app, whether I use version 1.5.1 or 2 of core plot.

**Comment by eskroch** [comment]
What did you download? 2.0 is only available on the release-2.0 branch right now. There is no downloadable 2.0 release package yet.

**Comment by briansayer** [comment]
I downloaded the master branch here: https://github.com/core-plot/core-plot
and then ran the Plot_Gallery_iOS project. So that would be 1.5.1 then...
never mind.



*Brian Sayer* | Development Manager






  *Customised Applications* *Mobile Software*



+27 (82) 336 2106

www.customisedapplications.net

brian.sayer@customisedapplications.net
<shaun.wuth@customisedapplications.net>

**Comment by eskroch** [comment]
If you got the latest from master, it should be fixed there, too.

**Comment by eskroch** [comment]
@briansayer Did you figure out what the problem was?
