### ISSUE TITLE
Apparent memory leak: CALayer objects not being released

### ISSUE THREAD

**Issue by briansayer** [core-plot/core-plot#154]
My app updates 4 or more core plot graphs whenever it receives new data (once a second at this point). The view controller used to create the graph has two strong properties pointing to the CPTGraphHostingView and CPTXYGraph. Each time new data is received, the view controller attempts to clean up the graph by nilling the core plot objects, before recreating them from scratch. I read in a previous comment that all that should be necessary to clean up the graph is 
    [_hostView removeFromSuperview];
    _hostView = nil;
but this is not working, so I've tried to nil a bunch of other core plot objects and relationships, to no avail.

Profiling the allocations in Instruments shows that CALayer objects continue to be allocated and not released:
![screen shot 2015-02-15 at 4 50 42 pm](https://cloud.githubusercontent.com/assets/3910425/6203695/411cf64c-b537-11e4-940b-05234015af18.png)
 until the app crashes.

The clean up method looks like this: 

    -(void)cleanUp
    {
          if(_monitorValueGraph)
          {
           for (CPTPlot* plot in _monitorValueGraph.allPlots) {
                plot.dataSource = nil;
                plot.delegate = nil;
                [plot deleteDataInIndexRange:NSMakeRange(0, plot.cachedDataCount)];
                plot.plotSpace = nil;
                [_monitorValueGraph removePlot:plot];
           }
            for(CPTPlotSpace* plotSpace in _monitorValueGraph.allPlotSpaces)
            {
                [_monitorValueGraph removePlotSpace:plotSpace];
            }
        
            [_hostView.hostedGraph.axisSet removeFromSuperlayer];
            _hostView.hostedGraph.axisSet = nil;
            _hostView.hostedGraph = nil;        
            [_hostView removeFromSuperview];
            [_hostView.layer removeFromSuperlayer];
            _hostView = nil;
            [_monitorValueGraph removeFromSuperlayer];
            _monitorValueGraph = nil;
        }
    }

I am pretty stumped as to what could be retaining these CALayer objects. Any help would be appreciated

**Comment by eskroch** [comment]
If `_hostView` and `_monitorValueGraph` are the only strong references to the graph and hosting view, setting them to `nil` will deallocate all of the Core Plot objects. Are you sure there are no other strong references and that they really are not deallocated? The Instruments trace you posted doesn't show any leaked objects.
