### ISSUE TITLE
Lots of bugs in Release-2.0 branch with Swift

### ISSUE THREAD

**Issue by kas84** [core-plot/core-plot#155]
I'm running CPTestApp-iPhone under examples folder on Xcode (Version 6.1.1) and getting the following errors:

![captura de pantalla 2015-02-20 a las 17 16 34](https://cloud.githubusercontent.com/assets/5584/6290035/734398e2-b924-11e4-9975-79c61e7f33e7.png)

**Comment by eskroch** [comment]
I updated the Swift examples to work with Swift 1.2 (Xcode 6.3 beta). The new `as!` operator was the big breaking change. I also used the new Swift `Set` when building custom axis labels.

Revert the changes from [commit d8ac0e7cc26faf839ed111debbbe17ab30403775](https://github.com/core-plot/core-plot/commit/d8ac0e7cc26faf839ed111debbbe17ab30403775) to make the examples work in previous versions.

**Comment by kas84** [comment]
I've detached to that commit. And when opening CorePlot Gallery examples for iOS, I get the following error (cannot find CorePlot.h though I am able to navigate with CMD + click) in PlotItem.h
![captura de pantalla 2015-03-04 a las 17 18 32](https://cloud.githubusercontent.com/assets/5584/6487626/99e69c0c-c292-11e4-9fe3-74e2efa6d135.png)

**Comment by eskroch** [comment]
I'm not seeing any errors with Xcode 6.1.1. Did you try a clean build?
