### ISSUE TITLE
Swatch drawing for pie charts executed in wrong order. Does not allow overriding.

### ISSUE THREAD

**Issue by davidbjames** [core-plot/core-plot#156]
CPTPlot.m
```objective-c
-(void)drawSwatchForLegend:(CPTLegend *)legend atIndex:(NSUInteger)idx inRect:(CGRect)rect inContext:(CGContextRef)context
{
    id<CPTLegendDelegate> theDelegate = (id<CPTLegendDelegate>)self.delegate;

    CPTFill *theFill = nil;
    if ( [theDelegate respondsToSelector:@selector(legend:fillForSwatchAtIndex:forPlot:)] ) {
        theFill = [theDelegate legend:legend fillForSwatchAtIndex:idx forPlot:self];
    }
    ... 
```

CPTPieChart.m
```objective-c
-(void)drawSwatchForLegend:(CPTLegend *)legend atIndex:(NSUInteger)idx inRect:(CGRect)rect inContext:(CGContextRef)context
{
    [super drawSwatchForLegend:legend atIndex:idx inRect:rect inContext:context];

    if ( self.drawLegendSwatchDecoration ) {
        CPTFill *theFill           = [self sliceFillForIndex:idx];
    ... 
```

Notice the order, 1. CPTPlot.m is called first (via super) allowing the delegate to set the swatch fill, 2. CPTPieChart.m sets swatch fill to slice color, which effectively negates No. 1

**Comment by eskroch** [comment]
You can set the pie chart's `drawLegendSwatchDecoration` property to `NO` to prevent it from overwriting the swatch with the pie slice fill. All plot types have this property.

**Comment by davidbjames** [comment]
`drawLegendSwatchDecoration = NO` implies "do not draw swatch". IMO, it could be named something like `useDefaultStyleForSwatch`, which defaults to `YES`, and can be turned off.
