### ISSUE TITLE
Problem with CorePlotProbes when installing the pod with Cocoapods

### ISSUE THREAD

**Issue by bertranddelvaux** [core-plot/core-plot#157]
Hello,

I am new to Cocoapods. I have followed tutorials such as http://www.raywenderlich.com/64546/introduction-to-cocoapods-2 to install the pod of CorePlot via Cocoapods, but once I run "pod install", it gives me an error related to

"dtrace -h -s framework/TestResources/CorePlotProbes.d -o framework/Source/CorePlotProbes.h"

Any idea?

Thank you!

**Comment by eskroch** [comment]
Answered on [StackOverflow](http://stackoverflow.com/questions/28680773/).
