### ISSUE TITLE
CorePlot crash (memmove in insertDataAtIndex:numberOfRecords:)

### ISSUE THREAD

**Issue by iangmaia** [core-plot/core-plot#159]
I have a live application whose number one crash is the following:

Crashed: 1.9-2092-b25facd (com.apple.main-thread)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x7538dcfb7617e400
_platform_memmove + 228
CPTPlot.m line 596
-[CPTPlot insertDataAtIndex:numberOfRecords:]

I have a plot chart whose data is updated every 30s or so, using insertDataAtIndex + reloadData.
Any clue?

**Comment by eskroch** [comment]
It's hard to tell what's happening without more context. How many point are being added? Are the Core Plot methods always called on the main thread? Is this a Mac or iOS app? Does it happen on one particular system version or on several? 32-bit, 64-bit, or both?

You don't need to call both `-insertDataAtIndex:` and `-reloadData`. Use one or the other, whichever is more appropriate at the time.

**Comment by iangmaia** [comment]
Hi Eric,
It's CorePlot version 1.5.1. Happens on iOS 7 and iOS 8, iPhones 5, 5S and 6.

**Comment by eskroch** [comment]
Does the app always crash on the main thread? Is `-insertDataAtIndex:numberOfRecords:` or `-reloadData` ever called from another thread? I'm wondering if the plot's data cache is being modified simultaneously from multiple places.

**Comment by iangmaia** [comment]
All the calls are on the main thread. I'll review the plot cache data usage, but I'm pretty sure it's always from the main thread as well.

**Comment by eskroch** [comment]
Did you ever find the problem?
