### ISSUE TITLE
Gradient property for xAxis 's majorGridLineStyle (vertically)

### ISSUE THREAD

**Issue by iangmaia** [core-plot/core-plot#160]
I tried to create a vertical gradient for xAxis lines (see the image to check out the desired effect) but it seems that the lineGradient won't work for vertical gradients, even playing around with the "angle" property.

This is my gradient setup code: 
CPTMutableLineStyle *gridLineStyle = [CPTMutableLineStyle lineStyle];
CPTGradient *gradient = [CPTGradient gradientWithBeginningColor:[CPTColor colorWithCGColor:[[UIColor whiteColor] colorWithAlphaComponent:0.2].CGColor]
                                                    endingColor:[CPTColor colorWithCGColor:[UIColor blueColor].CGColor]];
gridLineStyle.lineGradient = gradient;
gridLineStyle.lineWidth = 0.5;
axisSet.xAxis.majorGridLineStyle = gridLineStyle;

What am I missing here?
Thanks!

![screen shot 2015-02-27 at 11 14 11](https://cloud.githubusercontent.com/assets/2152244/6410716/cdb49d4c-be71-11e4-83b4-fa070a20b8bf.png)

**Comment by eskroch** [comment]
Instead of the `lineGradient`, try the `lineFill`.

    gridLineStyle.lineFill = [CPTFill fillWithGradient:gradient];
