### ISSUE TITLE
CorePlot 1.5.1 and Swift

### ISSUE THREAD

**Issue by aminas** [core-plot/core-plot#162]
Hi Eric,

I tried Coreplot 1.5.1 release 2.0 Swift support. Thanks to Swift and your simplifications (e.g. NSNumber rather than NSDecimal), Coreplot is becoming an easier library to learn and deploy and that's exciting.

At the moment I haven't been able to fully build the chart I was looking for due to super high memory and cpu consumption. I'm a bit confused what's going on. I try to debug step by step and datasource function seems to get values correctly. I use a autolayout managed view as the hostView. Do I still have to add -ObjC argument?

**Comment by eskroch** [comment]
Did you profile the app in Instruments? Do you have any memory leaks that might contribute to high memory usage? Where are the performance hot spots?

**Comment by aminas** [comment]
oops! it was a stupid mistake of mine! it works now smoothly.
