### ISSUE TITLE
Directory Issue when using latest build from master branch

### ISSUE THREAD

**Issue by Sully73** [core-plot/core-plot#164]
I'm trying to upgrade from version 1.5.1 to the latest version on the master branch using cocopods. But I'm getting a Lexical or Preprocessor Issue because it cannot locate  <CorePlot/CorePlot.h>, it appears there is an additional directory to access the coreplot.h -- CorePlot/OSX/CorePlot.h. however, if I Change it to #import <CorePlot/osx/CorePlot.h>, then it can't locate the additional resources specified in the core plot header file.

I can revert back to 1.5 and it works fine, but I cannot get it to work for the latest commit on the master branch.

**Comment by eskroch** [comment]
What does your podfile look like? The following line should work:

    pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'

**Comment by Sully73** [comment]
Yes that is what I have.

**Comment by Sully73** [comment]
It appears that that  .xcconfig file includes additional HEADER_SEARCH_PATHS, that include the OS X 
"${PODS_ROOT}/Headers/Private/CorePlot/osx"
"${PODS_ROOT}/Headers/Public/CorePlot/osx"

**Comment by eskroch** [comment]
Is the platform set correctly for each target, e.g., `platform :ios, "8.0"`?

**Comment by trondkr** [comment]
This is exactly the same problem I have mentioned in issue #163. I have not been able to find a solution for this. Any suggestions for how to solve this issue would be greatly appreciated :)

**Comment by Sully73** [comment]
I have not found any solutions. It can't locate any of the header files. I have tried numerous things including solutions found [here](http://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files).  I also completely removed all cocoa pods and related files from the instructions [here](http://stackoverflow.com/questions/16427421/how-to-remove-cocoapods-from-a-project) and then reinstalled. But the issue remains.

If I create a new project it works fine. Just can't get it to work on existing project.

**Comment by eskroch** [comment]
As noted in the linked SO question, the problem is a conflict in your header search path. If there is an issue with the app target, removing and reinstalling the pods won't help. What is the header search path setting in the app target? Does it include all of the paths inherited from the .xconfig file created by CocoaPods?

**Comment by trondkr** [comment]
In my case the only thing I did was change the podfile from pod 'CorePlot', '~> 1.5.1' to pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'. I am not sure how that can have changed anything. It seems more likely that additional info has to be added for the target to now understand where the header files are located.

**Comment by Sully73** [comment]
My header search paths for my application target, seem to be fine.

![screen shot 2015-03-15 at 8 20 10 am](https://cloud.githubusercontent.com/assets/1440684/6655801/0909802e-caed-11e4-9c03-1628d9dfb4a5.png)

I added the "${PODS_ROOT}/Headers/Public" and "${PODS_ROOT}/Headers" to see if that would help. But no luck.

Like @trondkr the issue occurred when upgrading from 1.5.1 to the latest master branch commit. If I put 1.5 back in the podfile, it can locate the headers, but i get the error related to setterMethod(boundObject, boundSetter, tweenedValue); indicating to many parameters passed in.

**Comment by Sully73** [comment]
@eskroch Thanks very much for this, Everything is working now.
