### ISSUE TITLE
Endless recursion on removal of a (function) plot

### ISSUE THREAD

**Issue by mike-lischke** [core-plot/core-plot#166]
This is a crash I saw in the release-2.0 branch. On removal of a plot an endless recursion is triggered as the plot tries to load data (which is weird since it is being removed and shouldn't need any data).

![bildschirmfoto 2015-04-05 um 12 58 13](https://cloud.githubusercontent.com/assets/2398704/6996625/74ad2270-db93-11e4-98f0-cb0e1f6bdec3.png)

**Comment by mike-lischke** [comment]
Thanks for the fix. Looks like that would fix the crash but shows another problem:
`
2015-04-06 10:39:05:687 Pecunia[39843:30b] [Error] Exception reported by the runtime: An instance 0x113239480 of class CPTScatterPlot was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61000025f4a0> (
<NSKeyValueObservance 0x6100006d9e50: Observer: 0x610000092ca0, Key path: plotSpace, Options: <New: YES, Old: YES, Prior: NO> Context: 0x1007017c8, Property: 0x61000025f620>
`

**Comment by eskroch** [comment]
The function datasource holds a weak reference to the plot, so when the plot goes away, you have a dangling notification observer. Quick fix: make sure to release the datasource before the plot.

What are the pitfalls of making the datasource hold strong reference to the plot? The plot has a weak reference to its datasource, so I don't think we'd cause a retain cycle.

**Comment by mike-lischke** [comment]
Ok, releasing the datasource before the plot helped. I think it would make sense to make the datasource a strong reference in the plot instead of the current setup. The datasource would have a weak reference to the plot. And, in order to keep the pattern as with the other optional structures (line styles, axes etc),  I'd recommend to do data source creation in the same fashion, i.e. a normal constructor/factory method on a datasource and a property on the the plot where the created instance is assigned to. That would make it way easier to understand the ownership. As it is currently, it's not clear that you have to keep an external reference (you don't have to for all the axes, line styles, colors etc., so why should you for the datasource?).

**Comment by eskroch** [comment]
The plot datasource is modeled after the behavior of `NSTableView` and `UITableView`. Both of those classes use weak references to their datasource ([`NSTableView`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSTableView_Class/#//apple_ref/occ/instm/NSTableView/dataSource), [`UITableView`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableView_Class/index.html#//apple_ref/occ/instp/UITableView/dataSource)).

Using a strong reference to the datasource makes it too easy to cause a retain cycle. The datasource is often implemented in a view controller. If the controller keeps a strong reference to the tableview (or plot), you have a retain cycle. We use a weak reference in plots for the same reasons. Delegates work the same way.

Why wouldn't you keep a strong reference to the object serving as the datasource? If it's part of the view controller, AppKit or UIKit takes care of retaining it. If you provide another object as the datasource, it's up to you to manage it.

**Comment by mike-lischke** [comment]
Yes, I know, you explained this to me already and I understand your motivitation, but this approach contradicts so much with the rest of coreplot that it, IMO, adds more to confusion than to clarity. And you see yourself how often it clashes. It's not the first time I stumble across problems with it. Maybe it's just me, but I would never have found out to release the datasource first before releasing the plot myself. Whatever your design decision is after all, you should ensure that it doesn't cause crashes, if a user of coreplot doesn't follow your intention to the letter (e.g. ensure that a datasource unregisteres its observer(s) when the plot goes).

And a last thought: there's still a discrepancy in your comparison between NSTableView/UITableView's datasource and the plot datasource. In AppKit this is an protocol, implemented by a class that exists anyway. In coreplot you create a dedicated datasource class. To make this comparable you'd have to define a protocol also for the plot datasource so that we can implement it in a similar fashion as the table datasource.

**Comment by eskroch** [comment]
I fixed the crash you found by making the datasource class hold a strong reference to its plot. That lets it make sure it deregisters from notifications before the plot goes away. Since the plot holds only a weak reference to the datasource, we don't have a retain cycle. Release both, and they both go away without crashing.

The plot datasource *is* defined by a protocol (`<CPTPlotDatasource>` and friends). It is often implemented in a view controller, but it doesn't have to be. It is good practice to separate the view controller into smaller pieces to perform a single function (see, for example, http://khanlou.com/2014/09/8-patterns-to-help-you-destroy-massive-view-controller/). We provide the `CPTFunctionDataSource` class as a convenience for the case where the y-values are easily calculated from the x-values and as a demo of a way to provide lots of data points to the plot quickly. In all cases, something has to retain the datasource object. When it's part of the view controller, AppKit or UIKit takes care of it for you. Otherwise, it's your responsibility.

**Comment by mike-lischke** [comment]
Ok, I see, thanks.
