### ISSUE TITLE
The NSFullSizeContentViewWindowMask styleMask (OS X 10.10) prevents text drawing

### ISSUE THREAD

**Issue by eskroch** [core-plot/core-plot#167]
On OS X 10.10, the `NSFullSizeContentViewWindowMask` window `styleMask` prevents text layers (and possibly others) from drawing their contents. From NSWindow.h:

```objectivec
/* If set, the contentView will consume the full size of the window; it can be combined with other window style masks, but is only respected for windows with a titlebar.
    Utilizing this mask opts-in to layer-backing. Utilize the contentLayoutRect or auto-layout contentLayoutGuide to layout views underneath the titlebar/toolbar area.
 */
    NSFullSizeContentViewWindowMask NS_ENUM_AVAILABLE_MAC(10_10) = 1 << 15
```

Core Plot requires a layer *hosting* view. Update Core Plot to work with hosting views and layer-backed views.

See this [discussion thread](https://groups.google.com/forum/#!topic/coreplot-discuss/eI7UzIJjMM4) for further discussion.

**Comment by grng** [comment]
Created this description for a separate issue but then found this one. :)

----

All the plot labels are not drawn on the initial app load when I'm using `NSVisualEffectView` in the view hierarchy.

When I'm setting up the whole plot in `awakeFromNib`, `viewDidLoad` or first `viewWillAppear` calls, there're no labels on my app start. But setup in `viewDidAppear` always works.

If I go into another tab of my app and then return back, then labels appear when I re-setup a plot in `viewWillAppear` call.

There're no issues for any other screens, the bug happens only on the first screen that's visible immediately after the app's launch.

I wasn't able to reproduce it in a test project, sorry. It works for a small OS X app without issues.

But the main ideas are:
* plot appears as soon as app's window initially loaded
* plot is created in `awakeFromNib`, `viewDidLoad` or first `viewWillAppear`
* plot is inside `NSVisualEffectView` hierarchy that uses `NSFullSizeContentViewWindowMask`

Workaround: use `viewWillAppear` if possible.
