### ISSUE TITLE
Xcode 6.3 - semantic issue in Core Plot Gallery Example Project

### ISSUE THREAD

**Issue by S2V** [core-plot/core-plot#170]
![cptplot_m](https://cloud.githubusercontent.com/assets/5613351/7225934/3f98c3a4-e74c-11e4-8776-dfbc13bd33e8.png)

P.S. on 6.2 worked perfectly

**Comment by eskroch** [comment]
What version of Core Plot are you using? The latest code on GitHub doesn't show any warnings or errors for me.

**Comment by zch617** [comment]
add 2.0 to my project

**Comment by S2V** [comment]
@eskroch after copy last version from master - all work fine.
