### ISSUE TITLE
Potential bug in CorePlot

### ISSUE THREAD

**Issue by Horray** [core-plot/core-plot#175]
I'm able to add the legend to another cell, but when I do that, the text is upside down.

Here is my code:

- (void)configureLegend
{
    CPTGraph *graph = self.hostView.hostedGraph;
    CPTLegend *theLegend = [CPTLegend legendWithGraph:graph];

    // Add legend to graph
    graph.legend = theLegend;
    graph.legendAnchor = CPTRectAnchorRight;
    CGFloat legendPadding = - (self.chartView.bounds.size.width / 8);
    graph.legendDisplacement = CGPointMake(legendPadding, 0.0);

    UITableViewCell *cell = [self.tableView cellForRowAtIndexPath:[NSIndexPath indexPathForRow:2 inSection:0]];
    [cell.layer addSublayer:graph.legend];
This is what I tried:

    theLegend.transform = CATransform3DMakeRotation(M_PI / 180.0f, 0, 1, 0);
}
That didn't do anything. The results where the same. How can I get the text to show normally, not upside down?

Here is the question in stackoverflow: http://stackoverflow.com/questions/29908998/why-is-the-text-upside-down

**Comment by eskroch** [comment]
Not a bug. Answered on StackOverflow.
