### ISSUE TITLE
CPTAxis tickDirection crash at 64bit mode only.

### ISSUE THREAD

**Issue by kmugitani** [core-plot/core-plot#176]
I am not sure whether this is my problem,Core Plot or Apple Compiler problem. This problem happened with 64bit execution only. 32bit execution has no problem with same source.

I Environment
Xcode: 6.2 ,6.3,6.3.1
App: DenkiMonitor2(4.4.1) was rejected by Apple. Because crash happened at 64bit machine. Current AppStore version(4.4.0) has no problem.
Core Plot: hash 125262fa(master at Apr 26)
Target:  32bit machines and simulator  have no problem.
             64bit machines and simulator  have crash.

 Since the latest app does not pass Apple review, you can not download crash app from AppStore. Current AppStore version(4.4.0) has no problem. And it has pier1 price tag.

II Reproducing Procedure
1. With 64bit machine or 64bit target simulator, launching the app.
2. Grid screen appeared. There are nine Japanese electric utilities.
3. Crick any of them then cause the crash. If crash did not happen, app would display following screen.

![ios simulator screen shot jan 16 2015 18 53 20](https://cloud.githubusercontent.com/assets/12152796/7404076/f7bbf306-ef18-11e4-8c6f-6859f9df4095.png)

III Simulator log analysis

Wrong value was passed to CPTAxis setTickdirection.

bp at -(void)setTickDirection:(CPTSign)newDirection of CPTAxis.m

newDirection	has (CPTSign)4294967295.
But it should be CPTSignNegative. And Xcode has ability to correct SPTSign value it the value is correct.
====
IV  Source Analysis.

my source has 

    x.tickDirection = CPTSignNegative;
    
  This caused calling to CPTAxis's above method. 4294967295 is max value of 32bit int.

  Looks like compiler generated -1 of 32bit. and no conversion to 64bit int.
 But receiver interpreted it as 64 bit integer.  

V Current AppStore version
 Current AppStore version has same code about this part. And no problem at all, include 64bit mode.
 
Environment:
Xcode: 6.1
Core Plot: Jan 2015 or older version.

 Is this Apple compiler bug?

**Comment by eskroch** [comment]
How is Core Plot integrated into your app project? Cocoapods? Dependent project? Precompiled (by you) library?

**Comment by kmugitani** [comment]
My method is as follows.
1 Clone core-plot from github by SourceTree
2 Copy core-plot project file to my app project
3 Build by Xcode

So I think this is dependent project.

**Comment by eskroch** [comment]
Check your build settings and make sure you're getting both 32- and 64-bit builds.

`CPTSign` is declared as an `NSInteger`, so it should be fine on both architectures.

    typedef NS_ENUM (NSInteger, CPTSign)

**Comment by eskroch** [comment]
I just checked this in the "Axis Demo" in *Plot Gallery* example app. With the iOS 8.3 simulator in Xcode 6.3.1, it works fine in both 32- and 64-bit builds.

**Comment by kmugitani** [comment]
Sorry for spending your time. At last, I found my mistake. My project has wrong setting for Header Search Path. It referred older Core-Plot files at hg era. But dependent project has the latest one. Therefore there was inconsistency.
 Before finding this, the app passed Apple review with working around for CPTSign definition.
