### ISSUE TITLE
Crash in setXRange: when scrolling

### ISSUE THREAD

**Issue by naudecruywagen** [core-plot/core-plot#177]
Using CorePlot version 1.5.1.
iPad running iOS 8.3.

Stack trace:
![screen shot 2015-04-30 at 10 26 41](https://cloud.githubusercontent.com/assets/1192894/7409085/bd3ea984-ef23-11e4-83b5-42f1e76bb255.png)

Code:
![screen shot 2015-04-30 at 10 26 50](https://cloud.githubusercontent.com/assets/1192894/7409089/c5c9dc54-ef23-11e4-9030-d1e9118f5132.png)

range = (null)

**Comment by eskroch** [comment]
This is already fixed. You need to update to a newer version. Either get the latest code from GitHub or wait for the next release. 1.6 should be out soon.
