### ISSUE TITLE
Examples don't build

### ISSUE THREAD

**Issue by JetForMe** [core-plot/core-plot#179]
Checking out master, and opening the examples workspace, I'm unable to build the Mac applications out-of-the box:

```
error: /Users/rmann/Library/Developer/Xcode/DerivedData/CorePlotExamples-bbmomenbgmhdpdgtbcszvoktxtvj/Build/Products/Debug/CorePlot.framework: No such file or directory
```

This happens when I select CPTTestApp and click Run. It also happens if I close the workspace and open the CPTTestApp project directly.

Xcode 6.3.1 on OS 10.10.3.

**Comment by eskroch** [comment]
The examples all compile and run for me. Have you tried clean builds and/or deleting all of the derived data?

**Comment by JetForMe** [comment]
This is straight out of a download from Github.

> On May 11, 2015, at 18:31 , Eric Skroch <notifications@github.com> wrote:
> 
> The examples all compile and run for me. Have you tried clean builds and/or deleting all of the derived data?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Rick Mann
rmann@latencyzero.com

**Comment by eskroch** [comment]
Can you build the Core Plot framework by itself? I'm trying to figure out if the problem is the framework build or the configuration of the example app project. It works fine for me after deleting the derived data folder, both for the master branch and the release 1.6 package that I uploaded yesterday.

**Comment by JetForMe** [comment]
Yes, I can build the framework project, and I'm able to build it as a dependency within my own project. I just can't build the examples.

> On May 11, 2015, at 18:47 , Eric Skroch <notifications@github.com> wrote:
> 
> Can you build the Core Plot framework by itself? I'm trying to figure out if the problem is the framework build or the configuration of the example app project. It works fine for me after deleting the derived data folder, both for the master branch and the release 1.6 package that I uploaded yesterday.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Rick Mann
rmann@latencyzero.com

**Comment by eskroch** [comment]
Looking at CPTTestApp in release 1.6, the framework and app both have a build products location of "$(PROJECT_DIR)/../../build". This puts the build folder in the "Source" directory of the release package or at the root of the Core Plot project if building from the GitHub repository. I use the default Xcode setting for the derived data location. Do you use different settings for any other these properties?

**Comment by JetForMe** [comment]
My Xcode prefs show "~/Library/Developer/Xcode/DerivedData", with a Unique location within that.

Also, I believe I've got the 2.0 branch checked out.

Other than that, I have not modified your projects.

> On May 12, 2015, at 17:31 , Eric Skroch <notifications@github.com> wrote:
> 
> Looking at CPTTestApp in release 1.6, the framework and app both have a build products location of "$(PROJECT_DIR)/../../build". This puts the build folder in the "Source" directory of the release package or at the root of the Core Plot project if building from the GitHub repository. I use the default Xcode setting for the derived data location. Do you use different settings for any other these properties?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Rick Mann
rmann@latencyzero.com

**Comment by eskroch** [comment]
Try removing the Core Plot framework from the Copy Frameworks build phase and relinking the framework. That should fix any path issues with the framework.

**Comment by JetForMe** [comment]
That seemed to fix it. I'll let you close this issue if you like, or you can keep it open until you fix it in the repo.
