### ISSUE TITLE
many question in  release_1.6  release_2.0？

### ISSUE THREAD

**Issue by kscorpio** [core-plot/core-plot#180]
when i use  https://github.com/core-plot/core-plot/releases/tag/release_1.6 
build my project has error: 
 duplicate symbol l035 in:  libCorePlot-CocoaTouch.a
so i drag the file libCorePlot-CocoaTouch.a from  https://github.com/core-plot/core-plot/tree/release-2.0
the error is disappeared.
but there is new error:
1 y.orthogonalCoordinateDecimal = CPTDecimalFromUnsignedInteger(0); :
 Property 'orthogonalCoordinateDecimal' not found on object of type 'CPTXYAxis *'
2
+(id)plotRangeWithLocation:(NSDecimal)loc length:(NSDecimal)len;
   send nsdecimal to nsnumber
I replace the method with

+(instancetype)plotRangeWithLocation:(NSNumber *)loc length:(NSNumber *)len;
+(instancetype)plotRangeWithLocationDecimal:(NSDecimal)loc lengthDecimal:(NSDecimal)
 
then  run the app in ipone 5s ios7.1
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason:
'+[CPTPlotRange plotRangeWithLocationDecimal:lengthDecimal:]: unrecognized selector sent to class

**Comment by eskroch** [comment]
Some parts of the API have changed on the release-2.0 branch, mostly in an effort to make the interface with Swift easier. See [issue 96](https://github.com/core-plot/core-plot/issues/96) for some discussion of the changes. You need to pick either the 1.x or 2.0 API.

**Comment by kscorpio** [comment]
I cannot find CorePlotHeaders folder on the release-2.0 branch,so i 
get that folder on the release-1.6 and the file 
(libCorePlot-CocoaTouch.a) on the release-2.0 branch .If this is ok? 
(libCorePlot-CocoaTouch.a on release 1.6 lead to errors :52 duplicate 
symbol ,exit/code//1/(use -v to see invocation) )

在 2015/5/13 8:02, Eric Skroch 写道:

**Comment by eskroch** [comment]
If you've included the Core Plot project in your app project, just point the header search path to the Core Plot framework folder. You can also build your own static library with the "Universal Library" target that will create the CorePlotHeaders folder and copy the headers to it.

**Comment by kscorpio** [comment]
i use the release 1.6  drag the headerfolder and libcoreplot.a
when building , errors: 
duplicate symbol l048 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTTradingRangePlot.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTBarPlot.o)
duplicate symbol l031 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l032 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l033 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l034 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/T 0runk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l035 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l036 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l037 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l038 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l039 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l040 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l041 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l042 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l043 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTGradient.o)
duplicate symbol l058 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTScatterPlot.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTLayer.o)
duplicate symbol l038 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPieChart.o)
duplicate symbol l039 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPieChart.o)
duplicate symbol l040 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPieChart.o)
duplicate symbol l041 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPieChart.o)
duplicate symbol l042 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPieChart.o)
duplicate symbol l037 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotArea.o)
duplicate symbol l041 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTNumericData.o)
duplicate symbol l042 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTNumericData.o)
duplicate symbol l034 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTPlotSymbol.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTRangePlot.o)
duplicate symbol l021 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTLineCap.o)
duplicate symbol l022 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTLineCap.o)
duplicate symbol l023 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTLineCap.o)
duplicate symbol l021 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAnimation.o)
duplicate symbol l022 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAnimation.o)
duplicate symbol l023 in:
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/iphone/Documents/Trunk/iphoneCorePlotChart/libCorePlot-CocoaTouch.a(CPTAnimation.o)
ld: 52 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kscorpio** [comment]
In addition ，both of release 1.6 and 2.0 support arm64？，

**Comment by eskroch** [comment]
The duplicate symbols mean the app is somehow linked to multiple copies of the Core Plot library.

Yes, Core Plot has supported both 32- and 64-bit on iOS for several years.

**Comment by kscorpio** [comment]
but both de header files and the file libCorePlot-CocoaTouch.a， I get them from release1.6 /Binaries / iOS. And the duplicate symbols  error is in libCorePlot-CocoaTouch.a,how can i fix this problem. I need the library which the APIs  does not change

**Comment by eskroch** [comment]
Make sure your project only includes one copy of the Core Plot library. If you have any other dependencies, make sure you're not getting another copy from one of them. Do a clean build to clear out any references to previous versions that might be hanging around.

**Comment by lexar** [comment]
Hello, 
I just tried to replace the 1.5.1 release with the 1.6. release (libCorePlot-CocoaTouch.a/CorePlotHeaders) in an iOS project, and got the same error:
Property 'orthogonalCoordinateDecimal' not found on object of type 'CPTXYAxis *'.
after refactoring several occurences of plotRangeWithLocation:length: to plotRangeWithLocationDecimal:lengthDecimal.

I removed 1.5.1 from the project, deleted the folder, edited LibrarySearchPath by removing the old reference, cleaned and cleaned the build folder, but the error persisted. I am certain I never used 2.0.

I reverted back to 1.5.1, and the error disappeared immediately.

**Comment by eskroch** [comment]
It looks like the 2.0 headers were included in the 1.6 package. I'll have to do a 1.6.1 release to fix it.

**Comment by kscorpio** [comment]
"  It looks like the 2.0 headers were included in the 1.6 package. I'll have to do a 1.6.1 release to fix it. 
Could this lead to the duplicate symbols errors?

**Comment by kscorpio** [comment]
"  It looks like the 2.0 headers were included in the 1.6 package. I'll have to do a 1.6.1 release to fix it. 
Could this lead to the duplicate symbols errors?

**Comment by kscorpio** [comment]
"  It looks like the 2.0 headers were included in the 1.6 package. I'll have to do a 1.6.1 release to fix it. 
Could this lead to the duplicate symbols errors?

**Comment by kscorpio** [comment]
"  It looks like the 2.0 headers were included in the 1.6 package. I'll have to do a 1.6.1 release to fix it. 
Could this lead to the duplicate symbols errors?

**Comment by eskroch** [comment]
I just rebuilt the 1.6 release and uploaded the corrected files. You can download them from the [release 1.6 page](https://github.com/core-plot/core-plot/releases/tag/release_1.6).

**Comment by kscorpio** [comment]
#189 maybe the problem is not fixed successfully

**Comment by lewisj86** [comment]
what did orthogonalCoordinateDecimal change to?

**Comment by mxl** [comment]
@lewisj86 It's now `CPTXYAxis.orthogonalPosition`. https://github.com/core-plot/core-plot/search?utf8=✓&q=orthogonalCoordinateDecimal
