### ISSUE TITLE
scroll doesn't work well

### ISSUE THREAD

**Issue by oremag14jf** [core-plot/core-plot#181]
Using CorePlot version 1.6.
Running iOS 8.3.

I'm using Core-Plot with ScatterPlot for to represent multiples lines.
When I scroll, the graph moves to jumps and it locks. I don't know what happens. Can you help me?
Here my code:

```objc
#import <UIKit/UIKit.h>
#import "CorePlot-CocoaTouch.h"
@interface TemporalLineViewController :UIViewController<CPTPlotSpaceDelegate,CPTPlotDataSource,
CPTScatterPlotDelegate>

@property (strong, nonatomic) IBOutlet CPTGraphHostingView *hostingView;

@end


@interface TemporalLineViewController (){
    NSMutableDictionary *dates;
}
@property (nonatomic, readwrite, strong) NSArray *plotData;
@end

@implementation TemporalLineViewController
-(CPTGraph *)createGraph{
    //Create host view
    //self.hostView = [[CPTGraphHostingView alloc] initWithFrame:[[UIScreen mainScreen]bounds]];
    //self.hostView = [[CPTGraphHostingView alloc] initWithFrame:CGRectMake(viewGraph.frame.origin.x, viewGraph.frame.origin.y, 500, viewGraph.frame.size.height)];
    //self.view=self.hostView;
    
    CPTGraph *graph = [[CPTXYGraph alloc] initWithFrame:hostingView.bounds];
    [graph applyTheme:[CPTTheme themeNamed:kCPTSlateTheme]];
    //self.hostView.hostedGraph = graph;
    hostingView.hostedGraph=graph;
    
    // Axes
    CPTXYAxisSet *axisSet = (CPTXYAxisSet *)graph.axisSet;
    CPTXYAxis *x          = axisSet.xAxis;
    x.majorIntervalLength         = CPTDecimalFromDouble(ONEDAY);
    x.orthogonalCoordinateDecimal = CPTDecimalFromDouble(0.0);
    x.minorTicksPerInterval       = 0;
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"dd/MM/yyyy"];
    //dateFormatter.dateStyle = kCFDateFormatterShortStyle;
    CPTTimeFormatter *timeFormatter = [[CPTTimeFormatter alloc] initWithDateFormatter:dateFormatter];
    timeFormatter.referenceDate = [[NSDate alloc]init];
    x.labelFormatter            = timeFormatter;
    x.labelRotation             = CPTFloat(M_PI_4);
    
    CPTXYAxis *y = axisSet.yAxis;
    y.hidden=YES;
    y.orthogonalCoordinateDecimal = CPTDecimalFromInt(0);
    return graph;
}

-(void)createScatterPlot{
    
    CPTGraph * graph = [self createGraph];
     
    CPTXYPlotSpace *plotSpace = (CPTXYPlotSpace *)graph.defaultPlotSpace;
    NSTimeInterval xLow       = 0.0;
    plotSpace.xRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromDouble(xLow) length:CPTDecimalFromDouble(ONEDAY * 10.0)];
    plotSpace.yRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromDouble(-1) length:CPTDecimalFromDouble(5.0)];
    plotSpace.allowsUserInteraction = YES;
    plotSpace.allowsMomentum = YES;

    // Create a plot that uses the data source method
    CPTScatterPlot *diagnosticPlot = [self createScatterPlotWithIdentifier:DIAGNOSTIC_PLOT withLineColor:[CPTColor greenColor] withFillColor:[CPTColor greenColor]];
    // Create a plot that uses the data source method
    CPTScatterPlot *vaccinePlot = [self createScatterPlotWithIdentifier:VACCINE_PLOT withLineColor:[CPTColor blackColor] withFillColor:[CPTColor blackColor]];
    // Create a plot that uses the data source method
    CPTScatterPlot *interventionPlot = [self createScatterPlotWithIdentifier:INTERVENTION_PLOT withLineColor:[CPTColor blueColor] withFillColor:[CPTColor blueColor]];
    // Create a plot that uses the data source method
    CPTScatterPlot *smokingHabitPlot = [self createScatterPlotWithIdentifier:SMOKING_HABIT_PLOT withLineColor:[CPTColor yellowColor] withFillColor:[CPTColor yellowColor]];
    // Create a plot that uses the data source method
    CPTScatterPlot *menstrualPlot = [self createScatterPlotWithIdentifier:MENSTRUAL_PLOT withLineColor:[CPTColor redColor] withFillColor:[CPTColor redColor]];
    // Create a plot that uses the data source method
    CPTScatterPlot *menstrualTreatmentPlot = [self createScatterPlotWithIdentifier:MENSTRUAL_TREATMENT_PLOT withLineColor:[CPTColor orangeColor] withFillColor:[CPTColor orangeColor]];
    // Create a plot that uses the data source method
    CPTScatterPlot *psychomotorMilestonePlot = [self createScatterPlotWithIdentifier:PSYCHOMOTOR_MILESTONE_PLOT withLineColor:[CPTColor purpleColor] withFillColor:[CPTColor purpleColor]];
    
    [graph addPlot:vaccinePlot toPlotSpace:plotSpace];
    [graph addPlot:diagnosticPlot toPlotSpace:plotSpace];
    [graph addPlot:interventionPlot toPlotSpace:plotSpace];
    [graph addPlot:smokingHabitPlot toPlotSpace:plotSpace];
    [graph addPlot:menstrualPlot toPlotSpace:plotSpace];
    [graph addPlot:menstrualTreatmentPlot toPlotSpace:plotSpace];
    [graph addPlot:psychomotorMilestonePlot toPlotSpace:plotSpace];   
}

-(CPTScatterPlot *)createScatterPlotWithIdentifier:(NSString *)identifier withLineColor:(CPTColor *)lineColor withFillColor:(CPTColor *) fillColor{
    CPTScatterPlot *dataSourceLinePlot = [[CPTScatterPlot alloc] init];
    dataSourceLinePlot.identifier = identifier;
    
    CPTMutableLineStyle *lineStyle = [dataSourceLinePlot.dataLineStyle mutableCopy];
    lineStyle.lineWidth              = 3.0;
    lineStyle.lineColor              = lineColor;
    dataSourceLinePlot.dataLineStyle = lineStyle;
    CPTPlotSymbol *plotSymbol2 = [CPTPlotSymbol ellipsePlotSymbol];
    plotSymbol2.fill               = [CPTFill fillWithColor:fillColor];
    plotSymbol2.size               = CGSizeMake(10.0, 10.0);
    dataSourceLinePlot.plotSymbol = plotSymbol2;
    dataSourceLinePlot.dataSource = self;
    
    return dataSourceLinePlot;
}

-(void)generateData{
    NSMutableArray *data = [NSMutableArray array];
//create different data structure
    [data addObject:[self createDiagnosticData]];
    [data addObject:[self createVaccineData]];
    [data addObject:[self createInterventionData]];
    [data addObject:[self createSmokingHabitData]];
    [data addObject:[self createMenstrualData]];
    [data addObject:[self createMenstrualTreatmentData]];
    [data addObject:[self createPsychomotorMilestoneData]];
    self.plotData = data;
}

#pragma mark -
#pragma mark Plot Data Source Methods

-(NSUInteger)numberOfRecordsForPlot:(CPTPlot *)plot
{
    NSLog(@"numberOfRecordsForPlot");
    if ([plot.identifier isEqual:DIAGNOSTIC_PLOT]) {
        NSMutableArray *data = self.plotData[0];
        return data.count;
    }else if([plot.identifier isEqual:VACCINE_PLOT]){
        NSMutableArray *data = self.plotData[1];
        return data.count;
    } else if([plot.identifier isEqual:INTERVENTION_PLOT]){
        NSMutableArray *data = self.plotData[2];
        return data.count;
    } else if([plot.identifier isEqual:SMOKING_HABIT_PLOT]){
        NSMutableArray *data = self.plotData[3];
        return data.count;
    } else if([plot.identifier isEqual:MENSTRUAL_PLOT]){
        NSMutableArray *data = self.plotData[4];
        return data.count;
    } else if([plot.identifier isEqual:MENSTRUAL_TREATMENT_PLOT]){
        NSMutableArray *data = self.plotData[5];
        return data.count;
    } else if([plot.identifier isEqual:PSYCHOMOTOR_MILESTONE_PLOT]){
        NSMutableArray *data = self.plotData[6];
        return data.count;
    }
    return 0;
}

-(id)numberForPlot:(CPTPlot *)plot field:(NSUInteger)fieldEnum recordIndex:(NSUInteger)index
{
    NSLog(@"numberForPlot");
    if ([plot.identifier isEqual:DIAGNOSTIC_PLOT]) {
        NSMutableArray *data = self.plotData[0];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        if ([str intValue]==0) {
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if([plot.identifier isEqual:VACCINE_PLOT]){
        NSMutableArray *data = self.plotData[1];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        return data[index][@(fieldEnum)];
    }else if([plot.identifier isEqual:INTERVENTION_PLOT]){
        NSMutableArray *data = self.plotData[2];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        return data[index][@(fieldEnum)];
    }else if ([plot.identifier isEqual:SMOKING_HABIT_PLOT]) {
        NSMutableArray *data = self.plotData[3];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        if ([str intValue]==0) {
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if ([plot.identifier isEqual:MENSTRUAL_PLOT]) {
        NSMutableArray *data = self.plotData[4];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        if ([str intValue]==0) {
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if ([plot.identifier isEqual:MENSTRUAL_TREATMENT_PLOT]) {
        NSMutableArray *data = self.plotData[5];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        if ([str intValue]==0) {
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if([plot.identifier isEqual:PSYCHOMOTOR_MILESTONE_PLOT]){
        NSMutableArray *data = self.plotData[6];
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        return data[index][@(fieldEnum)];
    }
    return nil;
}
```

**Comment by eskroch** [comment]
Does the graph appear correctly at first and then has problems only when scrolling? Are you using a plot space delegate? If so, what does it do?

**Comment by oremag14jf** [comment]
Yes, I use a plot space delegate.

The graph appear correctly, but when I scroll it, it moves only a little and it stop. I have to scroll it again, and it moves only a little and it stop.

**Comment by eskroch** [comment]
Temporarily remove the plot space delegate and see if that resolves the scrolling problem. If so, the issue is in the implementation of the delegate. Post the delegate code here if you need help troubleshooting.

**Comment by oremag14jf** [comment]
I've done what you told me and it doesn't work. All my code is this:

#import <UIKit/UIKit.h>
#import "CorePlot-CocoaTouch.h"

@interface TemporalLineViewController : UIViewController<CPTPlotSpaceDelegate,CPTPlotDataSource,
CPTScatterPlotDelegate>
@property (strong, nonatomic) NSManagedObjectContext *managedObjectContext;
@property (strong, nonatomic) IBOutlet CPTGraphHostingView *hostingView;
@end

- (void)viewDidLoad {
    [super viewDidLoad];
   self.title=@"TEMPORAL LINE";

    AppDelegate *app = (AppDelegate*)[[UIApplication sharedApplication] delegate];
    self.managedObjectContext = app.managedObjectContext;
    
    dates = [[NSMutableDictionary alloc]init];
    [self generateData];
    [self createScatterPlot];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

-(void)createScatterPlot{
    CPTGraph * graph = [self createGraph];
    // Setup scatter plot space

    CPTXYPlotSpace *plotSpace = (CPTXYPlotSpace *)graph.defaultPlotSpace;
    NSTimeInterval xLow       = 0.0;
    plotSpace.xRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromDouble(xLow) length:CPTDecimalFromDouble(ONEDAY * 10.0)];
    plotSpace.yRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromDouble(-1) length:CPTDecimalFromDouble(5.0)];
    plotSpace.allowsUserInteraction = YES;
    plotSpace.delegate=self;
    

    CPTScatterPlot *diagnosticPlot = [self createScatterPlotWithIdentifier:DIAGNOSTIC_PLOT withLineColor:[CPTColor greenColor] withFillColor:[CPTColor greenColor]];
    CPTScatterPlot *vaccinePlot = [self createScatterPlotWithIdentifier:VACCINE_PLOT withLineColor:[CPTColor blackColor] withFillColor:[CPTColor blackColor]];
    CPTScatterPlot *interventionPlot = [self createScatterPlotWithIdentifier:INTERVENTION_PLOT withLineColor:[CPTColor blueColor] withFillColor:[CPTColor blueColor]];
    CPTScatterPlot *smokingHabitPlot = [self createScatterPlotWithIdentifier:SMOKING_HABIT_PLOT withLineColor:[CPTColor yellowColor] withFillColor:[CPTColor yellowColor]];
    CPTScatterPlot *menstrualPlot = [self createScatterPlotWithIdentifier:MENSTRUAL_PLOT withLineColor:[CPTColor redColor] withFillColor:[CPTColor redColor]];
    CPTScatterPlot *menstrualTreatmentPlot = [self createScatterPlotWithIdentifier:MENSTRUAL_TREATMENT_PLOT withLineColor:[CPTColor orangeColor] withFillColor:[CPTColor orangeColor]];
    CPTScatterPlot *psychomotorMilestonePlot = [self createScatterPlotWithIdentifier:PSYCHOMOTOR_MILESTONE_PLOT withLineColor:[CPTColor purpleColor] withFillColor:[CPTColor purpleColor]];
    [graph addPlot:vaccinePlot toPlotSpace:plotSpace];
    [graph addPlot:diagnosticPlot toPlotSpace:plotSpace];
    [graph addPlot:interventionPlot toPlotSpace:plotSpace];
    [graph addPlot:smokingHabitPlot toPlotSpace:plotSpace];
    [graph addPlot:menstrualPlot toPlotSpace:plotSpace];
    [graph addPlot:menstrualTreatmentPlot toPlotSpace:plotSpace];
    [graph addPlot:psychomotorMilestonePlot toPlotSpace:plotSpace];
}

-(CPTGraph *)createGraph{
    CPTGraph *graph = [[CPTXYGraph alloc] initWithFrame:hostingView.bounds];
    [graph applyTheme:[CPTTheme themeNamed:kCPTSlateTheme]];
    hostingView.hostedGraph=graph;
   
    // Axes
    CPTXYAxisSet *axisSet = (CPTXYAxisSet *)graph.axisSet;
    CPTXYAxis *x          = axisSet.xAxis;
    x.majorIntervalLength         = CPTDecimalFromDouble(ONEDAY);
    x.orthogonalCoordinateDecimal = CPTDecimalFromDouble(0.0);
    x.minorTicksPerInterval       = 0;
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"dd/MM/yyyy"];
    CPTTimeFormatter *timeFormatter = [[CPTTimeFormatter alloc] initWithDateFormatter:dateFormatter];
    timeFormatter.referenceDate = [[NSDate alloc]init];
    x.labelFormatter            = timeFormatter;
    x.labelRotation             = CPTFloat(M_PI_4);
    
    CPTXYAxis *y = axisSet.yAxis;
    y.hidden=YES;
    y.orthogonalCoordinateDecimal = CPTDecimalFromInt(0);
    
    return graph;
}

-(CPTScatterPlot *)createScatterPlotWithIdentifier:(NSString *)identifier withLineColor:(CPTColor *)lineColor withFillColor:(CPTColor *) fillColor{
    CPTScatterPlot *dataSourceLinePlot = [[CPTScatterPlot alloc] init];
    dataSourceLinePlot.identifier = identifier;
    
    CPTMutableLineStyle *lineStyle = [dataSourceLinePlot.dataLineStyle mutableCopy];
    lineStyle.lineWidth              = 3.0;
    lineStyle.lineColor              = lineColor;
    dataSourceLinePlot.dataLineStyle = lineStyle;
    CPTPlotSymbol *plotSymbol2 = [CPTPlotSymbol ellipsePlotSymbol];
    plotSymbol2.fill               = [CPTFill fillWithColor:fillColor];
    plotSymbol2.size               = CGSizeMake(10.0, 10.0);
    dataSourceLinePlot.plotSymbol = plotSymbol2;
    dataSourceLinePlot.dataSource = self;
    
    return dataSourceLinePlot;
}

-(void)generateData{
    NSMutableArray *data = [NSMutableArray array];
    [data addObject:[self createDiagnosticData]];
    [data addObject:[self createVaccineData]];
    [data addObject:[self createInterventionData]];
    [data addObject:[self createSmokingHabitData]];
    [data addObject:[self createMenstrualData]];
    [data addObject:[self createMenstrualTreatmentData]];
    [data addObject:[self createPsychomotorMilestoneData]];
    self.plotData = data;
}

#pragma mark -
#pragma mark Plot Data Source Methods

-(NSUInteger)numberOfRecordsForPlot:(CPTPlot *)plot
{
    NSLog(@"numberOfRecordsForPlot");
    if ([plot.identifier isEqual:DIAGNOSTIC_PLOT]) {
        NSMutableArray *data = self.plotData[0];
        return data.count;
    }else if([plot.identifier isEqual:VACCINE_PLOT]){
        NSMutableArray *data = self.plotData[1];
        return data.count;
    } else if([plot.identifier isEqual:INTERVENTION_PLOT]){
        NSMutableArray *data = self.plotData[2];
        return data.count;
    } else if([plot.identifier isEqual:SMOKING_HABIT_PLOT]){
        NSMutableArray *data = self.plotData[3];
        return data.count;
    } else if([plot.identifier isEqual:MENSTRUAL_PLOT]){
        NSMutableArray *data = self.plotData[4];
        return data.count;
    } else if([plot.identifier isEqual:MENSTRUAL_TREATMENT_PLOT]){
        NSMutableArray *data = self.plotData[5];
        return data.count;
    } else if([plot.identifier isEqual:PSYCHOMOTOR_MILESTONE_PLOT]){
        NSMutableArray *data = self.plotData[6];
        return data.count;
    }
    return 0;
}

-(id)numberForPlot:(CPTPlot *)plot field:(NSUInteger)fieldEnum recordIndex:(NSUInteger)index
{
    NSLog(@"numberForPlot");
    if ([plot.identifier isEqual:DIAGNOSTIC_PLOT]) {
        NSMutableArray *data = self.plotData[0];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if([plot.identifier isEqual:VACCINE_PLOT]){
        NSMutableArray *data = self.plotData[1];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if([plot.identifier isEqual:INTERVENTION_PLOT]){
        NSMutableArray *data = self.plotData[2];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if ([plot.identifier isEqual:SMOKING_HABIT_PLOT]) {
        NSMutableArray *data = self.plotData[3];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if ([plot.identifier isEqual:MENSTRUAL_PLOT]) {
        NSMutableArray *data = self.plotData[4];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if ([plot.identifier isEqual:MENSTRUAL_TREATMENT_PLOT]) {
        NSMutableArray *data = self.plotData[5];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }else if([plot.identifier isEqual:PSYCHOMOTOR_MILESTONE_PLOT]){
        NSMutableArray *data = self.plotData[6];
        NSLog(@"VALOR: %@", data[index][@(fieldEnum)]);
        NSString *str = [NSString stringWithFormat:@"%@",(data[index][@(fieldEnum)])];
        NSLog(@"%d",[str intValue]);
        if ([str intValue]==0) {
            NSLog(@"NIL");
            return nil;
        }
        return data[index][@(fieldEnum)];
    }
    return nil;
}

**Comment by eskroch** [comment]
Where are your delegate methods? I only see the graph setup and datasource methods?

**Comment by oremag14jf** [comment]
What delegate methods?

**Comment by eskroch** [comment]
You declared the controller as implementing the `<CPTPlotSpaceDelegate> and <CPTScatterPlotDelegate> protocols and set the plot space delegate. What delegate methods did you implement and what do they do?

**Comment by oremag14jf** [comment]
I only implement:
-(id)numberForPlot:(CPTPlot *)plot field:(NSUInteger)fieldEnum recordIndex:(NSUInteger)index
-(NSUInteger)numberOfRecordsForPlot:(CPTPlot *)plot

**Comment by eskroch** [comment]
That method and `-numberOfRecordsForPlot:` are part of the datasource. All of the [plot space delegate methods](http://core-plot.github.io/iOS/protocol_c_p_t_plot_space_delegate-p.html) are optional, so omitting them shouldn't have an adverse effect on the app. It's just confusing seeing the delegate declared and set, and yet not implemented. A bad plot space delegate could easily cause the problem you describe.

**Comment by oremag14jf** [comment]
I delete CPTPlotSpaceDelegate: 

@interface TemporalLineViewController : UIViewController<CPTPlotDataSource,
CPTScatterPlotDelegate>

And the problem continues.

**Comment by eskroch** [comment]
I don't see any obvious problems with the code posted here. How many data points are in each plot? A large number of data points might cause rendering or memory issues that would affect performance. Do you call any methods on the graph from elsewhere in the app? If so, make sure that that always happens on the main thread and that it is not causing the issue.

**Comment by oremag14jf** [comment]
I tested with only one data point and happens the same. There aren't calls to methods on the graph out of this class.

**Comment by eskroch** [comment]
It's not clear from your description what "the graph moves to jumps and it locks" means. Can you elaborate? Can you post a video showing the problem?

Does the problem occur in the simulator, on a device, or both?

**Comment by oremag14jf** [comment]
The problem occur in the simulator. I haven't tested in a device.

**Comment by eskroch** [comment]
I don't know what "the graph moves to jumps and it locks" means. Can you describe your interaction with the graph and how it responds in more detail?

**Comment by oremag14jf** [comment]
When I scroll the chart, it only moves a little and it locks. It doesn't move continuously.

**Comment by eskroch** [comment]
Does the plot always get stuck at the same place? If you pick up your finger (mouse button on the simulator) and touch the plot again, can you scroll past the point where it gets stuck?

**Comment by oremag14jf** [comment]
Yes. When I touch the plot and I scroll, it moves a little and gets stuck. If I touch the plot again, in any point, the plot scrolls a little and gets stuck again.

**Comment by eskroch** [comment]
I'm still not clear on exactly what's happening and I don't see any obvious problems in the posted code. We can continue the troubleshooting on the [discussion board](https://groups.google.com/forum/#!forum/coreplot-discuss) if you have more information to add.
