### ISSUE TITLE
Core ploat for 32 and 64 bit both

### ISSUE THREAD

**Issue by maahi22** [core-plot/core-plot#182]
from 1 june 2015 ios support 64 bit necessary is there any lib for supporting both version .plz give me link
 

Thanks in Adv
mahendra

**Comment by eskroch** [comment]
Core Plot has supported both 32- and 64-bit builds on iOS for several years.

**Comment by maahi22** [comment]
When i use it for 64 bit its working fine on simulator as well as device  but failed when create a archive.. don't know why any idea.. please help.

**Comment by eskroch** [comment]
Make sure your build settings include both architectures. The "Build Active Architecture Only" setting should be "No" for release builds.
