### ISSUE TITLE
How to get a smooth experience when move CandleStick plot?

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#183]
I have set 'allowsMomentumX' and 'allowsMomentumY', also i have reset 'momentumAcceleration',
 How can i get a similar effect like I scroll a tableview, perfect decelerate time, distance and animation.
 Thanks a lot.

**Comment by eskroch** [comment]
What did you change `momentumAcceleration` to? The default value should give an effect similar to a tableview.

There are several properties that control scrolling momentum:

```objc
@property (nonatomic, readwrite) BOOL allowsMomentum;
@property (nonatomic, readwrite) BOOL allowsMomentumX;
@property (nonatomic, readwrite) BOOL allowsMomentumY;
@property (nonatomic, readwrite) CPTAnimationCurve momentumAnimationCurve;
@property (nonatomic, readwrite) CPTAnimationCurve bounceAnimationCurve;
@property (nonatomic, readwrite) CGFloat momentumAcceleration;
@property (nonatomic, readwrite) CGFloat bounceAcceleration;
@property (nonatomic, readwrite) CGFloat minimumDisplacementToDrag;
```

**Comment by Toanso** [comment]
I rewrite a custom CPTAnimationTimingFunction,  I pre generate a spline points like the implement of a scrollview in android , and use it when calculate animation progress and got a smooth experience. Thanks a lot eskroch.

**Comment by eskroch** [comment]
No response to request for further information.
