### ISSUE TITLE
Duplicated symbols on arm64 when building using Xcode 6.2

### ISSUE THREAD

**Issue by mervynokm** [core-plot/core-plot#189]
Hi, having this issue on Xcode < 6.3. Noticed it was a previous bug on which was fixed yesterday with the updated 1.6 build, but the issue still occurs when building on Xcode 6.2 causing a failure.

*It can build properly on Xcode 6.3 and above 

Hope you could have a look at it!

duplicate symbol l023 in:
    /Users/mong/ios/Frameworks/CorePlot/libCorePlot-CocoaTouch.a(CPTAxisLabel.o)
    /Users/mong/ios/Frameworks/CorePlot/libCorePlot-CocoaTouch.a(CPTAnimation.o)
ld: 51 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kscorpio** [comment]
I have asked this question， in #180 

eskroch： 
”It looks like the 2.0 headers were included in the 1.6 package. I'll have to do a 1.6.1 release to fix it.“
”I just rebuilt the 1.6 release and uploaded the corrected files. You can download them from the release 1.6 page.“

but i can not find release 1.6.1， if you use the release 1.6 yesterday, maybe the problem did not fixed?

**Comment by eskroch** [comment]
@kscorpio There is no 1.6.1 release. I replaced the broken 1.6 files with corrected ones. Download new copies if you need them. The build error in the old version wouldn't cause a duplicated symbol linker error. It used the 2.0 API, so the app likely wouldn't even compile without some changes.

**Comment by eskroch** [comment]
Duplicate linker symbols are caused by referencing more than one copy of the Core Plot library. Did you include both the pre-built library and the Core Plot project file in your app? If so, pick one to use and delete the other one. Also, do a clean build if you haven't already done so.

**Comment by kscorpio** [comment]
ok i wil check my project
