### ISSUE TITLE
Feature request for monotonic cubic interpolation

### ISSUE THREAD

**Issue by wanyancan** [core-plot/core-plot#193]
There was a known issue that current smooth plot will have undesirable overshoot interpolation if the nearby points have different sign of 1st derivative. 

It would be nice to use monotonic cubic interpolation which solves the 1st derivative at each point to prevent it from changing sign in each segment.

Please see one of the implementation here : http://en.m.wikipedia.org/wiki/Monotone_cubic_interpolation

**Comment by eskroch** [comment]
Pull request #268 added support for cubic Hermite spline interpolation, without the monotonic restriction.
