### ISSUE TITLE
CorePlot does not build on Xcode 7 beta with iOS 9

### ISSUE THREAD

**Issue by rplankenhorn** [core-plot/core-plot#194]
There are several build issues with CorePlot on iOS 9.  Here are some of them:

Xcode doesn't like comments that contain an ampersand sign:
/// @cond
/// @endcond

/** @brief @optional Informs the delegate that an animation operation started animating.
 *  @param operation The animation operation.
 **/

This causes an error:  "Maco name is a reserved identifier"
#if CPT_SDK_SUPPORTS_WEAK
#define __cpt_weak        __weak

I have found a lot more and I will try and add them as I find them.

**Comment by rplankenhorn** [comment]
Here are the changes I had to make in order to get it to build:

https://www.dropbox.com/s/tbocc4lb6suni94/coreplot_fixes.diff?dl=0

**Comment by eskroch** [comment]
Those comments are required for the Doxygen documentation. I'll see if there is another workaround that will let us keep the documentation comments intact.

**Comment by rplankenhorn** [comment]
This is also causing issues:

``` objective-c
#if CPT_SDK_SUPPORTS_WEAK
#define __cpt_weak        __weak
#define cpt_weak_property weak
#else
#if __clang__ && (__clang_major__ >= 3)
#define __cpt_weak __unsafe_unretained
#else
#define __cpt_weak
#endif
#define cpt_weak_property assign
#endif
```

**Comment by eskroch** [comment]
There are also some issues with non null pointers. Apple added nullability annotations to the SDK headers. I'm working on fixing all of the Xcode 7 issues.

**Comment by rplankenhorn** [comment]
@eskroch Thanks!

**Comment by c0nk** [comment]
Do you have an estimate when some of these fixes can be committed?

**Comment by eskroch** [comment]
I have a little more testing to do. I'll hopefully be done in another day or two.

**Comment by gordyeung** [comment]
I've encountered this issue again after I've updated my Xcode to version 7 (7A220): Core Plot (1.6) failed to compile (macro name is a reserved identifier) at:

#if CPT_SDK_SUPPORTS_WEAK
#define __cpt_weak        __weak
#define cpt_weak_property weak
#else
#if __clang__ && (__clang_major__ >= 3)
#define __cpt_weak __unsafe_unretained
#else
#define __cpt_weak
#endif
#define cpt_weak_property assign
#endif
