### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by liumin007** [core-plot/core-plot#199]
first，I‘m sorry to my English  is too bad.   when I used static library The three problems，Would you please tell me, what should I do。 Are you  understand me ?  thanks very much
![8b86644c-4fae-4775-bce9-cf03bc744665](https://cloud.githubusercontent.com/assets/8297744/8346098/5aaa833c-1b2a-11e5-8b39-46463d6b7516.jpg)
![17775952-5ad0-4da8-8571-e34af560cab3](https://cloud.githubusercontent.com/assets/8297744/8346109/7e7932ae-1b2a-11e5-9664-fa6e04386acf.png)

**Comment by mike-lischke** [comment]
You are missing the accelerate framework. Add this to the linker list and these problems should disappear.
