### ISSUE TITLE
TickLabelDirection changed during user interaction.

### ISSUE THREAD

**Issue by paulop5288** [core-plot/core-plot#201]
I am using customized Y Axis labels. I have changed the tick label direction to CPTSignPositive.
y.tickLabelDirection = CPTSignPositive;
But as I started moving the graph, the labels moved to the left hand side of the Y axis. There is no code that has changed the direction. I have try to change the default of CPTXYAxis to CPTSignPositive, but this problem still exist.
What is possible causing this?

Thanks.

**Comment by eskroch** [comment]
What is the `labelOffset`? A negative offset will place the label on the other side of the axis.

What is the `xRange` of the plot space? A negative length reverses the direction of the axis, i.e., the negative direction goes to the right instead of to the left.
