### ISSUE TITLE
PlotSpace zoom out lead to memory raise 

### ISSUE THREAD

**Issue by kscorpio** [core-plot/core-plot#202]
1 I use Scatter Plot， and did not add any point in， when zoom out extremely ，the Axis label become very intensive ， like white label. and the moving plot delay；how to resolve this ？ only to limit the xrange and yrange？

2 the the number of plotdata （x y couples） is more than 200， 
   x range is ： 0 ~  15  ，one pont per 0.05；
 y range is ：-4 ~ +4
 how to change the  unit length scale of x：y  （ x：y =10 ：1 is better）

**Comment by eskroch** [comment]
Either change the `majorIntervalLength` as the user zooms in (use a plot space delegate to monitor changes to the plot space) or try the the `CPTAxisLabelingPolicyAutomatic` labeling policy.
