### ISSUE TITLE
How to set the label

### ISSUE THREAD

**Issue by liumin007** [core-plot/core-plot#203]
I used the methods - (void)barPlot:(CPTBarPlot *)plot barWasSelectedAtRecordIndex:(NSUInteger)idx withEvent:(UIEvent *)event     Click on a column
![Uploading 1.png…]()

then reloadData   ，Tags before will not be removed
![Uploading 2.png…]()

What should I do in this situation

**Comment by eskroch** [comment]
Are you using annotations? You have to remove the old one when you're done with it.
