### ISSUE TITLE
CorePlot-CocoaTouch.h not found when installed with CocoaPods 0.38.0.beta.1

### ISSUE THREAD

**Issue by slizeray** [core-plot/core-plot#204]
If you install CorePlot with CocoaPods 0.38.0.beta.1 you can't compile your project because the header files are not copied into Pods/Headers/Public/CorePlot/ios

It works fine with previous versions of CocoaPods

**Comment by eskroch** [comment]
Which version of Core Plot does your podfile point to? Is it a release or GitHub?

**Comment by jhollida24** [comment]
I'm seeing this issue in 0.37.2 as well.

I'm using the official release.

**Comment by jhollida24** [comment]
Looks like the header can be found by importing:

```
#import <CorePlot/ios/CorePlot.h>
```

For whatever reason, the headers are nested within an `ios` folder under `Pods/Headers/Public`

**Comment by eskroch** [comment]
With the following line in the podfile, it works for me.

    pod 'CorePlot', '~>1.6'

Either of the following `#import` statements should work:

    #import "CorePlot-CocoaTouch.h"
    #import "CorePlot.h"

**Comment by benleiken** [comment]
@jhollida24 thanks! fixed this issue for me

**Comment by sirnacnud** [comment]
I am running in to this issue as well when upgrading from cocoa pods 0.38.2 to 0.39.beta.3. Neither `#import "CorePlot-CocoaTouch.h"` or `#import "CorePlot.h"` worked and I had to use @jhollida24's suggestion.

**Comment by eskroch** [comment]
`#import <CorePlot/ios/CorePlot.h>` is the correct header reference when building Core Plot as a framework (CocoaPods option `use_frameworks!`).

**Comment by sirnacnud** [comment]
I'm not building Core Plot as a framework, my pods are put in to a static library.

**Comment by Hung-Hsun** [comment]
I found another solution. Go to "Build Settings" -> "Header Search Paths" -> Make the header search path of CorePlot to be recursive. Then compile it and CorePlot-CocoaTouch.h could be found.

**Comment by mamaral** [comment]
+1 to @Hung-Hsun's suggestion.

<img width="547" alt="screen shot 2015-10-28 at 2 54 05 pm" src="https://cloud.githubusercontent.com/assets/6086409/10799545/c51bc954-7d83-11e5-8df0-2bfcbd204494.png">

+ 

```
#import <CorePlot-CocoaTouch.h>
```

**Comment by derjohng** [comment]
+1 to @Hung-Hsun, "recursive" resolve my issue.

**Comment by pbpios** [comment]
Using pod 'CorePlot', '~> 2.0'
#import "CorePlot-CocoaTouch.h" file not found 
Not working for me on xcode 7.2

**Comment by eskroch** [comment]
@pbpios Please be more specific. What have you tried?
