### ISSUE TITLE
Cast from 'const void *' to 'double *' drops const qualifier

### ISSUE THREAD

**Issue by BrookeHatfield** [core-plot/core-plot#207]
Hi,

I just upgraded to Xcode 7.3 beta. I found and applied fix #194.  I am now getting an error form CPTPlot.m.  

Cast from 'const void*' to 'double *' drops const qualifier. 

 This occurs three times and is associated with the '(double *) sourceEnd'  and (double *)numbers.bytes.

The odd thing is that I complied a core plot demo code and it compiles and runs OK. 

The code that fails with Xcdoe7.3 beta compiled just fine in Xcode 6.4.

I am at a bit of a loss as to where to start looking.

Has anyone else seen this error and has anyone found a fix? I performed a search for this and did not find any references for coreplot

![castfromconstvoid](https://cloud.githubusercontent.com/assets/13385156/8754563/3b711dae-2c79-11e5-827d-ba08787232f4.png)

**Comment by BrookeHatfield** [comment]
I added 'const' to the statements in CPTPlot.m and this 'fixed' the error.

**Comment by eskroch** [comment]
There are fixes for this and other Xcode 7-specific issues on the [xcode-7 branch](https://github.com/core-plot/core-plot/tree/xcode-7). I'll merge this branch into the "release-2.0" branch once Xcode 7 is out of beta.

**Comment by BrookeHatfield** [comment]
Hi Eric,

Thanks!  

Brooke


BTW.  I am enjoying the core plot tool set.  I have much to learn, but am thrilled that you’ve done so much work - that I don’t have to do!
