### ISSUE TITLE
Method override for the designated initializer of the superclass '-init' not found 

### ISSUE THREAD

**Issue by BrookeHatfield** [core-plot/core-plot#208]
Hi ,

I recently upgraded to Xcode 7.3 beta and am getting this error:

Method override for the designated initializer of the superclass '-init' not found 

in CPTColorSpace.m and CPTColor.m

Apparently this has been an issue with swift for a while. see http://stackoverflow.com/questions/29639040/warning-method-override-for-designated-initializer

**Comment by eskroch** [comment]
There are fixes for this and other Xcode 7-specific issues on the [xcode-7 branch](https://github.com/core-plot/core-plot/tree/xcode-7). I'll merge this branch into the "release-2.0" branch once Xcode 7 is out of beta.
