### ISSUE TITLE
Crash on CPTPlot drawInContext method

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#209]
Hi,
    The crash is occasional.
    crash line is 472
    id<CPTPlotDelegate> theDelegate = (id<CPTPlotDelegate>)self.delegate;

  I rewrite this line and add these lines below to the front of the crash line. 

 if (!self) {
        return;
    }
    if (!self.delegate) {   //  It also will crash at this line.
        return;
    }

In my app, the graph data source is dynamic changed,
 so [graph reloadData] method is frequent invoked.
Any suggestion is welcomed.

Thanks a lot.

**Comment by eskroch** [comment]
Can you post the crash log and/or stack trace from the crash? Make sure that `-reloadData` and any other Core Plot method that affects the data or drawing is only called from the main thread of your application.

We cache the delegate reference in a local variable because the plot holds a weak reference to its delegate. This way we ensure that the delegate object won't be deallocated before we call the `-didFinishDrawing` method.

**Comment by Toanso** [comment]
Thread : Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000020

0  libobjc.A.dylib                0x0000000196c540b4 objc_retain + 20
1  Stock                          0x0000000100295808 -[CPTPlot drawInContext:] (CPTPlot.m:472)
2  QuartzCore                     0x0000000189334da0 CABackingStoreUpdate_ + 2580
3  QuartzCore                     0x000000018933437c x_blame_allocations + 108
4  QuartzCore                     0x0000000189333f00 CA::Layer::display_() + 1276
5  Stock                          0x00000001001f3990 -[CPTLayer display] (CPTLayer.m:310)
6  QuartzCore                     0x0000000189314a18 CA::Layer::display_if_needed(CA::Transaction*) + 244
7  QuartzCore                     0x00000001893146d0 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 44
8  QuartzCore                     0x0000000189313e58 CA::Context::commit_transaction(CA::Transaction*) + 276
9  QuartzCore                     0x0000000189313bd8 CA::Transaction::commit() + 528
10 UIKit                          0x0000000189c4dcac _UIWindowUpdateVisibleContextOrder + 240
11 UIKit                          0x0000000189c4daf4 +[UIWindow _prepareWindowsPassingTestForAppResume:] + 32
12 UIKit                          0x0000000189c7934c -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 836
13 UIKit                          0x0000000189c78d90 __88-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]_block_invoke + 140
14 UIKit                          0x0000000189c78ce8 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 380
15 UIKit                          0x0000000189c6bf74 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 552
16 FrontBoardServices             0x000000018d79d3c8 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 32
17 CoreFoundation                 0x0000000184f2027c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
18 CoreFoundation                 0x0000000184f1f384 __CFRunLoopDoBlocks + 312
19 CoreFoundation                 0x0000000184f1d9a8 __CFRunLoopRun + 1756
20 CoreFoundation                 0x0000000184e492d4 CFRunLoopRunSpecific + 396
21 GraphicsServices               0x000000018e89f6fc GSEventRunModal + 168
22 UIKit                          0x0000000189a46f40 UIApplicationMain + 1488
23 Stock                          0x0000000100287690 main (main.m:14)
24 libdyld.dylib                  0x00000001972e6a08 start + 4

**Comment by eskroch** [comment]
The delegate property is set to an invalid address outside your application's memory space. Try logging the delegate to see what it is immediately prior to whatever action triggered the drawing method that crashed. If it's not the object you expected, troubleshoot and find out why.
