### ISSUE TITLE
Custom plot for fill background

### ISSUE THREAD

**Issue by willingheart** [core-plot/core-plot#212]
Hi!
Thank you for this great framework.
I want to use custom function to fill background. I can't use bandLimit, because it is a linear plot.
I try to use simple CPTScatterPlot with property areaFill (color with alpha 0.5), but result is not that I want (see image below: yellow and green fill).

![screenshot](https://cloud.githubusercontent.com/assets/2673726/8909317/6d4392ae-3489-11e5-80a6-66bcb68c74bc.png)

So I have 2 questions:
1. Can I draw some plots behind axis?
2. If no, how can I draw custom function plot for fill background?

**Comment by eskroch** [comment]
You can move the plots behind the axes, but they move as a group. This means you can't split them so some are in from and some are behind the axes.

If the graph won't move in response to user input, you can render the background into an image and use that as the graph fill. If not, you might need to use a second graph behind the first to draw the plot background and use a plot space delegate to keep the plot spaces in sync.

**Comment by willingheart** [comment]
Thanks, Eric!
