### ISSUE TITLE
Simple question about grouped columns

### ISSUE THREAD

**Issue by JanciP** [core-plot/core-plot#213]
Hey, I've read the core-plot documentation but I'm still not sure, whether core-plot is capable of generating grouped barcharts, with variable amount of bars(y-values) for each x-value. Like in this example, there are 3 y-vals for x==0, and 2 y-vals for x==4. 

![example](http://i.imgur.com/3Lwkp1R.png)

**Comment by eskroch** [comment]
Yes, set the `barOffset` to move the bars away from the given `location` and keep the groups together. See the Mac and iPad versions of *CPTTestApp* and the "Composite Plot" demo in the *Plot Gallery* example app.

**Comment by JanciP** [comment]
Thank you very much @eskroch
