### ISSUE TITLE
CPTScatterPlot ignores cornerRadius of CPTPlotArea

### ISSUE THREAD

**Issue by grng** [core-plot/core-plot#214]
I believe [this old bug](https://code.google.com/p/core-plot/issues/detail?id=510) appeared again.

I'm setting `_graph.plotAreaFrame.plotArea.cornerRadius = 5.0;` but it's ignored by my plots:

Please see the bottom red corners:

![core-plot](https://cloud.githubusercontent.com/assets/828466/9027690/7638098e-3935-11e5-84e5-cb9c3e0b319b.png)

	@interface AxisDemoController()
	{
		CPTXYGraph *_graph;
		ChartViewModel *_viewModel;
	}
	@property (nonatomic, readwrite, strong) IBOutlet CPTGraphHostingView *hostView;

	@end

	@implementation AxisDemoController

	- (void)awakeFromNib
	{
		[super awakeFromNib];
		
		_viewModel = [ChartViewModel new];
		
		_graph = [[CPTXYGraph alloc] initWithFrame:NSRectToCGRect(self.hostView.bounds)];
		self.hostView.hostedGraph = _graph;
		
		_graph.fill = nil;
		_graph.paddingBottom = 0;
		_graph.paddingTop = 0;
		_graph.paddingLeft = 0;
		_graph.paddingRight = 0;
		
		_graph.plotAreaFrame.axisSet.borderLineStyle = nil;
		_graph.plotAreaFrame.fill = nil;
		_graph.plotAreaFrame.paddingTop = 20.0;
		_graph.plotAreaFrame.paddingBottom = 50.0;
		_graph.plotAreaFrame.paddingLeft = 50.0;
		_graph.plotAreaFrame.paddingRight = 20.0;
		
		_graph.plotAreaFrame.plotArea.fill = [CPTFill fillWithColor:[CPTColor greenColor]];
		_graph.plotAreaFrame.plotArea.cornerRadius = 5.0;
	//	_graph.plotAreaFrame.plotArea.masksToBorder = YES; // can't because it cuts labels
		
		CPTXYPlotSpace *plotSpace = (CPTXYPlotSpace *)_graph.defaultPlotSpace;
		plotSpace.xRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromDouble(0.0) length:CPTDecimalFromDouble(24.0)];
		plotSpace.yRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromDouble(0.5) length:CPTDecimalFromDouble(100.0)];
		plotSpace.yScaleType = CPTScaleTypeLinear;
		
		CPTXYAxisSet *axisSet = (CPTXYAxisSet *)_graph.axisSet;
		CPTXYAxis *x = axisSet.xAxis;
		x.separateLayers = NO;
		x.orthogonalCoordinateDecimal = CPTDecimalFromDouble(0.5);
		x.majorIntervalLength = CPTDecimalFromDouble(0.5);
		
		x.axisLineStyle = nil;
		x.majorTickLength = 0;
		x.minorTickLength = 0;
		x.labelingPolicy = CPTAxisLabelingPolicyAutomatic;
		
		CPTXYAxis *y = axisSet.yAxis;
		y.separateLayers = NO;
		y.axisLineStyle = nil;
		y.majorTickLength = 0;
		y.minorTickLength = 0;
		y.labelingPolicy = CPTAxisLabelingPolicyNone;
		
		CPTColor *bluePlotColor = [CPTColor colorWithComponentRed:CPTFloat(0.3) green:CPTFloat(0.3) blue:CPTFloat(1.0) alpha:CPTFloat(1.0)];
		[self createPlot:@"Blue" ofColor:bluePlotColor];
		
		CPTColor *redPlotColor = [CPTColor colorWithComponentRed:CPTFloat(1.0) green:CPTFloat(0.3) blue:CPTFloat(0.3) alpha:CPTFloat(1.0)];
		[self createPlot:@"Red" ofColor:redPlotColor];
	}

	- (void)createPlot:(NSString *)plotId ofColor:(CPTColor *)color
	{
		CPTScatterPlot *plot = [[CPTScatterPlot alloc] init];
		plot.identifier = plotId;
		
		CPTMutableLineStyle *lineStyle = [plot.dataLineStyle mutableCopy];
		lineStyle.miterLimit = 1.0;
		lineStyle.lineWidth = 0;
		plot.dataLineStyle = lineStyle;
		
		CPTFill *areaFill = [CPTFill fillWithColor:color];
		plot.areaFill = areaFill;
		plot.areaBaseValue = [[NSDecimalNumber zero] decimalValue];
		
		plot.labelTextStyle = nil;
		plot.dataSource = _viewModel;
		
		[_graph addPlot:plot];
	}

**Comment by eskroch** [comment]
Try setting the corner radius on the plot area frame directly:

    _graph.plotAreaFrame.cornerRadius = 5.0;

**Comment by grng** [comment]
It rounds the corners but it includes the whole frame:

![core-plot-2](https://cloud.githubusercontent.com/assets/828466/9028095/d031fee6-3943-11e5-9fec-c8725101b41e.png)

By the way, I'm using OS X and the deployment target is 10.10.

**Comment by eskroch** [comment]
Plots are `CALayer`s, too. You can also set the `cornerRadius` on each plot.

**Comment by grng** [comment]
Yes, I tried it too but then the layers are producing small visual artifacts when multiple rounded are stacked on each other.

But I think I'll stick to this solution. Thanks!
