### ISSUE TITLE
NuGet and Xamarin Component Store Availability for 1.6?

### ISSUE THREAD

**Issue by neal007** [core-plot/core-plot#217]
Hello - thank you for the outstanding component.  Any idea when the latest (1.6 as of this writing) will be available on NuGet and Xamarin's Component Store?  We're looking for an update for our iOS app preferably via NuGet.

Thank you.

**Comment by eskroch** [comment]
The latest version of Core Plot is available through [CocoaPods](https://cocoapods.org). I intend to make sure the upcoming version 2.0 works well with [Carthage](https://github.com/Carthage/Carthage), too.

There's no problem with hosting Core Plot releases through NuGet, but it's not an officially supported release mechanism. I don't know who posted the previous versions that are available there.
