### ISSUE TITLE
Many warnings on Xcode 7 beta 6

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#220]
I'm trying my project with Xcode 7 beta 6, and I get thousands (!) of warnings similar to:

`file:///Volumes/Stuff/Koen/Development/projects/FrameWorks/core-plot/.hg/store/data/systemtests/google-toolbox-for-mac/_foundation/_g_t_m_base64.m.i: warning: Missing file: /Volumes/Stuff/Koen/Development/projects/FrameWorks/core-plot/.hg/store/data/systemtests/google-toolbox-for-mac/_foundation/_g_t_m_base64.m.i is missing from working copy`

I'm using the Xcode branch of CorePlot.

**Comment by eskroch** [comment]
I don't see any errors in the xcode-7 branch with Xcode 7. That file is part of the old Mercurial repository. Delete the Derived Data folder and do a clean build.

**Comment by koenvanderdrift** [comment]
Turns out, Source Control was turned on in the Xcode preferences. I always have it turned off, so in Xcode, it must be back on by default. All warnings are now gone.
