### ISSUE TITLE
Bar partially filled

### ISSUE THREAD

**Issue by iDevelopper** [core-plot/core-plot#225]
Hello,

How can i partially fill a bar. Is it possible ?

Like this ;

![barsample](https://cloud.githubusercontent.com/assets/1782450/9870230/721f67ee-5b8a-11e5-891b-d5ed0ffd475a.png)

**Comment by eskroch** [comment]
Set `barBasesVary` to `YES`. Then the plot will ask the datasource for the `CPTBarPlotFieldBarBase` field in addition to the `CPTBarPlotFieldBarLocation`and `CPTBarPlotFieldBarTip`.

**Comment by iDevelopper** [comment]
Thank you so much !
