### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by eskroch** [core-plot/core-plot#227]
Add a tvOS framework to Core Plot. Also create a version of the *Plot Gallery* example app that shows off all of the plot types on the Apple TV.

**Comment by charlesaroutiounian** [comment]
Thank You very much! Awesome! Looking forward to use it!

**Comment by eskroch** [comment]
The tvOS framework is on the `release-2.1` branch.

**Comment by SatabdiDas27** [comment]
Hi ,
From where can I download the Coreplot with tvOS support?
Thanks
Sat

**Comment by SatabdiDas27** [comment]
I mean you mentioned its on release 2.1 branch..but I can see only core plot 2.0

**Comment by eskroch** [comment]
2.1 hasn't been released yet. Use git to pull the latest code from that branch or use Cocoapods and point it to the branch instead of a release version.

**Comment by SatabdiDas27** [comment]
When will 2.1 be released??

**Comment by eskroch** [comment]
No specific plans for 2.1, but I think it will be ready soon.
