### ISSUE TITLE
IOS(/Xcode7

### ISSUE THREAD

**Issue by xianrecords2015** [core-plot/core-plot#228]
When should we expect the support for IOS9/Xcode 7 ? 

I have moved my projects to IOS9 but I am stuck with CorePlot 1.6 not working with IOS9

I have also tried to use the xcode7 branch but it gives me all kinds of error.

**Comment by eskroch** [comment]
Release 2.0 should be out soon (hopefully within the next week). In the meantime, you can use the latest code from the master or release-2.0 branches in Xcode 7. Note that release 2.0 has some API changes that will require some minor updates in your code.
