### ISSUE TITLE
Parse Issues with release-2.0 Examples

### ISSUE THREAD

**Issue by jerenmb** [core-plot/core-plot#229]
When trying to run any of the projects in the Examples folder of the release-2.0 branch I get a series of errors, largely made up of: Parse Issue - Expected '>', or Parse Issue - Expected Identifier or '('. I'm using Xcode 6.4. I am seeing these same errors in a project I am working on in which I would like to use Core Plot. In that project I have added Core Plot through CocoaPods pointing to the release-2.0 branch.

**Comment by eskroch** [comment]
Release 2.0 will require Xcode 7. I suspect these errors are from the new Objective-C lightweight generic annotations that first appeared in the Xcode 7 tooling.
