### ISSUE TITLE
Warnings when compiled alongside Swift 2.1

### ISSUE THREAD

**Issue by joshhaug** [core-plot/core-plot#230]
Firstly, let me say that CorePlot has been a pleasure to use.  You guys have done a tremendous job :)
Just updated:
* XCode to ver. 7.0 and 
* My project to Swift 2.1

With this I've noticed a number of initializer-based warnings coming from the library. 
Here's a screenshot of some of the errors:
![image](https://cloud.githubusercontent.com/assets/3131141/10057868/4400324e-61f7-11e5-9563-212cd0da7202.png)

Similar errors are produced in CPTLimitBand, CPTNumericData, CPTPathExtensions, CPTPlotSpaceAnnotation, and CPTTimeFormatter.  

Let me know if I can provide any more useful information, as these errors seem to be causing strange behavior in my project's graphs.

**Comment by eskroch** [comment]
What version of Core Plot are using? The latest code on the master and release-2.0 branches works fine for me in Xcode 7.

**Comment by thomasaw** [comment]
I'm seeing these warnings when using CorePlot via CocoaPods and without Swift 2.1. I believe this is because the latest version when just using `pod 'CorePlot'` is 1.6.

**Comment by eskroch** [comment]
Release 2.0 will fix this. I want to do some testing on El Capitan and hopefully have it out within a week.
