### ISSUE TITLE
Drop iOS 6 and lower?

### ISSUE THREAD

**Issue by jessesquires** [core-plot/core-plot#234]
Given the [current stats](https://developer.apple.com/support/app-store/) on iOS usage (iOS 8 at `41%` and iOS 9 at `52%`), should we consider dropping support for iOS 6 and lower? 

For apps, Apple recommends only supporting the 2 most recent OS versions.

Supporting only iOS 7 and above would definitely make maintenance and feature development easier.

Thoughts?

**Comment by mike-lischke** [comment]
+1 makes sense

**Comment by jessesquires** [comment]
:smile:

I would actually support being iOS 8+, but maybe that's too aggressive.

**Comment by iDevelopper** [comment]
I don't think so ! iOS 7 is an old version now...

**Comment by mbrennek** [comment]
My 2c, I just dropped iOS 5 & 6 support a couple months ago with the latest version of my apps that use CorePlot. They were combined about 2% of my user base. Still close have to 10% of my users on iOS 7, so I won't be able to drop support for them for a while yet.

**Comment by eskroch** [comment]
My intention for release 2.0 is to keep iOS support for the iOS static library with a deployment target of iOS 6. This release will also include an iOS framework, which requires iOS 8. Both versions will have identical functionality, but we'll need both for a while to keep support for pre-iOS 8 deployment targets. Moving into the future, we can raise the deployment target as needed if we implement features that require OS infrastructure from later versions.

**Comment by jessesquires** [comment]
Thanks @eskroch ! Do you have a release date goal for 2.0?

**Comment by eskroch** [comment]
I'm trying to get it out this weekend. I have documentation and release notes to write and some testing left to do.

**Comment by eskroch** [comment]
[Release 2.0](https://github.com/core-plot/core-plot/releases/tag/release_2.0) is out now. The deployment targets are set as discussed above.

**Comment by jessesquires** [comment]
Nice work @eskroch ! :tada: Thanks!
