### ISSUE TITLE
Getting a bunch of warnings with 2.0 release - "... was built for newer iOS version (9.0) than being linked (8.0)"

### ISSUE THREAD

**Issue by JaxMyers** [core-plot/core-plot#235]
I am getting a bunch of warnings like this below:
ld: warning: object file (./libCorePlot-CocoaTouch.a(CPTXYPlotSpace.o)) was built for newer iOS version (9.0) than being linked (8.0)

Anybody know how to fix or silence them?

**Comment by eskroch** [comment]
What is the "Base SDK" setting in your app project? Core Plot was built with a Base SDK of iOS 9.0.

**Comment by JaxMyers** [comment]
My Base SDK is Latest iOS (iOS 9.0) using Xcode 7.

**Comment by eskroch** [comment]
Have you tried a clean build and/or clearing out Xcode's Derived Data folder?

**Comment by JaxMyers** [comment]
I tried cleaning but didn't try deleting the derived data folder. Will try that later tonight. 

Jackson

**Comment by JaxMyers** [comment]
Cleaning via Xcode (Product -> Clean) didn't work, nor did deleting ~/Libarary/Developer/Xcode/Derived Data.

If I change my deployment target to 9.0 it works but wouldn't that prevent iOS 8 users from downloading? Is that required for Core-plot 2.0?

**Comment by eskroch** [comment]
The deployment target for the release 2.0 static library is iOS 6.0. Are you building Core Plot from source or using the precompiled library in the release package?

**Comment by JaxMyers** [comment]
I'm not building from source, I'm using the precompiled library.

I found the same issue with a different project here.
https://github.com/google/gcm/issues/104#issuecomment-145622399

**Comment by eskroch** [comment]
I followed the linked discussion and did some other research. It all points to setting the deployment target explicitly, which Core Plot already does. It is set to 6.0 for both debug and release builds.

**Comment by eskroch** [comment]
I fixed the deployment target for the pre-built iOS static library and framework and uploaded revision 1 of [release 2.0](https://github.com/core-plot/core-plot/releases/tag/release_2.0) to the release page.
