### ISSUE TITLE
Unknown command tag name documentation errors Xcode 7

### ISSUE THREAD

**Issue by jaxelanderson** [core-plot/core-plot#238]
Hi all,
I have a project that I recently revisited after a 9 month hiatus. After updating Xcode to 7 to test it for iOS9 compatibility, I am getting several unknown command tag names. It appears that xcode does not like @'s in comments. I dont see much on the interweb about it, though I can't see how I am the only one.  I took the latest code from master and had the same issue. 
![screen shot 2015-10-21 at 2 35 34 pm](https://cloud.githubusercontent.com/assets/3373375/10646423/03a059f2-7801-11e5-9868-c725531f17c2.png)

**Comment by eskroch** [comment]
Please update to release 2.0. It fixes the Xcode 7 compatibility issues.
