### ISSUE TITLE
Warnings: libCorePlot-CocoaTouch.a(...)was built for newer iOS version (9.0) than being linked (7.0)

### ISSUE THREAD

**Issue by brabbeldas** [core-plot/core-plot#240]
Today I have downloaded v2.0 of CorePlot. After adding it as a static library to my project I now get these warnings:
"libCorePlot-CocoaTouch.a(CPTPlatformSpecificFunctions.o)) was built for newer iOS version (9.0) than being linked (7.0)"

I know that there is a similar issue here: https://github.com/core-plot/core-plot/issues/235 which is already closed, but that does not give a solution.
Could somebody please share the solution for this issue? Thanks in advance, Bas

**Comment by eskroch** [comment]
Core Plot 2.0 enabled bitcode in the iOS builds. Does your app support bitcode, too?

**Comment by brabbeldas** [comment]
Bitcode seems to be enabled by default, that's what triggered me to upgrade from CorePlot v1.5 to v2.0

**Comment by eskroch** [comment]
I fixed the deployment target for the pre-built iOS static library and framework and uploaded revision 1 of [release 2.0](https://github.com/core-plot/core-plot/releases/tag/release_2.0) to the release page.

**Comment by brabbeldas** [comment]
Thanks eskroch! The release page still says "released this on Oct 4", if i download CorePlot_2.0.zip, will that be revision 1?

**Comment by eskroch** [comment]
Download CorePlot_2.0r1.zip to get the updated version.
