### ISSUE TITLE
Core Plot symbol

### ISSUE THREAD

**Issue by iDevelopper** [core-plot/core-plot#241]
Are there any way to do this with Core Plot or so is it a custom development? When I touch the view, I would like to display that vertical line and the legend at the top of this line.

Thanks for help.

![2015-11-04_13-10-22](https://cloud.githubusercontent.com/assets/1782450/10938540/62931cba-82fb-11e5-888c-2fb81aa5a47f.png)

**Comment by eskroch** [comment]
Add this to one of the example apps as a demo.

See [this discussion](https://groups.google.com/forum/#!topic/coreplot-discuss/8U_WoKAq1-0) for details and sample code.

**Comment by iDevelopper** [comment]
Well, it is a recurring issue

**Comment by pprraasshhaanntthh** [comment]
does the example added ?

**Comment by iDevelopper** [comment]
I don't think so but I have posted it here : [this discussion](https://groups.google.com/d/msg/coreplot-discuss/8U_WoKAq1-0/DSgOTZ1lAwAJ)

**Comment by eskroch** [comment]
I added a live indicator line to the "Date Plot" in the Plot Gallery app on the `release_2.1` branch.

**Comment by pprraasshhaanntthh** [comment]
I have downloaded but I couldn't see it ... If this available for iPad plot gallery

**Comment by iDevelopper** [comment]
@pprraasshhaanntthh : In Plot Gallery iOS. You have to download release 2.1 branch, not master branch

**Comment by iDevelopper** [comment]
@eskroch : Thanks again!

Suggestion:

After 
```
        iAxis.orthogonalPosition = xNumber;
        iAxis.hidden             = NO;
```
Test if the annotation is partially outside the plot area so set a displacement on it in this case
```
        CGPoint iAxisPoint = [iAxis viewPointForCoordinateValue:xNumber];
        CGRect areaFrame = graph.plotAreaFrame.plotArea.frame;
        
        CGFloat maxDisplacement = textLayer.frame.size.width / 2;
        CGFloat maxX = areaFrame.origin.x + areaFrame.size.width;
        
        if (iAxisPoint.x + maxDisplacement >= maxX) {
            annotation.displacement = CGPointMake(-(iAxisPoint.x + maxDisplacement - maxX), 0.);
        }
        else {
            if (iAxisPoint.x - maxDisplacement < areaFrame.origin.x) {
                annotation.displacement = CGPointMake((maxDisplacement - (iAxisPoint.x - areaFrame.origin.x)), 0.);
            }
            else {
                annotation.displacement = CGPointMake(0.,0.);
            }
        }
```

**Comment by pprraasshhaanntthh** [comment]
Thanks for the update.
