### ISSUE TITLE
Implement vertical line track indicator 

### ISSUE THREAD

**Issue by pprraasshhaanntthh** [core-plot/core-plot#244]
![bdy5t](https://cloud.githubusercontent.com/assets/4393799/11024397/bcda58d0-86b3-11e5-80ab-eccc103dbd35.jpg)

How can I implement the above ? I couldn't find anything like in the examples

**Comment by eskroch** [comment]
We've been discussing an issue like this on the [discussion board](https://groups.google.com/forum/#!topic/coreplot-discuss/8U_WoKAq1-0) recently. That thread includes a sample project that has code that should get you started.

**Comment by eskroch** [comment]
Duplicate of issue #241.
