### ISSUE TITLE
AppStore issue: invalid architecture i368, x86_64

### ISSUE THREAD

**Issue by ennioma** [core-plot/core-plot#245]
Hi,
I've added the CorePlot.framework to my project and it works on simulator and if I run the app on my devices. 

The issue is raised when I try to submit the project to the AppStore. Should I re-build the framework just for armv7, armv7s and arm64 using the Universal iOS Framework target? How could I remove i386 and x86_64 architectures from the generated framework?

Thanks!

**Comment by eskroch** [comment]
The "Universal iOS Framework" target builds the universal framework that includes the simulator architectures (i368, x86_64) that are giving you trouble. Run a release build of the "CorePlot iOS" target to create a framework that only includes the ARM architectures.

**Comment by eskroch** [comment]
This appears to be a problem with Apple's toolchain not stripping the simulator architectures from the framework when submitting the app to the store. The [Carthage project](https://github.com/Carthage/Carthage) has some suggested solutions [here](https://github.com/Carthage/Carthage/issues/188).
