### ISSUE TITLE
App crash while calling -(void)setAreaBaseValue:(NSNumber *)newAreaBaseValue

### ISSUE THREAD

**Issue by jayesh15111988** [core-plot/core-plot#246]
Every time I try to plot values on graph, app crashes while calling 
`-(void)setAreaBaseValue:(NSNumber *)newAreaBaseValue` defaulting on exception EXC_BAD_ACCESS. Anyone observed this issue earlier?

**Comment by eskroch** [comment]
Where is the app crashing? Can you post the stack trace?

**Comment by jayesh15111988** [comment]
I am using following line of code to instantiate core plot graph

`CPTScatterPlot *workoutPlot = [[CPTScatterPlot alloc] init];
  [workoutPlot setAreaBaseValue:CPTDecimalFromInteger(<yMinBound>)];`

And it crashes right at `-(void)setAreaBaseValue:(NSNumber *)newAreaBaseValue`

Attaching screenshot for better clarity on this issue,

<img width="558" alt="screen shot 2015-11-20 at 2 59 47 pm" src="https://cloud.githubusercontent.com/assets/6687735/11310405/5ee0d762-8f97-11e5-9a70-33b223966b98.png">

There is no stack trace around. Looks like object is prematurely deallocated while calling this method.

**Comment by eskroch** [comment]
Look at the method signature. This is one of the properties that changed from `NSDecimal` to `NSNumber` in 2.0. Try this:

    workoutPlot.areaBaseValue = @(yMinBound);

**Comment by jayesh15111988** [comment]
@eskroch Thanks for the prompt reply. I am on it and will get back to you ASAP.

**Comment by jayesh15111988** [comment]
@eskroch I got it fixed. For some reason we did not update bunch of code to use version 2.0. But it's all good now. Thanks for quick turnaround.
