### ISSUE TITLE
How to change the Legend titles in core-plot stacked bar chart?

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [core-plot/core-plot#247]
i want to change the Legend title values for my stacked bar chart , by default it takes the "sets" values given in the code. I can't change the "sets" value because i used it to match and get values from the web service.
i tried this code 
-(NSString *)legendTitleForBarPlot:(CPTBarPlot *)barPlot recordIndex:(NSUInteger)index

{
    return [NSString stringWithFormat:@"Bar %lu", (unsigned long)(index + 1)];
}
but it takes the index value for all stacked-bars in the graph.
How to change the the Legend title values for stacked bar chart?

**Comment by eskroch** [comment]
Set the `title` property of each plot to change the label displayed in the legend. You can use the `attributedTitle` instead if you want to display styled text within the label.

Also answered on [StackOverflow](http://stackoverflow.com/questions/33889344).

**Comment by karthikeyanchenniappan** [comment]
- (double)doubleForPlot:(CPTPlot *)plot field:(NSUInteger)fieldEnum recordIndex:(NSUInteger)index
 {
 NSInteger plotIndex = 0;
 if ([plot.identifier isEqual:[sets objectForKey:@"D"]] == YES) 
{
 plotIndex = 0; 
} 
else if ([plot.identifier isEqual:[sets objectForKey:@"O"]] == YES) 
{ 
plotIndex = 1; 
} 
else if ([plot.identifier isEqual:[sets objectForKey:@"P"]] == YES) 
{ 
plotIndex = 2; 
}
if (plotIndex ==0)
{
plot.title=@"A";
}
else if (plotIndex ==1)
{
plot.title=@"AA";
}
else if (plotIndex ==2)
{ 
plot.title=@"AAA";
} 
}
 Displays "A" for all 3 legend Values, where i can add plot title please suggest?
