### ISSUE TITLE
How to add plot title for stacked bar chat?

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [core-plot/core-plot#248]
Where  to add title for each plot in stacked bar chat i tried on the below methods
 -(NSString *)legendTitleForBarPlot:(CPTBarPlot *)barPlot recordIndex:(NSUInteger)index

 { if ([barPlot.identifier isEqual:[sets objectForKey:@"D"]] == YES) { barPlot.title=@"A"; } else if ([barPlot.identifier isEqual:[sets objectForKey:@"O"]] == YES) { barPlot.title=@"AA"; } else if ([barPlot.identifier isEqual:[sets objectForKey:@"P"]] == YES) { barPlot.title=@"AAA"; } return barPlot.title; 
} 
  	 	
I tired like this to inside the method -(void)barPlot:(CPTBarPlot *)plot barWasSelectedAtRecordIndex:(NSUInteger)index
 if (plotIndex ==0)
 { plot.title=@"A"; }else if (plotIndex ==1) { plot.title=@"AA"; }else if (plotIndex ==2) { plot.title=@"AAA"; }
- (double)doubleForPlot:(CPTPlot *)plot field:(NSUInteger)fieldEnum recordIndex:(NSUInteger)index 
{
 NSInteger plotIndex = 0; if ([plot.identifier isEqual:[sets objectForKey:@"D"]] == YES) { plotIndex = 0; } else if ([plot.identifier isEqual:[sets objectForKey:@"O"]] == YES) { plotIndex = 1; } else if ([plot.identifier isEqual:[sets objectForKey:@"P"]] == YES) { plotIndex = 2; }if (plotIndex ==0){plot.title=@"A";}else if (plotIndex ==1){plot.title=@"AA";}else if (plotIndex ==2){ plot.title=@"AAA";} 

} 

- (void)generateLayout
{

 plot.identifier         = set;
     
        if ([plot.identifier isEqual:[sets objectForKey:@"D"]] == YES) {
            plot.title=@"A";
        } else if ([plot.identifier isEqual:[sets objectForKey:@"O"]] == YES)
                    {
                    plot.title=@"AA";
                    }
        else if ([plot.identifier isEqual:[sets objectForKey:@"P"]] == YES)
        {
            plot.title=@"AAA";
        }
        [graph addPlot:plot toPlotSpace:plotSpace];
    }

Where to add title for each plot to replace the Legend values displayed on the screen?

**Comment by eskroch** [comment]
Set the `title` on the plot during the initial setup. Any time before you add the plot to the legend will work.
