### ISSUE TITLE
Draw gaps for line chart

### ISSUE THREAD

**Issue by mancunianetz** [core-plot/core-plot#249]
The goal is to draw a dashed bar instead of gaps like in below screenshot.

![device-2014-08-01-001629](https://cloud.githubusercontent.com/assets/2619031/11422487/06b4fe30-9445-11e5-8895-5d77a404d502.png)

**Comment by eskroch** [comment]
You could use a bar plot or another scatter plot to draw the shaded box.

**Comment by mancunianetz** [comment]
@eskroch forgot to mention that gaps are drawn using scatter plot. 
As far as i know, the plot area can be filled using a gradient, a color or an image. Should I generate an image ? Or I can do the drawing on plot's layer directly? But i'm afraid it will have a bad impact on other plot features

**Comment by eskroch** [comment]
To get the pattern with diagonal stripes, you'll need to use an image fill. Set `tiled` to `YES` on the image used to create the fill to draw the repeating pattern throughout the box. The easiest way to draw the box would be with a scatter plot separate from the data plot. You only need two data points to draw a rectangle—the upper left and upper right corners. Set the `areaFill` to the image fill discussed above.

**Comment by mancunianetz** [comment]
Yes, I'm using 2 scatter plots, one for showing data, another for showing gaps.

Thanks for the hints, I've been able to implement this.
