### ISSUE TITLE
Tracker line issue in Date Plot 

### ISSUE THREAD

**Issue by chandramohan11** [core-plot/core-plot#251]
Hi 
I am working on date plot graph . But i am  not able to plot blue vertical line with annotation. Annotation is working fine but blue line is not coming with annotation. Could you please suggest something.
Your suggestion must be appreciated.

Regards
ChandraMohan
![screen shot 2015-12-15 at 7 29 42 pm](https://cloud.githubusercontent.com/assets/16095614/11812993/f550297e-a364-11e5-8f66-4e20a6cf00be.png)
[IQPricingChartView.swift.zip](https://github.com/core-plot/core-plot/files/62579/IQPricingChartView.swift.zip)

**Comment by eskroch** [comment]
Where do you want to draw the line? What is it for? It's often easier to use an extra axis line or plot to draw vertical or horizontal marker lines.

**Comment by chandramohan11** [comment]
Thanks for reply. We wanted to draw a tracker vertical line with annotation. Which we can move in graph to track the data points. See the attached screen(Line with red colour and annotation).
![screen shot 2015-12-16 at 11 25 51 am](https://cloud.githubusercontent.com/assets/16095614/11833416/68fa5934-a3e8-11e5-8661-037081be437f.png)

**Comment by iDevelopper** [comment]
Look the date plot sample

**Comment by chandramohan11** [comment]
Yes I am following the date plot only. Even i am getting the orthogonal position of iAxes annotation. But red marker line not getting display . here is my code.



import UIKit

class PricingChartView: UIView , CPTBarPlotDelegate ,CPTBarPlotDataSource, CPTAxisDelegate,CPTPlotSpaceDelegate,CPTScatterPlotDelegate,CPTScatterPlotDataSource
{
    
    var subjectCompanyId:NSNumber!
    private var hostingView:CPTGraphHostingView!
    private var graph:CPTGraph!
    private var listhistory:[IQQCTradeData]!
    private var yaxismaxvalue:Double?
    private var yaxisminvalue:Double?
    private var dictcontent:[String:[String:NSNumber]]!
    private var startdate:NSDate?// plot starts
    private var enddate:NSDate?// plot ends
    private var timeframe:IQOverviewPricingChartSegmentsIds?
    private let spacecount = 2
    private var markerAnnotation:CPTPlotSpaceAnnotation?

    
    let oneDay:NSTimeInterval  = 24 * 60 * 60
    
    override func awakeFromNib() {
        
        hostingView  = CPTGraphHostingView(frame: self.bounds)
        self.addSubview(hostingView)
        
        
        
        graph = CPTXYGraph(frame: self.bounds)
        hostingView.hostedGraph = graph
        
        let theme = CPTTheme(named: kCPTPlainWhiteTheme)
         graph.applyTheme(theme)
        
        if let plotAreaFrame = graph.plotAreaFrame{
            plotAreaFrame.paddingLeft   = 40
            plotAreaFrame.paddingTop    = 0
            plotAreaFrame.paddingRight  = 0
            plotAreaFrame.paddingBottom = 50
            plotAreaFrame.borderLineStyle  = nil
            plotAreaFrame.masksToBorder = false
        }
        hostingView.userInteractionEnabled = true
    }
    
    // remove previously added plots
    private func removeCurrentPlots(){
        let allplots =  graph.allPlots()
        for plot in allplots{
            graph.removePlot(plot)
            graph.removeAllAnnotations()
        }
        self.yaxismaxvalue = 0
        self.yaxisminvalue = 0
        self.startdate = nil
        self.enddate = nil
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        hostingView.frame = self.bounds
    }
    
    // fill the plot meta details to plot the graph
    private func fillPlotMetaDetails(){
        
        self.removeCurrentPlots()
        // looping to get the meta details
        
        
        
        for trade in listhistory{
            
            // to find the plot space range
            print(trade.datestring, trade.value)
            if let begintime = self.startdate, let tradedate = trade.date where begintime.compare(tradedate)==NSComparisonResult.OrderedDescending{
                self.startdate = tradedate
            }else if let tradedate = trade.date where self.startdate==nil{
                self.startdate = tradedate
            }
            
            if let endtime = self.enddate, let tradedate = trade.date where endtime.compare(tradedate)==NSComparisonResult.OrderedAscending {
                self.enddate = tradedate
            }else if let tradedate = trade.date where self.enddate==nil{
                self.enddate = tradedate
            }
            
            if let cvalue = trade.value where cvalue.doubleValue > 0.0 {
                let cv = cvalue.doubleValue
                
                if let ymax = self.yaxismaxvalue, let ymin = self.yaxisminvalue {
                    self.yaxismaxvalue = ymax>cv ? ymax:cv// max value
                    self.yaxisminvalue = ymin<cv ? ymin:cv// min value
                }
                else{
                    self.yaxismaxvalue = cv// max value
                    self.yaxisminvalue = cv// min value
                }
            }
            
        }
        
        self.yaxisminvalue = self.yaxisminvalue! - ((self.yaxisminvalue!*5)/100)
        self.yaxismaxvalue = self.yaxismaxvalue! + ((self.yaxismaxvalue!*5)/100)
        
        
        // non display plot
        let lineStyle = CPTMutableLineStyle()
        lineStyle.lineWidth = 1.5
        lineStyle.lineColor = CPTColor(componentRed: 29.0/255.0, green: 187.0/255.0, blue: 225.0/255.0, alpha: 1.0)
        
        
        let subjectPlot = CPTScatterPlot()
        subjectPlot.dataLineStyle = lineStyle
        subjectPlot.dataSource = self
        
        subjectPlot.opacity = 0.0
        let fadeInAnimation = CABasicAnimation(keyPath: "opacity")
        fadeInAnimation.duration            = 1.0
        fadeInAnimation.removedOnCompletion = false
        fadeInAnimation.fillMode            = kCAFillModeForwards
        fadeInAnimation.toValue             = 1.0
        subjectPlot.addAnimation(fadeInAnimation, forKey: "animateOpacity")
        //subjectPlot.interpolation = CPTScatterPlotInterpolation.Linear
        
        let areaGradient:CPTGradient = CPTGradient(beginningColor: CPTColor.whiteColor(), endingColor: CPTColor(componentRed: 29.0/255.0, green: 187.0/255.0, blue: 225.0/255.0, alpha: 0.6))
        areaGradient.angle = 90.0
        let areaGradientFill:CPTFill = CPTFill(gradient: areaGradient)
        subjectPlot.areaBaseValue = self.yaxisminvalue
        subjectPlot.areaFill = areaGradientFill
        
        
        
        graph.addPlot(subjectPlot)

        
    }
    

    func populateData(data: [IQQCTradeData]!) {
        
        listhistory = data
        self.fillPlotMetaDetails()
        
         let plotSpace:CPTXYPlotSpace = (graph.defaultPlotSpace as? CPTXYPlotSpace)!
            plotSpace.delegate = self
            plotSpace.allowsUserInteraction = true

        
            if let begintime = self.startdate, let endtime = self.enddate{
                plotSpace.xRange = CPTPlotRange(location: NSNumber(double: 0), length:NSNumber(double: endtime.timeIntervalSinceDate(begintime)))
                
              // NSNumber(double:oneDay) * NSNumber(double: Double(listhistory.count)-1.0)
                
                //plotSpace.xRange = CPTPlotRange(location: NSNumber(double: 0), length:NSNumber(double: oneDay * NSNumber(double: listhistory.count - 1)))
            }
            
            if let ymax = self.yaxismaxvalue, let ymin = self.yaxisminvalue {
                plotSpace.yRange = CPTPlotRange(location:NSNumber(double: ymin), length:NSNumber(double: ymax-ymin))
            }
        
        if let axisSet:CPTXYAxisSet = (graph.axisSet as? CPTXYAxisSet), let xAxis:CPTXYAxis = axisSet.xAxis, let yAxis:CPTXYAxis = axisSet.yAxis{
            // Create grid line styles
            let majorGridLineStyle:CPTMutableLineStyle  = CPTMutableLineStyle()
            majorGridLineStyle.lineWidth = 0.75
            majorGridLineStyle.lineColor = CPTColor(genericGray: 0.2).colorWithAlphaComponent(0.75)
            majorGridLineStyle.lineFill = CPTFill(gradient: CPTGradient().fadeinfadeoutGradient())
            
            let minorGridLineStyle:CPTMutableLineStyle = CPTMutableLineStyle()
            minorGridLineStyle.lineWidth = 0.25
            minorGridLineStyle.lineColor = CPTColor.whiteColor().colorWithAlphaComponent(0.1)
            
            let labelstyle:CPTMutableTextStyle = CPTMutableTextStyle()
            labelstyle.fontSize = 12
            labelstyle.fontName = "Arial-BoldMT"
            labelstyle.color = CPTColor(CGColor: UIColor.darkGrayColor().CGColor)
            

            
            
            
            xAxis.delegate = self
            xAxis.labelingPolicy = CPTAxisLabelingPolicy.EqualDivisions
            xAxis.majorIntervalLength = NSNumber(double: oneDay)
            //xAxis.majorGridLineStyle = majorGridLineStyle
            //xAxis.minorGridLineStyle = minorGridLineStyle
            xAxis.orthogonalPosition = NSNumber(float: 2)
            xAxis.minorTicksPerInterval = 0
            xAxis.axisLineStyle = nil
            xAxis.majorTickLineStyle = nil
            xAxis.minorTickLineStyle = nil
            xAxis.labelRotation = CGFloat(M_PI_2/4)
            xAxis.labelTextStyle = labelstyle
            xAxis.axisConstraints = CPTConstraints.constraintWithLowerOffset(0.0)

            let dateformatter = NSDateFormatter()
            dateformatter.dateFormat = "MMM-dd-yyyy"
            let timeFormatter = CPTTimeFormatter(dateFormatter: dateformatter)
            timeFormatter.referenceDate = startdate
            xAxis.labelFormatter = timeFormatter
            xAxis.preferredNumberOfMajorTicks = 6
            
            let formatter = NSNumberFormatter()
            formatter.positiveFormat = "0.00"
            //formatter.negativeFormat = "-0.00"
            
            yAxis.labelingPolicy = CPTAxisLabelingPolicy.EqualDivisions
            yAxis.majorGridLineStyle = majorGridLineStyle
            yAxis.minorGridLineStyle = minorGridLineStyle
            yAxis.labelFormatter     = formatter
            yAxis.minorTicksPerInterval = 1//sub scale
            yAxis.preferredNumberOfMajorTicks = 10
            yAxis.majorTickLength = 1
            //yAxis.axisLineStyle = nil
            yAxis.majorTickLineStyle = nil
            yAxis.minorTickLineStyle = nil
            yAxis.orthogonalPosition = NSNumber(float: 2)
            yAxis.axisConstraints = CPTConstraints.constraintWithLowerOffset(0)
            yAxis.labelTextStyle = labelstyle
            yAxis.labelAlignment = CPTAlignment.Right
            //yAxis.coordinate = CPTCoordinate.
           
            yAxis.majorIntervalLength   = 0.5
            yAxis.minorTicksPerInterval = 5
            yAxis.orthogonalPosition    = oneDay
            
            let blueLineStyle:CPTMutableLineStyle = CPTMutableLineStyle()
            blueLineStyle.lineColor =  CPTColor(componentRed: 46.0/255.0, green: 123.0/255.0, blue: 224.0/255.0, alpha: 0.7)
            blueLineStyle.lineWidth = 2.0;
            
            let iAxis:CPTXYAxis = CPTXYAxis(frame: CGRectZero)
            iAxis.title          = nil
            iAxis.labelFormatter = nil
            iAxis.axisLineStyle  = blueLineStyle;
            
            iAxis.coordinate         = CPTCoordinate.Y
            iAxis.plotSpace          = graph.defaultPlotSpace
            iAxis.majorTickLineStyle = nil
            iAxis.minorTickLineStyle = nil
            iAxis.orthogonalPosition = 0.0
            iAxis.hidden             = true
            
            graph.axisSet?.axes = [xAxis,yAxis,iAxis]

            
            // Setup a style for the annotation
            let hitAnnotationTextStyle:CPTMutableTextStyle = CPTMutableTextStyle()
            hitAnnotationTextStyle.color    = CPTColor.blackColor()
            hitAnnotationTextStyle.fontName = "Helvetica-Bold";
            
            
            
            
            let imageLayer:CPTBorderedLayer = CPTBorderedLayer(frame: CGRectMake(100,-100,20,100))
            imageLayer.fill = CPTFill(image: CPTImage(named: "briefing_side_bar_vert_bdg_1_ipad.png"))
            
            
            let textLayer:CPTTextLayer = CPTTextLayer(text: "", style: hitAnnotationTextStyle)
            textLayer.borderLineStyle = blueLineStyle
            textLayer.fill            = CPTFill(color: CPTColor.whiteColor())
            textLayer.cornerRadius    = 3.0
            textLayer.paddingLeft     = 2.0
            textLayer.paddingTop      = 2.0
            textLayer.paddingRight    = 2.0
            textLayer.paddingBottom   = 2.0
            textLayer.hidden          = false
            //textLayer.addSublayer(imageLayer)
            
            let annotation:CPTPlotSpaceAnnotation = CPTPlotSpaceAnnotation(plotSpace: plotSpace, anchorPlotPoint: [0,0])
           
            annotation.contentLayer = textLayer
            
            annotation.displacement = CGPointMake(0.0, 10.0)
            //graph.addAnnotation(annotation)
            graph.plotAreaFrame?.plotArea?.addAnnotation(annotation)
            
            self.markerAnnotation = annotation

           
            
        }
    }

    // core plot delegate methods
    func numberOfRecordsForPlot(plot: CPTPlot) -> UInt {
        
        if let trades = listhistory{
            return UInt(trades.count)
        }
        
        
        return 0
    }
    func numberForPlot(plot: CPTPlot, field fieldEnum: UInt, recordIndex idx: UInt) -> AnyObject? {
        
        let indexrow = Int(idx)
    
         if (plot.isKindOfClass(CPTScatterPlot)) {
            if fieldEnum == UInt (CPTScatterPlotField.X.rawValue) {
                if  let acobj:IQQCTradeData = listhistory[indexrow]{
                    let timeinterval = acobj.date?.timeIntervalSinceDate(startdate!)
                    return NSNumber(double:timeinterval!)
                }
                
                return NSNumber(unsignedLong:idx)
            }
            else if fieldEnum == UInt (CPTScatterPlotField.Y.rawValue) {
                
                if let acobj:IQQCTradeData = listhistory[indexrow]{
                    return acobj.value
                }else {
                    return NSDecimalNumber.zero()
                }
            }
            
        }
 
        
        return nil
    }
    
    func plotSpace(space: CPTPlotSpace, shouldHandlePointingDeviceDownEvent event: UIEvent, atPoint point: CGPoint) -> Bool {
        
        let xySpace:CPTXYPlotSpace = space as! CPTXYPlotSpace
        let graph:CPTGraph = space.graph!
        let axisSet:CPTXYAxisSet = graph.axisSet as! CPTXYAxisSet;
        let axes:CPTAxisArray = axisSet.axes!
        let iAxis:CPTXYAxis   = axes.lastObject as! CPTXYAxis
        
        let plotPoint:CPTNumberArray = space.plotPointForEvent(event)!
        let annotation:CPTPlotSpaceAnnotation = self.markerAnnotation!;
        let textLayer:CPTTextLayer = annotation.contentLayer as! CPTTextLayer;
        textLayer.hidden = false;
        var xNumber:NSNumber? = plotPoint[CPTCoordinate.X.rawValue] as? NSNumber
        
        if xySpace.xRange.containsNumber(xNumber) {
            let x:UInt = UInt(lround(xNumber!.doubleValue / oneDay))
            print(x)
            let myTimeInterval = NSTimeInterval(oneDay)
            let myDouble = NSNumber(double: myTimeInterval)
            xNumber = NSNumber(double: NSNumber(unsignedLong: x).doubleValue * myDouble.doubleValue)
            let labelString   = axisSet.xAxis?.labelFormatter?.stringForObjectValue(xNumber!)
            //var isDateRange:Bool = false
           
            for trade in listhistory {
                
                let priceValue = NSString(format: "%@", trade.value!)
                let volume = NSString(format: "%@", trade.volumn!)
                if trade.datestring == labelString {
                    textLayer.text = NSString(format: "  %@  \n  %@  \n  %@mm  ",labelString!,SuffixNumber(priceValue as String, 2),SuffixNumber(volume as String, 2)) as String
                    //isDateRange = true
                }
            }
//            if !isDateRange {
//                textLayer.text = ""
//                textLayer.hidden = true
//                iAxis.hidden     = true
//            }
            annotation.anchorPlotPoint = [xNumber!, xySpace.yRange.maxLimit];
            iAxis.orthogonalPosition = xNumber
            textLayer.hidden = false;

        }
        else {
            textLayer.text = ""
            textLayer.hidden = true
            iAxis.hidden     = true
        }
        
        return false

    }
  func plotSpace(space: CPTPlotSpace, shouldHandlePointingDeviceDraggedEvent event: UIEvent, atPoint point: CGPoint) -> Bool {
        return self.plotSpace(space, shouldHandlePointingDeviceDownEvent: event, atPoint: point)
    }
    
    func plotSpace(space: CPTPlotSpace, willDisplaceBy proposedDisplacementVector: CGPoint) -> CGPoint {
      return   CGPointMake(0.0, 0.0);
    }
    
    func plotSpace(space: CPTPlotSpace, shouldHandlePointingDeviceUpEvent event: UIEvent, atPoint point: CGPoint) -> Bool {
        return false
    }

    
    deinit {
        // perform the deinitialization
        hostingView.hostedGraph = nil
        hostingView = nil
    }
    
    
}

**Comment by eskroch** [comment]
I don't see any obvious problems. Have you looked at the shouldHandlePointingDeviceDownEvent method in the debugger to make sure all of the calculations come up with the values you expect?

I do see one area that is correct, but could be simplified to make it easier to follow. You can replace the following three lines:

```
let myTimeInterval = NSTimeInterval(oneDay)
let myDouble = NSNumber(double: myTimeInterval)
xNumber = NSNumber(double: NSNumber(unsignedLong: x).doubleValue * myDouble.doubleValue)
```

with

```
xNumber = NSNumber(double: Double(x) * oneDay)
