### ISSUE TITLE
Update axisLabels

### ISSUE THREAD

**Issue by mancunianetz** [core-plot/core-plot#252]
```CPTXYAxis``` instance has``` labelingPolicy``` property set to ```CPTAxisLabelingPolicyNone```. ```majorTickLocations``` and ```axisLabels``` are set. Later I need to update title's of some ```axisLabels```. How can I achieve that ?

In the ```- (void)plotSpace:(CPTPlotSpace *)space didChangePlotRangeForCoordinate:(CPTCoordinate)coordinate``` I'm doing the following:

    NSMutableArray *labels = [[((CPTXYAxisSet *)mGraph.axisSet).xAxis.axisLabels allObjects] mutableCopy];
    if ([labels count] > 0) {
        CPTMutableTextStyle *style = [[CPTMutableTextStyle alloc] init];
        style.textAlignment = CPTTextAlignmentCenter;
        style.fontName = @"HelveticaNeue";
        style.fontSize = 13.0f;
        style.color = [CPTColor whiteColor];
        CPTAxisLabel *label = [[CPTAxisLabel alloc] initWithText:@"blabla" textStyle:style];
        [labels replaceObjectAtIndex:0
                          withObject:label];
        NSSet *updatedLabels = [NSSet setWithArray:labels];
        ((CPTXYAxisSet *)mGraph.axisSet).xAxis.axisLabels = updatedLabels;
        [((CPTXYAxisSet *)mGraph.axisSet).xAxis updateMajorTickLabels];
    }

But this doesn't work.

**Comment by eskroch** [comment]
It doesn't look like the new label is completely set up. Make sure you set the `tickLocation` of the label so it shows up in the right place.

You don't need to call `-updateMajorTickLabels`. Setting the new axis labels does that for you.

**Comment by mancunianetz** [comment]
Thanks @eskroch. I've already fix it, totally forgot about setting ```tickLocation``` property.
