### ISSUE TITLE
Problem Building, Assigning to _Nullable from incompatible type

### ISSUE THREAD

**Issue by seeya** [core-plot/core-plot#253]
I've updated CorePlot from 1.6 to 2.0 and when I try to build it it gives a bunch of assigning errors.
`/EskPlotTheme.m:137:27: Assigning to 'NSNumber * _Nullable' from incompatible type 'NSDecimal'`

Not sure if it's my own problem, or the new xcode problem. Currently running on El Capitan 10.11.2 and Xcode 7.2 for iOS 9. I tried cleaning the project and rebuilding it but the error still exits.

**Comment by seeya** [comment]
It seems to be some API changes which causes this error, however I'm still unsure how do I upgrade the previous codes to the new API.

**Comment by iDevelopper** [comment]
[NSNumber numberWithDouble:0.5];

**Comment by eskroch** [comment]
There were some API changes between 1.x and 2.0. The biggest one is that all `NSDecimal` properties and method parameters were changed to take `NSNumber` instead. See [the wiki](https://github.com/core-plot/core-plot/wiki/Core-Plot-API-Changes-Between-Versions-1.x-and-2.x) for details about the changes.

You can also use the `@0.5` shorthand or a boxed expression (`@(0.5)`) to create an `NSNumber`.
