### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#254]
Straight out of the box CorePlot seems to be already working with Carthage, if I add the line `github "core-plot/core-plot"` to my Cartfile, it will download and install Release 2.0.  I'd like to use release 2.1 though, and if I change above line to `github "core-plot/core-plot" ~> 2.1`, it starts to download the `wwdcbranchupdate` instead. Not sure how this can be fixed, maybe the branches need to be renamed 2.x instead of release 2.x ?

**Comment by eskroch** [comment]
Carthage uses git tags to find the release numbers. Since 2.1 hasn't been released yet, there is no tag for it.

**Comment by koenvanderdrift** [comment]
Makes sense, thanks - I guess I got confused by the word 'release'.
