### ISSUE TITLE
CPTImage is displayed wrongly

### ISSUE THREAD

**Issue by mancunianetz** [core-plot/core-plot#255]
I'm trying to fill a plot with an image which is displayed as a striped box (it shows missing data).
The below code works, but there are two issues. First, because grid cell height is different when in portrait and landscape image is deformed (in landscape). Second, image height is smaller than filled area and above of it is displayed another striped box, which is not fine, I need only one striped box which fits filled area.

This is the code I configured the fill area image :  
```objective-c
...
    CPTImage *areaImage = [[CPTImage alloc] initWithCGImage:boxImage.CGImage];
    areaImage.tiled = YES;
    areaImage.scale = [UIScreen mainScreen].scale;
    areaImage.tileAnchoredToContext = NO;

    return [CPTFill fillWithImage:areaImage];
}
```
I was trying to find some helpful hints in the documentation but I didn't succeed. Point me out how to make image to be displayed fine.

**Comment by eskroch** [comment]
There are only two drawing options for drawing images: tiled or stretched to fill the area. What shape are you trying to fill?

If you don't want a tiled image (`tiled = YES`), you might need to use different fill images when in portrait or landscape. When the app notices the orientation change, update the `fill` with the right image.

**Comment by mancunianetz** [comment]
I need it to be tiled.  Tile looks like this 
![thumb_img_2434_1024 copy](https://cloud.githubusercontent.com/assets/2619031/12140717/c2f6daf8-b472-11e5-81bd-bdfa8babebad.jpg)


The result of above code is 
![thumb_img_2434_1024](https://cloud.githubusercontent.com/assets/2619031/12140687/801577da-b472-11e5-9af2-e21fd3468d86.jpg)

The problem is that I can't calculate or find out the right height to generate tile image, for both orientations.

**Comment by eskroch** [comment]
A tile image should make a repeating pattern when tiled. That image obviously doesn't do that. Make the tile image larger so that it includes enough of the pattern to have the desired appearance when tiled.

**Comment by mancunianetz** [comment]
Yes it makes. Here are 3 tiles:

![thumb_img_2434_1024 copy](https://cloud.githubusercontent.com/assets/2619031/12140717/c2f6daf8-b472-11e5-81bd-bdfa8babebad.jpg)![thumb_img_2434_1024 copy](https://cloud.githubusercontent.com/assets/2619031/12140717/c2f6daf8-b472-11e5-81bd-bdfa8babebad.jpg)![thumb_img_2434_1024 copy](https://cloud.githubusercontent.com/assets/2619031/12140717/c2f6daf8-b472-11e5-81bd-bdfa8babebad.jpg)

This is exactly what I need.

I've solved the problem this way:
```objective-c
- (void)viewDidLayoutSubviews
{
    CPTScatterPlot *gapPlot = (CPTScatterPlot *)[mGraph plotWithIdentifier:@(PlotDataGap)];
    if (gapPlot) {
        float plotPointHeight = (mGraph.frame.size.height - (mGraph.plotAreaFrame.paddingTop + mGraph.plotAreaFrame.paddingBottom)) / mPlotSpace.globalYRange.lengthDouble;
        gapPlot.areaFill = [ChartStyle getFillImageForGapPlotWithHeight: plotPointHeight * kGapPlotPointsAxisY];
    }
}
```

Each time device rotates, a new fill image is generated. To calculate height of the fill area, the height of a plot point (not sure if the definition is good) needs to be known. It's calculated this way:
pointHeight = (```CPTXYGraph``` height - (```CPTXYGraph``` area frame's top padding + bottom padding )) / ```CPTXYPlotSpace``` globalYRange.
The height of fill area is equal to ```pointHeight * numberOfPoints```.
