### ISSUE TITLE
Getting warnings with swift "Duplicate definition of category 'Cpt...' on interface 'NS...'

### ISSUE THREAD

**Issue by jc4432** [core-plot/core-plot#256]
I added the main branch and also tried release 2.1 and am getting these errors:

<img width="657" alt="screen shot 2016-01-05 at 10 27 53 pm" src="https://cloud.githubusercontent.com/assets/6857458/12134262/b12154b0-b3fb-11e5-8a36-0b8bae403f0b.png">

I am not sure if this has anything to do with the issue but what happens is when I make the bridger header file, I get the error that it cannot be found then I proceed toto move the bridge header file up a level alongside the xcodeproj and then the three warnings come. This may just be causing Xcode to run through the core plot pod or it may have a link. I am having a little trouble with converting the core plot to swift so if anyone has seen any good tutorials or sample apps that would be great. Thanks!

**Comment by eskroch** [comment]
How did you add Core Plot to your project? CocoaPods? Dependent project?

Those category headers have two versions, one for iOS and one for the Mac. Something in your project setup is trying to include both versions.

**Comment by jc4432** [comment]
I used cocoa pods

**Comment by eskroch** [comment]
Use `#import <CorePlot/CorePlot.h>` to import the headers. CocoaPods takes care of everything else.

**Comment by jc4432** [comment]
Aha! it was that simple. Thanks for the quick help.
