### ISSUE TITLE
CorePlot Framework TARGET_IPHONE_SIMULATOR

### ISSUE THREAD

**Issue by jeeftor** [core-plot/core-plot#257]
I have an iOS swift project and I've included the core plot via carthage.  

I'm trying to add some objc code and i'm getting the following error:

<img width="697" alt="screen shot 2016-01-08 at 3 03 55 pm" src="https://cloud.githubusercontent.com/assets/6491743/12208168/1250d94e-b619-11e5-9ac4-9eb92750aa95.png">

I'm assuming maybe my `TARGET_IPHONE_SIMULATOR || TARGET_OS_IPHONE` isn't getting set correctly.  Is there a way to verify this??

**Comment by jeeftor** [comment]
I fixed the bug by adding `#include <TargetConditionals.h>` to the first line of

`CorePlot.h` inside of my `CorePlot.framework`

<img width="516" alt="screen shot 2016-01-08 at 3 06 26 pm" src="https://cloud.githubusercontent.com/assets/6491743/12208206/6fe71b90-b619-11e5-99c1-2c2cfbb7425e.png">

Perchance  `#include <TargetConditionals.h>` should be added to `CorePlot.h`

**Comment by jeeftor** [comment]
It appears this was actually fixed but the carthage tag hasn't been bumped yet.  - if thats the case please feel free to close out this bug.

**Comment by eskroch** [comment]
Fixed in [commit ca0ab9f](https://github.com/core-plot/core-plot/commit/ca0ab9f4d4d5b371de6cabcb242961f80b4d63d9). It will be part of release 2.1.

**Comment by jeeftor** [comment]
Thanks
