### ISSUE TITLE
Animation not smooth when drag or scale for CPTTradingRangePlotStyleCandleStick plot

### ISSUE THREAD

**Issue by Toanso** [core-plot/core-plot#258]
why animation when drag or scale for CPTTradingRangePlotStyleCandleStick plot smooth under iOS 9.0, but after upgrade to iOS 9.x it will lag serious?
any idea?

**Comment by eskroch** [comment]
Did you change anything in the app or does the same build run fine on 9.0 and poorly on later versions? Device or simulator?

**Comment by Toanso** [comment]
I test on device and change nothing. the build run fine on 9.x, only the animation not smooth.

**Comment by eskroch** [comment]
Does your app use a plot space delegate or anything else that might also affect the scrolling and scaling? Have you profiled the app to see where the bottleneck is occurring?
