### ISSUE TITLE
width/heightDecimal properties not updated when CPTLayerBoundsDidChange is fired.

### ISSUE THREAD

**Issue by maltebargholz** [core-plot/core-plot#261]
Changing the bounds of an ````CPTPlotArea```` object causes an update on its properties ````widthDecimal```` and ````heightDecimal````. Unfortunately this happens after the ````CPTLayerBoundsChanged```` notification is fired. This means that ````CPTPlotArea````'s methods for converting a view point to a plot point are using wrong boundaries.
 When using a custom label placement code ````CPTLayerBoundsDidChange```` is the optimal place to update label position, which is not possible right now since ````plotPoint:numberOfCoordinates: forPlotAreaViewPoint):```` returns wrong values when called from the corresponding ````CPTLayerBoundsDidChange```` notification.
To fix this One could either move the ````widthDecimal````/````heightDecimal```` update code above ````[super setBounds:newBounds]```` or drop the ````widthDecimal````/````heightDecimal```` usage alltogether and simply convert the plotArea bounds to ````NSDecimal```` on-the-fly when converting a view point to a plot point an vice-versa.

**Comment by eskroch** [comment]
I moved the call to `super` after caching the decimal values. The cache is necessary to improve performance during drawing operations that use the plot space to convert many points.
