### ISSUE TITLE
how to summarize the values of the two (or more) line in one graphs?

### ISSUE THREAD

**Issue by Dem909** [core-plot/core-plot#265]
I constructed the chart a few lines, but the problem is that I need to output only one, and if the two (or more) graphics are on the same coordinate the X (my time) - they should summarize their values Y.

If someone faced, help please, because I have absolutely nothing happens (

PS. sorry for my English

**Comment by eskroch** [comment]
Core Plot does not summarize plot data. There are too many different types of data and ways to summarize it to include a general purpose solution. Plots will display all of their data points. If you want a summary, calculate the summarized values before sending them to the plot.
