### ISSUE TITLE
Build errors with latest Xcode (7.3b5)

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#266]
After installing the latest Xcode release from yesterday (Xcode 7.3 beta 5), I am getting a slew of build errors like this (using CorePlot 2.0 or 2.1):

`core-plot/framework/Source/CPTLayer.m:860:82: Implicit conversion increases floating-point precision: 'CGFloat' (aka 'float') to 'double'`

Maybe a build setting can turn error this off?

**Comment by eskroch** [comment]
Fixed in commit 4eb6e97008b1fa0a9b4f0de345f16ac7937995ea.

**Comment by koenvanderdrift** [comment]
I got another similar error in `CPTScatterPlot.m`:

```
- (void)setCurvedInterpolationCustomAlpha:(CGFloat)newCurvedInterpolationCustomAlpha
 {
     if ( newCurvedInterpolationCustomAlpha > (CGFloat)1.0 ) {
         newCurvedInterpolationCustomAlpha = 1.0;
     }
     if ( newCurvedInterpolationCustomAlpha < 0 ) {
         newCurvedInterpolationCustomAlpha = 0.0;
     }
 
     if ( newCurvedInterpolationCustomAlpha != curvedInterpolationCustomAlpha ) {
         curvedInterpolationCustomAlpha = newCurvedInterpolationCustomAlpha;
         [self setNeedsDisplay];
     }
 }

```

Casting 1.0 with a `CGFloat` made the error go away.

**Comment by eskroch** [comment]
I'm not seeing this error, but I know why it happens. I've fixed it. This is part of the new curved scatter plot options that is only on the release-2.1 branch.

**Comment by koenvanderdrift** [comment]
FYI, I only saw the error when archiving my project, not with a regular build.

**Comment by eskroch** [comment]
Thanks for the hint. I fixed a couple of other related issues in the *Plot Gallery* app, too.
