### ISSUE TITLE
Unable to resolve library not found -lCorePlot-CocoaTouch 

### ISSUE THREAD

**Issue by joshisunil-1983** [core-plot/core-plot#267]
_**1st Part **_

@eskroch 
i am using core plot library 1.5 which part of my existing app and working fine. recenetly i do not  work  on my app. but few days before i got some feedback from my client. so i open the Xcode project and found library missing error in my project after doing changes(which not related to chart). i try to add this library again. once my app deploy to developer device and after that it is not working on simulator and device as well. i   continuously getting missing library error. urgent help need what should i do.

**_2nd part_**
after posting first part of my query try with the latest library 2.0.r1. where i found some issues in my code **majorIntervalLength **  this was taking nsdecimal and now it is asking for nsnumber type. this kind of some more issues found in my code.

**Comment by eskroch** [comment]
Make sure the static library is included in the app target so it gets copied and linked with the app.

**Comment by joshisunil-1983** [comment]
i am able to deploy app on developer device after adding 1.6 lib to my app. but still unable to run it on simulator. what can i do.

**Comment by eskroch** [comment]
Release 2.0 changed the API in a few places to simplify it and make it easier to use with Swift. See the [wiki page](https://github.com/core-plot/core-plot/wiki/Core-Plot-API-Changes-Between-Versions-1.x-and-2.x) for details.

What do you mean by unable to run on the simulator? Does it build and not run or do you get build errors? Are you using the pre-built release versions or building from source?

**Comment by joshisunil-1983** [comment]
i am trying to run it on simulator and it is  showing message ld: library not found for -lCorePlot-CocoaTouch. i am using pre-built libCorePlot-CocoaTouch.a file which i download from git.

**Comment by eskroch** [comment]
Check the [installation instructions](https://github.com/core-plot/core-plot/wiki/Using-Core-Plot-in-an-Application) again. Make sure the Core Plot library is listed in the "Link Binary With Libraries" section in the Build Phases for the app target.

**Comment by joshisunil-1983** [comment]
@eskroch 
yes core plot library is listed in the  "Link Binary With Libraries"  section in the build phases of r the app target. i try again with the installation instructions but same build error occur.

**Comment by eskroch** [comment]
Make sure the "Library Search Paths" build setting includes the folder that holds the static library.

**Comment by joshisunil-1983** [comment]
Thanks for help i am done. do this path not mandatory earlier.
