### ISSUE TITLE
Random crash on graph touches

### ISSUE THREAD

**Issue by sergiomtzlosa** [core-plot/core-plot#272]
Hi,

I am using CorePlot 1.6 (iPhone), but I reproduced this bug in CorePlot 2.0 too. I am having trouble when I touch continously the graph, it gives crahses randomly.

My graph updates each second manually, I attach a new point at the end of the dataset and remove the first one. I think that it crashes when tries to calculate a new point to draw on screen. I just have the call stack because I cannot figure out what should be happening over CorePlot:

![screen shot 2016-03-31 at 15 59 47](https://cloud.githubusercontent.com/assets/381675/14178312/5c6c0fee-f75a-11e5-82f4-42d4fdf87d64.png)

Does somebody have a similar isssue? Do you know what should be happening?

Thanks!

**Comment by eskroch** [comment]
Did the plot have points added between the touch start and touch end events? What was the error message from the crash? The stack trace is helpful, but not the whole story.

**Comment by sergiomtzlosa** [comment]
Hi,

Thank a lot for your response, unfortunately XCode does not give significant information about the issue, just the stack trace, but after digging deeper in StackOverflow and many other sites I have found that if you want to update the date you must fix the axis with constraints because on each refresh both axis move and point calculation are sometimes wrong, this way I solved my issue:
```
    CPTXYAxisSet *axisSet = (CPTXYAxisSet *)graph.axisSet;

    axisSet.yAxis.axisConstraints = [CPTConstraints constraintWithLowerOffset:0.0f];
    axisSet.xAxis.axisConstraints = [CPTConstraints constraintWithLowerOffset:0.0f];
```

Thanks a lot!

**Comment by eskroch** [comment]
Did you solve the crashing problem or is the axis constraints solution unrelated to that issue?

**Comment by sergiomtzlosa** [comment]
Yes, my issue is solved, it was all about axis constraints.

Thank you
