### ISSUE TITLE
Reference line on a core plot

### ISSUE THREAD

**Issue by NANDEESHKUMAR** [core-plot/core-plot#277]
Hi ,

How I can draw a horizontal  reference line(like the red line on the below graph) on a barchart  ???
![barchart](https://cloud.githubusercontent.com/assets/18665100/14793047/80f617de-0b1d-11e6-9f23-6ab732b35271.png)

Help me in solving this

**Comment by eskroch** [comment]
For a simple horizontal or vertical line, you can use an additional axis. If you need something more complex (a marker somewhere on the line, user interaction, multiple lines, etc.), use a scatter plot. The "Selection Demo" in the Mac CPTTestApp example app uses a scatter plot to draw a plot symbol with horizontal and vertical lines through the selected plot point.

**Comment by NANDEESHKUMAR** [comment]
Thanks a lot eskroch :-)

**Comment by NANDEESHKUMAR** [comment]
Hi there is one more question

![bar chart 1](https://cloud.githubusercontent.com/assets/18665100/14821571/8686b4b6-0bcb-11e6-80fe-b78b718f427c.png)

I have created additional axis and my plot is looking like this.
What I want is I want the Axis to be shown on the top of the plot but in the above graph the axis is behind the plot.

How I can achieve it?

**Comment by iDevelopper** [comment]
#279
