### ISSUE TITLE
pod core-plot problem?

### ISSUE THREAD

**Issue by sujiewen** [core-plot/core-plot#278]
target 'YunyaPhysician' do
    platform :ios, '8.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'OpenUDID', '~> 1.0.0'
    pod 'AFNetworking', '~> 2.6.2'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'OHAlertView', '~> 3.0.1'
    pod 'OHActionSheet', '~> 2.0.1'
    pod 'CocoaLumberjack','~>2.2.0'
    pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
    pod 'PureLayout', '~> 3.0.1'
    pod 'SMPageControl', '~> 1.2'
    pod 'WebViewJavascriptBridge', '~> 5.0.5'
    pod 'HMSegmentedControl', '~> 1.5.2'
    pod 'RFQuiltLayout', '~> 1.1.1'
    pod 'MJExtension', '~> 3.0.10'
    pod 'ACEDrawingView', '~> 1.3.7'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'Color-Picker-for-iOS', '~> 2.0'
    pod 'FMDB/SQLCipher', '~> 2.6.2'
    pod 'JCAlertView', '~> 1.1.5'
    pod 'IQKeyboardManager', '~> 4.0.1'
    pod 'WZLSerializeKit', '~> 1.1'
    pod 'CMPopTipView', '~> 2.3.0'
    pod 'AFViewShaker', '~> 0.0.2'
    pod 'SSKeychain', '~> 1.4.0'
    pod 'TapkuLibrary', '~> 0.3.8'
    pod 'Curry', '~> 2.2.0'
    pod 'JTCalendar', '~> 2.1.5'
    #pod 'CorePlot', '~> 2.1'
    xcodeproj 'YunyaPhysician/YunyaPhysician.xcodeproj'
end

There is no problem with this.

target 'YunyaPhysicianBeta' do
    platform :ios, '8.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'OpenUDID', '~> 1.0.0'
    pod 'AFNetworking', '~> 2.6.2'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'OHAlertView', '~> 3.0.1'
    pod 'OHActionSheet', '~> 2.0.1'
    pod 'CocoaLumberjack','~>2.2.0'
    pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
    pod 'PureLayout', '~> 3.0.1'
    pod 'SMPageControl', '~> 1.2'
    pod 'WebViewJavascriptBridge', '~> 5.0.5'
    pod 'HMSegmentedControl', '~> 1.5.2'
    pod 'RFQuiltLayout', '~> 1.1.1'
    pod 'MJExtension', '~> 3.0.10'
    pod 'ACEDrawingView', '~> 1.3.7'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'Color-Picker-for-iOS', '~> 2.0'
    pod 'FMDB/SQLCipher', '~> 2.6.2'
    pod 'JCAlertView', '~> 1.1.5'
    pod 'IQKeyboardManager', '~> 4.0.1'
    pod 'WZLSerializeKit', '~> 1.1'
    pod 'CMPopTipView', '~> 2.3.0'
    pod 'AFViewShaker', '~> 0.0.2'
    pod 'SSKeychain', '~> 1.4.0'
    pod 'TapkuLibrary', '~> 0.3.8'
    pod 'Curry', '~> 2.2.0'
    pod 'JTCalendar', '~> 2.1.5'
    pod 'CorePlot', '~> 2.1'
    xcodeproj 'YunyaPhysician/YunyaPhysician.xcodeproj'
end

Is there a problem?! pod install ，Prompt a warning，

[!] The `YunyaPhysician [Debug]` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `../Pods/Target Support Files/Pods-YunyaPhysician/Pods-YunyaPhysician.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `YunyaPhysician [Release]` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `../Pods/Target Support Files/Pods-YunyaPhysician/Pods-YunyaPhysician.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `YunyaPhysicianBeta [Debug]` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `../Pods/Target Support Files/Pods-YunyaPhysicianBeta/Pods-YunyaPhysicianBeta.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `YunyaPhysicianBeta [Release]` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `../Pods/Target Support Files/Pods-YunyaPhysicianBeta/Pods-YunyaPhysicianBeta.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by eskroch** [comment]
I think that setting is only important when building Core Plot as a framework. I couldn't find any way to configure the pod spec to ignore it during static library builds only. You should be able to disable it by changing the setting in the `CorePlot.xcconfig` support file. Note that you'll have to make the change after each update to the pods.
