### ISSUE TITLE
Line Breaking problem in annotation - NSAttributed String with Antenna font

### ISSUE THREAD

**Issue by izik461** [core-plot/core-plot#280]
When creating plot annotation using Antenna fonts in NSAttributed string with line breaking, string is displayed only until it reaches \n sign, and then "...". Maybe other fonts are affected as well? Needs investigation.
Problem described here: http://stackoverflow.com/questions/36916969/cpttextlayer-multiple-lines-nsattributedstring

**Comment by slizeray** [comment]
Doesn't break the compatibility with previous versions, the existing margins will be changed and will be greater ?

**Comment by eskroch** [comment]
This only matters if the text layer has a fill and/or border. If you know a better way to fix this issue, I'm willing to listen.

**Comment by slizeray** [comment]
Not only it breaks the existing code, but also it adds an extra padding on the right and on the bottom
![img_0020 2](https://cloud.githubusercontent.com/assets/5292428/18255826/ce2ef98c-73ad-11e6-9c71-5b639fe2a60c.PNG)

**Comment by slizeray** [comment]
Did you try boundingRectWithSize: options: context:?

**Comment by eskroch** [comment]
I reverted the last change while looking for a different fix. We use `-boundingRectWithSize:options:attributes:context:` to compute the size of text generated from `NSString` text. However, `CPTTextLayer` can also display `NSAttributedString` text. We use the `-size` method for those.

I'll need to investigate whether we need to use a different method for attributed strings.

**Comment by slizeray** [comment]
Thanks!

**Comment by tvlc** [comment]
Hi, commit [e5607eb](https://github.com/core-plot/core-plot/commit/e5607eb4ae2c17f198d6f6fabb38ec940858e51b)
breaks compatibility with deployment target 10.8.
Used -boundingRectWithSize:options:attributes:context: method has been introduced in mac os x 10.11

**Comment by eskroch** [comment]
@tvlc The Mac deployment target for the Core Plot project is 10.8. That method is only used in one place and we check for availability with `-respondsToSelector:` before use and fall back to `-boundingRectWithSize:options:attributes:` if it isn't available.
