### ISSUE TITLE
MacOS - Xcode8 issue 

### ISSUE THREAD

**Issue by bendermh** [core-plot/core-plot#284]
Compiling on Xcode8 stopped by error:
/Users/XXXX/Documents/Xcode/XXXXX/framework-coreplot/Source/CPTTimeFormatter.m:119:56: Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'

**Comment by eskroch** [comment]
Fixed.

**Comment by koenvanderdrift** [comment]
Using release 2.2 and Xcode 8 beta 2, I get the following error:

`Signing for CorePlot iOS requires a development team. Select a development team in the Target Editor.`

Can I just use my own development team for this?

**Comment by eskroch** [comment]
Yes, although if you know a way to keep it generic, I'll fix it for everyone.

**Comment by koenvanderdrift** [comment]
Upgrading to Xcode 8 beta 3 seems to have solved it.

**Comment by helinyu** [comment]
It's show at 8.0 stable version

**Comment by antonio081014** [comment]
@helinyu Have you specified it to Release 2.2?

**Comment by eskroch** [comment]
[Release 2.2](https://github.com/core-plot/core-plot/releases/tag/release_2.2) requires Xcode 8.

**Comment by manjubasha** [comment]
Hi @eskroch  isnt 2.2 available to be downloaded via Cocoa Pods? 
I tried to download with cocoapods 2.1 was getting downloaded.

**Comment by eskroch** [comment]
Yes, it is. Include the following line in your pod file:

    pod 'CorePlot', '~> 2.2'
