### ISSUE TITLE
Core Plot Release 2.1 does not build under Xcode Version 8.0 beta (8S128d)

### ISSUE THREAD

**Issue by tedonaldsn** [core-plot/core-plot#286]
Problem 1
=========

File CPTTimeFormatter.m

Line 119: -(nullable NSString *)stringForObjectValue:(nonnull id)coordinateValue

Error: Nullability specifier ‘nonnull’ conflicts with existing specifier ‘nullable’

Problem 2
=========

File CPTCalendarFormatter.m

Line 145: -(nullable NSString *)stringForObjectValue:(nonnull id)coordinateValue

Error: Nullability specifier ‘nonnull’ conflicts with existing specifier ‘nullable’

Problem 3
=========

File CPTImage.m

Line 762: [self drawImage:theImage inContext:context rect:rect scaleRatio:scaleRatio];
Line 790: [self drawImage:imageSlices.slice[CPTSliceTopLeft]

Warning: Null passed to a callee that requires a non-null 1st parameter

Problem 4
=========

File CPTBarPlot.m

Line 944: return NULL;

Warning: Null is returned from a method that is expected to return a non-null value

**Comment by iDevelopper** [comment]
I think that the form of this message is not well correct! Some people develop librairies for you and you can't send a message like this!

**Comment by tedonaldsn** [comment]
Sorry. Was just trying to inform someone. Ignore the message. I'm sure someone who knows the proper incantations will report it later.

**Comment by tedonaldsn** [comment]
Core Plot developers are not developing for me. I gave Core Plot a shot. Does not build. rude response to an attempt to inform ya'll. Done with Core Plot.

**Comment by eskroch** [comment]
Duplicate of issue #284.

I fixed all of the new warnings from the Xcode 8 beta on the release-2.2 branch. Use the master branch or release 2.1 if you're still using Xcode 7.x.
