### ISSUE TITLE
Piechart with negative values (I know, it's impossible,  but..)

### ISSUE THREAD

**Issue by superandrew** [core-plot/core-plot#287]
Hi, when a piechart with the following series

    714936
    -713936
    500

is alterned with a series of positive numbers, for example

    443
    550
    506

When the reloadData is called, there's a huge CPU bottleneck and it takes 12 seconds on simulator, 30 on mobile to draw the chart.

I know it's impossible to have negative numbers on a piechart, however I'd like to warn about this problem.

follows a profile (simulator) screenshot
![screen shot 2016-06-21 at 23 06 58](https://cloud.githubusercontent.com/assets/71364/16246831/41cfe168-3807-11e6-996e-9e6b56b8c74d.png)

**Comment by eskroch** [comment]
Core Graphics isn't very smart about drawing arcs that wrap around the circle more than once. Constraining the drawing angles to 0...2π radians seems to fix the issue.
