### ISSUE TITLE
Build error with 2.2 release

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#288]
I'm getting the following build error on Xcode 7.3.1, using the 2.2 release branch:

`.../core-plot/framework/iPhoneOnly/CPTGraphHostingView.m:233:53: Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'`

The offending line is `-(void)touchesCancelled:(nonnull NSSet<UITouch *> *)touches withEvent:(nullable UIEvent *)event
`

**Comment by koenvanderdrift** [comment]
Sorry for the noise, just read in one of the closed issues that release 2.2 only works with Xcode 8.

**Comment by eskroch** [comment]
Duplicate of issue #284.

**Comment by guochangxindeGH** [comment]
I also encountered the same issue #284.
