### ISSUE TITLE
scatter plot symbols missing labels when animation active

### ISSUE THREAD

**Issue by slashlos** [core-plot/core-plot#293]
Once animation starts scrolling, the newest scatter points no longer have labels. This can be seen when altering the gallery sample scatter plot to label the symbols. An example of such can be found in InfoLineView module at https://drive.google.com/folderview?id=0B8QzZhjxD4brM1k0bFpGNFFDTjg&usp=sharing
/los

**Comment by eskroch** [comment]
See this StackOverflow [question](http://stackoverflow.com/questions/38555045) for more details.

**Comment by eskroch** [comment]
Fixed on the `release-2.2` branch.
