### ISSUE TITLE
Notify when x-axis labels hit chart's x-coordinate center

### ISSUE THREAD

**Issue by mancunianetz** [core-plot/core-plot#294]
![screen shot 2016-07-27 at 15 35 15](https://cloud.githubusercontent.com/assets/2619031/17179619/8bb7adce-5422-11e6-89ed-cc4c2ecfaf5b.png)
 
Each time when a x-axis `CPTAxisLabel` hits that center the client class must be notified about this. 
The problem is I couldn't find a way to implement a valid check of this, to see if label's x coordinate center is equal to chart x coordinate center.  What I tried so far is each time when a update of major ticks must be performed (when `CPTAxis`'s `updateMajorTickLabels` method is called) I get the each visible label position and try to match with chart's x coordinate center. But label x-coordinate position are not returning always omogen values: 0, 1, 2, 3,etc. It depends on scrolling velocity, the faster it is the bigger becomes gap between values: 0, 19, 55, etc; and if chart's x coordinate center is equl to 40,  labels are "skipping" it.

Thanks.

**Comment by eskroch** [comment]
I would use a plot space delegate to monitor changes to the plot space. Use one of the following methods:

    -plotSpace:willChangePlotRangeTo:forCoordinate:
    -plotSpace:didChangePlotRangeForCoordinate:

Plot ranges have a built-in properties to compute the center: `midPoint`, `midPointDecimal`, and `midPointDouble`, depending on the type you need.
