### ISSUE TITLE
newBarPathWithContext:recordIndex: in CPTBarPlot.m returns NULL although the return type is declared as non null

### ISSUE THREAD

**Issue by hwiesmann** [core-plot/core-plot#299]
The headline already says it. Here the code:

`
-(nonnull CGMutablePathRef)newBarPathWithContext:(nullable CGContextRef)context recordIndex:(NSUInteger)recordIndex
{
    // Get base and tip points
    CGPoint basePoint, tipPoint;
    BOOL barExists = [self barAtRecordIndex:recordIndex basePoint:&basePoint tipPoint:&tipPoint];

    if ( !barExists ) {
        return NULL;
    }
...
}
`

**Comment by eskroch** [comment]
This is fixed by commit 3a8f03195031c815f8cb792e2fe06653331952fb on the `release-2.2` branch. It will be part of the next release.
