### ISSUE TITLE
A Polar Plot Enhancement

### ISSUE THREAD

**Issue by swainwri** [core-plot/core-plot#300]
I've been working on a Polar Plot enhancement to core plot. I modified the Scatter Plot some years ago to show Traveling Cylinder data for oil wells anti-collision work. Having recently revisited the work, I realised I was miles away from having a complete solution. Now I have a bunch of files and a working example that would fit neatly into CorePlot Gallery. 
Presently I'm having difficulty, and it's always been a thorn, with clipping the baseAreaValue and Band Limits, I've set up for CPTPolarPlot. I've managed to create the CGPathRefs to represent the clipping area, and seen their shapes by outlining them, but try as I may, I ain't getting what I want. 
I'm ignorant of using Git, as this would be the first time to try to contribute. Where would I show my work etc.?
In need a bit of coaxing, to point me in the right direction, any advice would be appreciated.

**Comment by eskroch** [comment]
Have you forked the Core Plot project on GitHub? You'll need to incorporate your changes into a fork to make a pull request. It would also give us a place to review your work and offer suggestions.

**Comment by swainwri** [comment]
Ok, if I make a fork will this be available for the general public? Excuse my ignorance.

**Comment by swainwri** [comment]
I’m about to upload files, but just noticed my example in CorePlot Gallery, doesn’t
draw the line or baseAreas, although the image of the plot seems to be generated
for the Table View in the rootviewcontroller? Will have another 12 hours on it, then
just submit them. I made a video of the app I’m working on https://youtu.be/Tg7oeLvGwyI <https://youtu.be/Tg7oeLvGwyI>.

Using
#import <CorePlot/CPTPolarAxis.h>
#import <CorePlot/CPTPolarAxisSet.h>
#import <CorePlot/CPTPolarGraph.h>
#import <CorePlot/CPTPolarPlotSpace.h>
#import <CorePlot/CPTPolarPlot.h>

**Comment by eskroch** [comment]
@swainwri On GitHub, all of your projects are public unless you have a paid account. Once you fork another project, the fork belongs to you. The demo app looks cool.

**Comment by swainwri** [comment]
I’m afraid I’ve made a complete mess of my first attempt at uploading files.

Will have another go soon.

**Comment by swainwri** [comment]
I believe I made a better attempt at uploading files to the correct places. In English English to call somebody a git is quite a derogatory term.....but I've learnt some excellent stuff I was too lazy to get involved with previously i.e Git with Xcode & Python code generation.
To get back on track, I'm trying make the area I had the mouse twirling on in my video blank i.e. background. Out of luck I seem to have the Banding Limits working. I neglected to look at labelling for angles on the centre out lines, I'm tracing throw that at the moment.

**Comment by swainwri** [comment]
I have 2 zip files, my version of framework folder, and a working example. I'm spending too much time here with trying to understand Github....I need to crack on with other stuff. I feel an obligation to make this work available, as I've been using core-plot for some time now. 
[PolarPlot.zip](https://github.com/core-plot/core-plot/files/466572/PolarPlot.zip)
[framework.zip](https://github.com/core-plot/core-plot/files/466573/framework.zip)

**Comment by swainwri** [comment]
Hope this is of some use....

**Comment by eskroch** [comment]
Thanks. This might be useful when we get around to working on issue #31.

**Comment by swainwri** [comment]
I’m still not happy with how areaBase works if the angles don’t complete 360deg.
Perhaps somebody could check out that code. There should be a key hole effect
instead of shading across the whole area from circle limit and data path line.
Noticed I added to CPTNumericData, so that one could alter its sampleArray values directly
or by multiplying by a factor. This was so one could add angles either radians or degrees in
dataForPlot:recordIndexRange: there’s a radialAngleOption in CPTPolarSpace. There’s 
some cleaning up in CPTAxis class that could probably be placed in CPTPolarAxis.
The positioning of labels on the RadialAngle Axis needs looking as nearly got it right, but
not quit there.
Let me know here if you need me to relook at anything before you go ahead.
