### ISSUE TITLE
Xcode 8 GM Version errors: Implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float')

### ISSUE THREAD

**Issue by rajeshyandamuri** [core-plot/core-plot#301]
Source/Libs/core-plot-master/framework/iPhoneOnly/CPTPlatformSpecificCategories.m:128:23: Implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float')

Source/Libs/core-plot-master/framework/iPhoneOnly/CPTPlatformSpecificCategories.m:129:23: Implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float')

Source/Libs/core-plot-master/framework/iPhoneOnly/CPTPlatformSpecificCategories.m:128:37: Implicit conversion increases floating-point precision: 'CGFloat' (aka 'float') to 'double'

Source/Libs/core-plot-master/framework/iPhoneOnly/CPTPlatformSpecificCategories.m:129:37: Implicit conversion increases floating-point precision: 'CGFloat' (aka 'float') to 'double'

Xcode 8 GM version has the above errors.

**Comment by eskroch** [comment]
Fixed on the `release-2.2` branch.
