### ISSUE TITLE
Lot of issues with IOS 10.

### ISSUE THREAD

**Issue by simformsolutions** [core-plot/core-plot#302]
There are lot of conflict in current core plot library with IOS 10. Will there be any update for IOS 10 ?

**Comment by alcamla** [comment]
All of this conflicts are solved in branch version2.2

**Comment by eskroch** [comment]
I intend to release version 2.2 once Xcode 8 is finalized. In the meantime, use the code on the `release-2.2` branch.

**Comment by pnome** [comment]
That's good news :)  Do you know what date that would be? I'm now using the GM release of Xcode 8.

Will the pod version be updated at the same time?
Thanks,
Joe

**Comment by eskroch** [comment]
iOS 10 will be released tomorrow, September 13. Apple usually releases the final version of Xcode with iOS. Once it's out, I'll need a few days to download it and test Core Plot to make sure everything still works before I make the release package.

**Comment by eskroch** [comment]
Core Plot [release 2.2](https://github.com/core-plot/core-plot/releases/tag/release_2.2) is out now.
