### ISSUE TITLE
Coreplot throws error when downloaded with cocoapods-1.0.1

### ISSUE THREAD

**Issue by manjubasha** [core-plot/core-plot#304]
I am trying to download coreplot using Cocoapods 1.0.1 and it keeps throwing the error `'CorePlot/CorePlot-CocoaTouch.h' file not found` i tried various solutions given on the web and nothing worked for me. Do help me figure this out.

Here is a sample of my podfile code

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

xcodeproj 'Sample'

pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git', :branch => 'release-2.0'
pod 'Google/Analytics'


target 'SampleKIFTests', :exclusive => true do
  pod 'KIF', '~> 3.3.0'
  pod 'KIF/IdentifierTests', '~> 3.3.0'
end
```

**Comment by eskroch** [comment]
Is there any reason you're pointing to the branch and not the final release?

    pod 'CorePlot', '~>2.0'

Use this line to include the header when building as a static library:

    #import "CorePlot-CocoaTouch.h"

or this one when building a framework:

    #import <CorePlot/CorePlot.h>

**Comment by manjubasha** [comment]
Hi Eric,

Thank you for your response.
Long back we had issues with supporting our existing code with 2.1. 
Never mind. Changed my podfile to 

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

xcodeproj 'Sample'

pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'
pod 'Google/Analytics'


target 'SampleKIFTests', :exclusive => true do
  pod 'KIF', '~> 3.3.0'
  pod 'KIF/IdentifierTests', '~> 3.3.0'
end
```

I tried downloading the latest version of Coreplot and the following import statements
```
#import <CorePlot/CorePlot.h> 
#import "CorePlot-CocoaTouch.h" 
#import <CorePlot/CorePlot-CocoaTouch.h>
```
It still didnot work. Keeps throwing same error.

**Comment by manjubasha** [comment]
Is its something to do with cocoapods? When i download the same coreplot with cocoapods 0.38 it works perfectly. If i download it using a cocoapod version higher than 0.38, then the error gets fired.

**Comment by eskroch** [comment]
I'll have to do some testing. I'm getting ready to make the 2.2 release, so I'd like to resolve this before I do the release. Thanks for the heads-up.

**Comment by manjubasha** [comment]
Thats a relief. Thank you. Eagerly looking forward to hear from you.

**Comment by eskroch** [comment]
Cocoapods 0.39 and 1.0.1 both work fine for me. Look in the `Pods/CorePlot/framework` folder inside your project folder. Is the "CorePlot-CocoaTouch.h" header file there after a `pod update`?

**Comment by manjubasha** [comment]
`Pods/CorePlot/CorePlot-CocoaTouch.h ` is where the file is. 
The file has always been there, Whereas when i try to import the file in bridging header it throws the error.
```
'CorePlot-CocoaTouch.h' file not found
#import "CorePlot-CocoaTouch.h"
```

Like i said before i have tried using all the import statements, nothing worked though.
```
#import <CorePlot/CorePlot.h> 
#import "CorePlot-CocoaTouch.h" 
#import <CorePlot/CorePlot-CocoaTouch.h>
```

Or walk me through the steps ill see what am doing differently or missing.

**Comment by eskroch** [comment]
Check the "Header Search Paths" in the build settings. Make sure Cocoapods set it up to point to the Pods folder.

**Comment by thanhsoncun** [comment]
I try to import the file Pods folder but file 'CorePlot-CocoaTouch.h' file not found
