### ISSUE TITLE
typedef NSString *CPTLayerNotification cpt_swift_struct; ERROR

### ISSUE THREAD

**Issue by Airtower** [core-plot/core-plot#307]
I updated to CorePlot 2.2 via cocoaPods and now when I try to run and use my app, I get this error...

typedef NSString *CPTLayerNotification cpt_swift_struct;  <---Expected Expression

The error is in the CPTLayer.h file.

I can't figure out what the problem could be.

**Comment by iDevelopper** [comment]
Use Xcode 8 ans iOS 10.

**Comment by Airtower** [comment]
Will it still work if I make my target iOS 9.2 ? or does it need to be 10+?

**Comment by iDevelopper** [comment]
Yes it will work.

**Comment by Airtower** [comment]
Thank you for the help!

**Comment by iDevelopper** [comment]
The deployment target of CorePlot 2.2 is 8.0.
