### ISSUE TITLE
Issue with reload data

### ISSUE THREAD

**Issue by binoliMhatre** [core-plot/core-plot#308]
I get error when I use CPTScatterPlot.reloadData()
Can you fix this bug with CorePlot.

**Comment by eskroch** [comment]
What kind of error? Please be more specific.

What version of Core Plot are you using? Which platform?

**Comment by binoliMhatre** [comment]
Hi, I am sorry for insufficient information.
I am using Coreplot framework on Xcode Version 8.0.
In Swift 3, when I reload CPTScatterPlot I get an error as Ambiguous use of 'reloadData()'.
Can you please tell me how can I fix it.
I am stuck with it since a long time.

Thank you.

**Comment by eskroch** [comment]
Upgrade to a newer version of Core Plot. This is fixed in [release 2.2](https://github.com/core-plot/core-plot/releases/tag/release_2.2).
