### ISSUE TITLE
Deprecations in CPTTextStylePlatformSpecific.h

### ISSUE THREAD

**Issue by boisy** [core-plot/core-plot#309]
Hi guys,

On Xcode 8.1 and a minimum target of 10.12, the compiler is flagging the "TextAlignment" enumerations as deprecated. The new names are slightly rearranged for 10.12 (e.g. NSTextAlignmentLeft instead of NSLeftTextAlignment)

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
