### ISSUE TITLE
Anchor position for an annotation in unit coordinates with xConstraints and yConstraints

### ISSUE THREAD

**Issue by slizeray** [core-plot/core-plot#310]
Currently for an annotation, the anchor positions in unit coordinates are limited to the 9 possible values of CPTRectAnchor.

Would it be possible to make the xConstraints and yConstraints public, such as there is no limitation to set the anchor position of an annotation in unit coordinates with any values (0 to 1)?

**Comment by eskroch** [comment]
Yes, but I'm not sure that's the right API for it. I'll consider your pull request #311, too.

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
