### ISSUE TITLE
CPTAxisLabel direction display error when scrolling

### ISSUE THREAD

**Issue by L0omg** [core-plot/core-plot#313]
![lalog7d-us0br80dmg_922_431](https://cloud.githubusercontent.com/assets/3807454/20125560/31323c9a-a669-11e6-9289-9b0a7c531f28.png)
I try modify core-plot demo(CurvedInterpolationDemo) code, change yAxisLabel direction to positive, but it display error when scrolling.

![img_0311](https://cloud.githubusercontent.com/assets/3807454/20125617/7f91f1aa-a669-11e6-80b2-bae17048b068.jpg)
**## first**

![img_0312](https://cloud.githubusercontent.com/assets/3807454/20125629/8bad50b0-a669-11e6-9511-ce00b5ad66a2.jpg)
**## scroll**

**Comment by L0omg** [comment]
First axis label show in positive, but scroll after it show in negative.

**Comment by L0omg** [comment]
Find the bug, CPTAxis-updateCustomTickLabels direct use tickDirection.
![lalog75y8m0cl80era_1092_559](https://cloud.githubusercontent.com/assets/3807454/20126298/e8a270fc-a66e-11e6-9b8b-43b21f2f3bf4.png)

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
