### ISSUE TITLE
Why do the demos not use multiply target...

### ISSUE THREAD

**Issue by Huang-Libo** [core-plot/core-plot#315]
Why do the demos not use multiply target and reduce the project amount, there are too many project in a workspace...

**Comment by eskroch** [comment]
The `CorePlotExamples` workspace collects all of the example apps into a common area. You should not need to open the individual app projects separately.

Each example project includes targets for the related app. Most are for a single platform, while the *Plot Gallery* app includes targets for all supported platforms: Mac, iOS, and tvOS. A few, like the *MinorTickLabels* example have been absorbed into the *Plot Gallery* app, but they have internal differences that serve as useful integration tests for different Core Plot features. We've also converted two of the example apps, one each for iOS and the Mac, into Swift to test language integration issues between Swift and Objective-C.
