### ISSUE TITLE
Customisation for Out of range value display.

### ISSUE THREAD

**Issue by shrikanthananth** [core-plot/core-plot#317]
Currently I am working on already established application which uses Core plot and in specific its using ScatterPlot to draw a graph. This graph is drawn with values obtained from connected bluetooth device so the graph is dynamically drawn. XY graph with X axis having time value and Y axis having value from BLE device.

Now the requirement is to add an out of range value with a label "OL" in the graph and its not a fixed constant value for the bluetooth device(Its more of a state set in model object that is constructed in BLE layer with junk value obtained for that state and on which we can figure out its a out of range value).

So for e.g., if I get 'OL' value initially then I need to add it on graph above 0 with label "OL". '-OL' below 0 with label "-OL". The values obtained from BLE is continuously added to array and the graph is redrawn using this array.

So behaviour is expected as below: If I get 200 as value in the array and if the array has OL value then OL value has to be plotted above 200 and if the next value from BLE is 300 which will be added to array and since OL is above 200, now OL has to be plotted above 300.

I tried 2-3 different approaches to figure out a solution for this but with no success.

**Image of the expected requirement: as explained above require plotting with OL/-OL string for out of range plot **
![abgv1](https://cloud.githubusercontent.com/assets/11516657/21001515/b83fe0e0-bd46-11e6-9efc-7dd3871e824d.jpg)

**Comment by eskroch** [comment]
Asked and answered on [StackOverflow](http://stackoverflow.com/questions/40582944).
