### ISSUE TITLE
Y Axis grid not showing

### ISSUE THREAD

**Issue by ecnepsnai** [core-plot/core-plot#318]
I have a graph with a fixed X series of 24 objects, and I would like a vertical line for each X point.

This is what I have so far:

        CPTXXAxisSet * axisSet = (CPTXYAxisSet *)self.graph.axisSet;
        CPTAxis * x = axisSet.xAxis;
        x.majorIntervalLength = @1.0;
        x.preferredNumberOfMajorTicks = 24;
        x.minorTicksPerInterval = 0;
        CPTMutableLineStyle * style = [CPTMutableLineStyle lineStyle];
        style.lineWidth = 0.5f;
        style.lineFill = [CPTFill fillWithColor:[CPTColor lightGrayColor]];
        x.majorTickLineStyle = style;
        x.labelingPolicy = CPTAxisLabelingPolicyNone;

But no grid shows up? What am I missing?

---

**Edit** I originally stated that I had a fixed Y series, this is incorrect. I have a fixed X series.

**Comment by eskroch** [comment]
`labelingPolicy = CPTAxisLabelingPolicyNone` means you have to provide tick locations (major and/or minor) and any axis labels. I don't see that in the code provided.

It sounds like the default `CPTAxisLabelingPolicyFixedInterval` is the best choice for your situation. With that labeling policy, the `majorIntervalLength` adjusts the space between major tick marks.

**Comment by ecnepsnai** [comment]
I've updated my code:

    { // X Axis
        CPTAxis * x = axisSet.xAxis;
        x.majorIntervalLength = @1;
        x.preferredNumberOfMajorTicks = 24;
        CPTMutableLineStyle * style = [CPTMutableLineStyle lineStyle];
        style.lineWidth = 0.5f;
        style.lineFill = [CPTFill fillWithColor:[CPTColor lightGrayColor]];
        x.majorTickLineStyle = style;
        x.labelingPolicy = CPTAxisLabelingPolicyFixedInterval;
    }

But still no ticks or lines show up:

<img width="363" alt="screen shot 2016-12-18 at 19 29 24" src="https://cloud.githubusercontent.com/assets/1607109/21300383/4f75da64-c558-11e6-9eb4-040b8ea7adc3.png">

**Comment by eskroch** [comment]
Are those lines the axis lines or part of the border around the graph or plot area? If they're part of the border, you need to move the axes into the visible area. If they are the axes, what is the `xRange` of the plot space? The way it's set up now, you should have a tick mark at each integer value along the x-axis. If the range falls entirely between two tick marks you won't see the tick marks.

**Comment by ecnepsnai** [comment]
Ah, that did the trick! I moved my yRange a bit and and I can see that the ticks are below the border.  Now the question is, how can I see these lines without altering the ranges with the ranges? Padding doesn't seem to do the trick.

**Comment by eskroch** [comment]
Use the `axisConstraints` to position the axes independent of the plot ranges. You can specify a fixed distance from one of the edges or a percentage (useful, for example, for keeping them centered).
