### ISSUE TITLE
Remove ALWAYS_SEARCH_USER_PATHS=YES from podspec?

### ISSUE THREAD

**Issue by toreolsensan** [core-plot/core-plot#320]
I'm using CorePlot 2.2 in my project. After doing `pod install`, building in Xcode 8.1 gives me the following warning:
```
warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.
```

I tracked the source of this setting to CorePlot, and managed to get rid of the warnings by changing the setting to `NO` locally by doing `pod spec edit CorePlot` before rebuilding pod install/Xcode build.

Would you consider changing this setting? I suspect that commit 114de15e2866f7d1a9aad82f60da628380876880 which reintroduced this setting didn't really need to, and that adding the `HEADER_SEARCH_PATHS` would be enough in that case, but I haven't really investigated this.

This isn't a big deal, but having fewer build warnings is always nice.

**Comment by eskroch** [comment]
That setting was added to fix issue #243 last year. I'm not sure if its still needed with newer versions of Xcode in some situations.

I was able to reproduce this problem in my Cocoapods test project with Xcode 8.2. I fixed it by overriding the "Always Search User Paths" setting in the app to "No". Does that work for you? Note that you need to change the setting at the target level—Cocopods uses an .xcconfig file that overrides the project-wide setting.

**Comment by toreolsensan** [comment]
Thanks for taking your time to respond to this! You are correct that the warnings go away if you override the setting on the target in Xcode. However that causes `pod install` to complain:
```
[!] The `MyProject [Debug]` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Perhaps that's preferrable since it's not run so often but I still wonder if reintroducing ALWAYS_SEARCH_USER_PATHS=YES in that bugfix was strictly needed…

**Comment by zygoat** [comment]
Xcode 8.3, released today, [indicates](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html) that `ALWAYS_SEARCH_USER_PATHS` is now deprecated:

>The "Always Search User Paths" build setting is deprecated and may not be supported by a future version of Xcode. Projects which are relying on this feature should migrate to separate user vs. system header include semantics and set this build setting to "No". (16364329)

By virtue of Core Plot forcing this setting, our project always emits several annoying compiler warnings on build. Seems like no better time to get rid of this.

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.

**Comment by 3a4oT** [comment]
hey, what status has  2.3? Will it ever be released?

**Comment by eskroch** [comment]
I'll release it after the final version of Xcode 9 is released this fall.

**Comment by PaulWagener** [comment]
Any update?

**Comment by eskroch** [comment]
I'm working on resolving the last open pull request. I'll finalize the release after that is taken care of.

**Comment by 4brunu** [comment]
Hey, I hit this issue today, any update on this? 🙂

**Comment by eskroch** [comment]
I haven't had a lot of time to work on Core Plot lately. I'll try to make time to get this release finished soon.

**Comment by levigroker** [comment]
Bump...

**Comment by QuentinArnault** [comment]
Until 2.3 release, this problem can be handled this way:
```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'CorePlot'
                config.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'NO'
            end
        end
    end
end
```

**Comment by QuentinArnault** [comment]
Thanks for the feedback.

**Comment by mbaltaks** [comment]
You can always do it with a sharp knife in the meantime:

```ruby
post_install do |installer|
    `sed -i '' 's,ALWAYS_SEARCH_USER_PATHS = YES,,g' "Pods/Target Support Files/CorePlot/CorePlot.xcconfig"`
end
```
