### ISSUE TITLE
Specify width and stroke color for legend lines

### ISSUE THREAD

**Issue by ecnepsnai** [core-plot/core-plot#321]
On our graph the legend isn't legible due to its small size. Can we specify the line weight and stroke color for the legend line? And if not, could this be implemented as a feature?

![legend](https://cloud.githubusercontent.com/assets/1607109/21327526/75d4c3fa-c5e4-11e6-80d0-afeeafdaac89.png)

On the left is our current graph, on the right is what we'd like (ideally)

**Comment by eskroch** [comment]
You can use a legend delegate to change the drawing style. See the [`CPTLegendDelegate` documentation](http://core-plot.github.io/MacOS/protocol_c_p_t_legend_delegate-p.html) for more info.

**Comment by ecnepsnai** [comment]
Thank you! For what its worth, the documentation is extremely difficult to browse since it requires you to know what to look for, when you don't even know where to start.
