### ISSUE TITLE
How to add vertical crosshair line when drag or touch on iOS.

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#322]
Do you have any idea? how can i add vertical crosshair line when drag or touch and show value on iOS by using Coreplot.
Here is for example.
http://www.highcharts.com/stock/demo/responsive

**Comment by iDevelopper** [comment]
There is a sample in the demo project on Github.

And another one:

[CorePlotEvent.zip](https://github.com/core-plot/core-plot/files/675362/CorePlotEvent.zip)

Hope it helps!

**Comment by declareerror** [comment]
Yes, that's great.  One more question.
How can i add multiple panel in one graph like stock chart with indicator panel below as i mention before. 
http://www.highcharts.com/stock/demo/responsive

**Comment by eskroch** [comment]
There's also an example of a crosshair in the Mac *CPTTestApp* example app. You can use a plot space annotation to display the details of the selected point.

Use a second graph with its own hosting view for the other panel. The two graphs are independent of each other. In the posted example, you can use changes to the bottom graph to update the plot ranges and other properties of the upper one.

**Comment by declareerror** [comment]
@eskroch two plots are depend on each other like this 
http://www.highcharts.com/stock/demo/candlestick-and-volume
and i would like to show crosshair both panels

**Comment by eskroch** [comment]
It's the responsibility of the controller to keep the graphs in sync and to manage the crosshairs. The plots don't share a plot space or anything else, so it's much easier to display them in separate graphs that can be positioned and formatted independently.
