### ISSUE TITLE
core plot 1.5 shouldHandlePointingDeviceDownEvent 

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#323]
on this plot space delegate `shouldHandlePointingDeviceDownEvent`
my source code 
`CGPoint plotPoint = [space plotAreaViewPointForEvent:event];` 
how can i apply plotpoint  to display annotation.anchorPlotPoint correctly with xAxis and yAxis

**Comment by iDevelopper** [comment]
#322 should help you
