### ISSUE TITLE
plotPoint = [space plotPointForEvent:event] in coreplot 1.5

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#324]
`CPTNumberArray *plotPoint = [space plotPointForEvent:event];`
Is there any delegate to get plotPoint in core plot 1.5?
i used `plotAreaViewPointForEvent` in not correct point

**Comment by eskroch** [comment]
The best solution would be upgrade to a newer version of Core Plot that has the `-plotPointForEvent :` method. Version 2.2 is the latest latest release right now.

Core Plot 1.5 has these two methods that do the same operation, but return the result as a c-style array instead of an `NSArray` of `NSNumber` objects:

    -(void)plotPoint:(NSDecimal *)plotPoint numberOfCoordinates:(NSUInteger)count forEvent:(CPTNativeEvent *)event;
    -(void)doublePrecisionPlotPoint:(double *)plotPoint numberOfCoordinates:(NSUInteger)count forEvent:(CPTNativeEvent *)event;

**Comment by declareerror** [comment]
Do i have to use both or just one of them? 
Please give an example i have no idea. 
Thank you.

**Comment by eskroch** [comment]
Just one. Which one you choose depends on whether you need the values as `double` or `NSDecimal`.

Example:

    double start[2];

    [plotSpace doublePrecisionPlotPoint:start numberOfCoordinates:2 forPlotAreaViewPoint:dragStartInPlotArea];

    double xVal = start[CPTCoordinateX];
    double yVal = start[CPTCoordinateY];

**Comment by declareerror** [comment]
@eskroch these source code implement on 
`- (BOOL)plotSpace:(CPTPlotSpace *)space shouldHandlePointingDeviceDownEvent:(CPTNativeEvent *)event atPoint:(CGPoint)point`

and dragStartInPlotArea is point from delegate.

**Comment by eskroch** [comment]
What are you trying to do? Plot spaces have methods to convert back and forth between the plot area layer coordinates and data coordinates. Interaction points start out in the coordinate system of the graph layer, so you need to use `CALayer` methods to convert to the plot area layer first.

Later versions of Core Plot have the additional plot space methods to make this easier (e.g., the `-plotPointForEvent:` method mentioned in the original question). Is there any reason you can't upgrade to a newer version?

**Comment by declareerror** [comment]
@eskroch thank you.
