### ISSUE TITLE
Crash on CPTScatterPlotDelegate in renderAsVectorInContext:(nonnull CGContextRef)context

### ISSUE THREAD

**Issue by zzepos** [core-plot/core-plot#325]
I am trying to overlay multiple graphs in one plot and I am getting crashes (EXC_BAD_ACCESS) on the CPTScatterPlotDelegate at line 
id<CPTScatterPlotDelegate> theDelegate = self.delegate;
in method renderAsVectorInContext:(nonnull CGContextRef)context 
in class CPTScatterPlot.m

The Same in CPTLegendDelegate at line
id<CPTLegendDelegate> theDelegate = (id<CPTLegendDelegate>)self.delegate;
in method -(void)drawSwatchForLegend:(nonnull CPTLegend *)legend atIndex:(NSUInteger)idx inRect:(CGRect)rect inContext:(nonnull CGContextRef)context
in file CPTPlot.m

I am using CorePlot 2.1
I have modified the 
-(void)renderInGraphHostingView:(nonnull CPTGraphHostingView *)hostingView withTheme:(nullable CPTTheme *)theme animated:(BOOL)animated 
in file SimpleScatterPlot.m as 
......
   static CPTGraph *graph = nil;
   if( initialize ) {
        graph = [[CPTXYGraph alloc] initWithFrame:bounds];
        ........
    }
    [self addGraph:graph toHostingView:hostingView];
    theme      = [CPTTheme themeNamed:kCPTDarkGradientTheme];
......
So overtime I want to draw a new line of data I use the same graph. 

The problem is random and sometimes appears in the second line, sometimes in the third etc. It also depends on the compilation.
Any ideas?
Thanks in Advance

**Comment by eskroch** [comment]
Asked and answered on [StackOverflow](http://stackoverflow.com/questions/41447696/crash-on-cptscatterplotdelegate-in-coreplot).
