### ISSUE TITLE
Lines going backwards with CPTScatterPlotInterpolationCurved

### ISSUE THREAD

**Issue by pRizz** [core-plot/core-plot#329]
With `CPTScatterPlotInterpolationCurved`, it is possible for the drawn line to go backwards (to the left). This interpolation does not make sense for certain kinds of data, such as time based data.

I have reproduced this with this simple set of `(x, y)` data: `(0.0, 1.0), (0.05, 0.0), (1.0, 0.5)`.

This may be desired for some cases, so I propose a new kind of interpolation method, maybe called `CPTScatterPlotInterpolationCurvedForwards` which forces the interpolation lines to only go forwards.

![simulator screen shot feb 22 2017 12 05 01 pm](https://cloud.githubusercontent.com/assets/3519085/23225350/2b0a7fb8-f8f7-11e6-92b1-86074313c05e.png)

**Comment by eskroch** [comment]
Try one of the other interpolation options for the `curvedInterpolationOption` scatter plot property:

    typedef NS_ENUM (NSInteger, CPTScatterPlotCurvedInterpolationOption) {
        CPTScatterPlotCurvedInterpolationNormal,                ///< Standard Curved Interpolation (Bezier Curve)
        CPTScatterPlotCurvedInterpolationCatmullRomUniform,     ///< Catmull-Rom Spline Interpolation with alpha = @num{0.0}.
        CPTScatterPlotCurvedInterpolationCatmullRomCentripetal, ///< Catmull-Rom Spline Interpolation with alpha = @num{0.5}.
        CPTScatterPlotCurvedInterpolationCatmullRomChordal,     ///< Catmull-Rom Spline Interpolation with alpha = @num{1.0}.
        CPTScatterPlotCurvedInterpolationCatmullCustomAlpha,    ///< Catmull-Rom Spline Interpolation with a custom alpha value.
        CPTScatterPlotCurvedInterpolationHermiteCubic           ///< Hermite Cubic Spline Interpolation
    };

**Comment by pRizz** [comment]
Ah, didn't know about that API, thanks. After some testing, it looks like `CPTScatterPlotCurvedInterpolationCatmullRomChordal` is the best for this case.
