### ISSUE TITLE
How to set text layer annotation not transparent background color.

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#330]
How to set text layer annotation not transparent background color above all elements on the same view container. 
![Image of screen](http://i65.tinypic.com/25a6n3r.png)
@eskroch

**Comment by eskroch** [comment]
Use an opaque color for the text layer `fill`.

**Comment by declareerror** [comment]
`textLayer.opaque = NO;`
` textLayer.fill = [CPTFill fillWithColor:[CPTColor lightGrayColor]];`

Am i right? set opaque for text layer and use fill.
@eskroch

**Comment by eskroch** [comment]
Yes. If that doesn't work, post your code so we can get a better idea what's going on.

**Comment by declareerror** [comment]
it doesn't work.
`CPTMutableTextStyle *hitAnnotationTextStyle = [CPTMutableTextStyle textStyle];
    hitAnnotationTextStyle.color    = [CPTColor blackColor];
    hitAnnotationTextStyle.fontSize = 10;
    
    CPTTextLayer *textLayer = [[CPTTextLayer alloc] initWithText:@"Annotation\n new line" style:hitAnnotationTextStyle];
    textLayer.borderColor   = [[UIColor grayColor] CGColor];
    textLayer.cornerRadius  = 4.;
    textLayer.borderWidth   = 1.;
    textLayer.opaque = NO;
    textLayer.fill = [CPTFill fillWithColor:[CPTColor grayColor]];`

**Comment by eskroch** [comment]
Is this being displayed within a `CPTGraphHostingView`? It doesn't look like the gray background is being drawn at all. All Core Plot layers rely on infrastructure provided by the hosting view to render and update their layout properly.

**Comment by declareerror** [comment]
`annotation.contentLayer = textLayer;`
`[graph.plotAreaFrame.plotArea addAnnotation:annotation];`

i already added on plotArea

@eskroch

**Comment by iDevelopper** [comment]
Hi, I have an example in which it works well:

```
    // Setup a style for the annotation
    CPTMutableTextStyle *hitAnnotationTextStyle = [CPTMutableTextStyle textStyle];
    hitAnnotationTextStyle.color    = [CPTColor blackColor];
    hitAnnotationTextStyle.fontName = @"Helvetica-Bold";
    
    CPTTextLayer *textLayer = [[CPTTextLayer alloc] initWithText:@"Annotation" style:hitAnnotationTextStyle];
    textLayer.borderColor   = [[UIColor blueColor]CGColor];
    textLayer.borderWidth   = 2.;
    textLayer.backgroundColor = [UIColor whiteColor].CGColor;
    textLayer.paddingLeft   = 2.0;
    textLayer.paddingTop    = 2.0;
    textLayer.paddingRight  = 2.0;
    textLayer.paddingBottom = 2.0;
    //textLayer.hidden = YES;
    
    NSArray *anchorPoint = @[@0, @0];
    CPTPlotSpaceAnnotation *annotation = [[CPTPlotSpaceAnnotation alloc] initWithPlotSpace:_altGraph.defaultPlotSpace anchorPlotPoint:anchorPoint];
    annotation.contentLayer = textLayer;
    
    [_altGraph.plotAreaFrame.plotArea addAnnotation:annotation];
```

[CorePlotEvent.zip](https://github.com/core-plot/core-plot/files/800969/CorePlotEvent.zip)
