### ISSUE TITLE
CPTAnimation coreplot 1.5

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#332]
Is there any reason CPTAnimation not working on iPhone5s and upper models?

`        [CPTAnimation animate:volumePlotSpace
                     property:@"yRange"
                fromPlotRange:[CPTPlotRange      plotRangeWithLocation:lowVolumeAdding.decimalValue
                                                                length:CPTDecimalMultiply(lengthVolume.decimalValue, CPTDecimalFromInteger(10))]
                  toPlotRange:[CPTPlotRange      plotRangeWithLocation:lowVolumeAdding.decimalValue
                                                                length:lengthVolume.decimalValue]
                     duration:CHART_ANIMATION_DURATION
                    withDelay:0
               animationCurve:CPTAnimationCurveCubicInOut
                     delegate:nil];`

It's working in iPhone5 and lower  but not working on iPhone5s and upper. 
I don't know what wrong with my code.

@eskroch

**Comment by eskroch** [comment]
Are both phones running the same version of iOS? Can you upgrade to a newer version of Core Plot? Release 2.2 is the latest.

**Comment by declareerror** [comment]
Yes, I same version of IOS but there is no this problem on iOS simulator. It only on device.
I have to use version 1.5. 
Do i miss something? 

@eskroch

**Comment by eskroch** [comment]
What do you mean by "not working"? Does it crash? Does the graph display, but not animate? Do you see any console log messages?

It appears to work on 32-bit hardware but not 64-bit. How are you linking Core Plot with your app (embedded project, precompiled library, etc.)? Does the 64-bit version of Core Plot get linked into your app on 64-bit builds?

**Comment by declareerror** [comment]
App not crash but graph not show. i'm link core plot wite precomplied library.

**Comment by eskroch** [comment]
I don't think this is related to the animation code, then. Do you see any console log messages when the app tries to display the graph? Can you post your setup and datasource code here? It'll be much easier to help if we can see what's going on.

**Comment by declareerror** [comment]
but with the same code graph was show on iPhone5 with animation.
@eskroch

**Comment by eskroch** [comment]
Does the graph display on the 5S when you disable the animation? If not, that's not the problem and you have an issue somewhere else in the app. Without seeing the code, we can't tell if it's in the Core Plot setup or datasource code or somewhere else in the app.

**Comment by declareerror** [comment]
Yes , it's show when i set plots place without animation 

CPTXYPlotSpace *plotSpace  = (CPTXYPlotSpace *)martketGraph.defaultPlotSpace;

    CPTXYPlotSpace *volumePlotSpace = (CPTXYPlotSpace *)[martketGraph plotSpaceWithIdentifier:@"Volume Plot Space"];
    
    
    volumePlotSpace.xRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(0)
                                                          length:CPTDecimalFromInteger(0)];
    volumePlotSpace.yRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(0)
                                                          length:CPTDecimalFromInteger(0)];
    
    
    NSDecimalNumber *pricePlotSpaceDisplacementPercent = [NSDecimalNumber decimalNumberWithMantissa:1
                                                                                           exponent:-2
                                                                                         isNegative:NO];
    NSDecimalNumber *lowPlotSpaceDisplacementPercent = [NSDecimalNumber decimalNumberWithMantissa:5
                                                                                         exponent:-2
                                                                                       isNegative:NO];
    NSDecimalNumber *high   = [[NSDecimalNumber alloc]
                               initWithDouble:[[ohlcDataSource valueForKeyPath:@"@max.doubleValue"] doubleValue]];
    NSDecimalNumber *highDisplacementValue = [high decimalNumberByMultiplyingBy:pricePlotSpaceDisplacementPercent];
    NSDecimalNumber *highAdding   = [high decimalNumberByAdding:highDisplacementValue];
    NSDecimalNumber *low    = [[NSDecimalNumber alloc]
                               initWithDouble:[[ohlcDataSource valueForKeyPath:@"@min.doubleValue"] doubleValue]];
    NSDecimalNumber *lowDisplacementValue = [low decimalNumberByMultiplyingBy:lowPlotSpaceDisplacementPercent];
    NSDecimalNumber *lowAdding   = [low decimalNumberBySubtracting:lowDisplacementValue];
    NSDecimalNumber *length = [highAdding decimalNumberBySubtracting:lowAdding];
    
    
    NSDecimalNumber *highPlotSpaceDisplacementPercent = [NSDecimalNumber decimalNumberWithMantissa:88
                                                                                          exponent:-2
                                                                                        isNegative:NO];
    NSDecimalNumber *highVolume   = [[NSDecimalNumber alloc]
                               initWithDouble:[[volumeDataSource valueForKeyPath:@"@max.doubleValue"] doubleValue]];
    NSDecimalNumber *highVolumeDisplacementValue = [highVolume decimalNumberByMultiplyingBy:highPlotSpaceDisplacementPercent];
    NSDecimalNumber *highVolumeAdding   = [highVolume decimalNumberByAdding:highVolumeDisplacementValue];
    NSDecimalNumber *lowVolume    = [[NSDecimalNumber alloc]
                               initWithDouble:[[volumeDataSource valueForKeyPath:@"@min.doubleValue"] doubleValue]];
    NSDecimalNumber *lowVolumeDisplacementValue = [lowVolume decimalNumberByMultiplyingBy:pricePlotSpaceDisplacementPercent];
    NSDecimalNumber *lowVolumeAdding   = [lowVolume decimalNumberBySubtracting:lowDisplacementValue];
    
    NSDecimalNumber *lengthVolume = [highVolumeAdding decimalNumberBySubtracting:lowVolumeAdding];
    
    plotSpace.xRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(-1)
                                                    length:CPTDecimalFromInteger(ohlcDataSource.count + 1)];
    plotSpace.yRange = [CPTPlotRange plotRangeWithLocation:lowAdding.decimalValue
                                                    length:length.decimalValue];
//
    volumePlotSpace.xRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(-1)
                                                          length:CPTDecimalFromInteger(ohlcDataSource.count + 1)];
    volumePlotSpace.yRange = [CPTPlotRange plotRangeWithLocation:lowVolumeAdding.decimalValue
                                                          length:lengthVolume.decimalValue];
    
    
    plotSpace.delegate = self;
    
    
    if ( animationOperation ) {
        [[CPTAnimation sharedInstance] removeAnimationOperation:animationOperation];
    }
    
    if (priceAnimationOperation) {
        [[CPTAnimation sharedInstance] removeAnimationOperation:priceAnimationOperation];
    }
    
    if ( lowVolumeAdding && lengthVolume ) {
     
//        [CPTAnimation animate:volumePlotSpace
//                     property:@"yRange"
//                fromPlotRange:[CPTPlotRange      plotRangeWithLocation:lowVolumeAdding.decimalValue
//                                                                length:CPTDecimalMultiply(lengthVolume.decimalValue, CPTDecimalFromInteger(10))]
//                  toPlotRange:[CPTPlotRange      plotRangeWithLocation:lowVolumeAdding.decimalValue
//                                                                length:lengthVolume.decimalValue]
//                     duration:CHART_ANIMATION_DURATION
//                    withDelay:0
//               animationCurve:CPTAnimationCurveCubicInOut
//                     delegate:self];
        

//
//        [CPTAnimation animate:plotSpace
//                     property:@"yRange"
//                fromPlotRange:[CPTPlotRange      plotRangeWithLocation:lowAdding.decimalValue
//                                                                length:CPTDecimalMultiply(length.decimalValue, CPTDecimalFromInteger(10))]
//                  toPlotRange:[CPTPlotRange      plotRangeWithLocation:lowAdding.decimalValue
//                                                                length:length.decimalValue]
//                     duration:CHART_ANIMATION_DURATION
//                    withDelay:0
//               animationCurve:CPTAnimationCurveCubicInOut
//                     delegate:self];
        
//        animationOperation = [CPTAnimation animate:volumePlotSpace
//                                          property:@"yRange"
//                                     fromPlotRange:[CPTPlotRange      plotRangeWithLocation:lowVolumeAdding.decimalValue
//                                                                                     length:CPTDecimalMultiply(lengthVolume.decimalValue, CPTDecimalFromInteger(10))]
//                                       toPlotRange:[CPTPlotRange      plotRangeWithLocation:lowVolumeAdding.decimalValue
//                                                                                     length:lengthVolume.decimalValue]
//                                          duration:0.5];
        
//        priceAnimationOperation = [CPTAnimation animate:plotSpace
//                                          property:@"yRange"
//                                     fromPlotRange:[CPTPlotRange      plotRangeWithLocation:lowAdding.decimalValue
//                                                                                     length:CPTDecimalMultiply(length.decimalValue, CPTDecimalFromInteger(10))]
//                                       toPlotRange:[CPTPlotRange      plotRangeWithLocation:lowAdding.decimalValue
//                                                                                     length:length.decimalValue]
//                                          duration:CHART_ANIMATION_DURATION];
//        priceAnimationOperation.delegate = self;


here is method when i reload chart with animation. but i already comment.

@eskroch

**Comment by declareerror** [comment]
@eskroch 
Do you have any suggestions to animate chart from bottom to top without using cptanimation?
i have no idea.

**Comment by eskroch** [comment]
What delegate methods are implemented in the animation delegate? Do you also have a plot space delegate? Can you post the code from those delegate methods, too?

I'm still having trouble understanding why this works on 32-bit platforms and not 64-bit.

**Comment by declareerror** [comment]
`-(void)animationDidFinish:(CPTAnimationOperation` *)operation {
    NSArray *axisArray = martketGraph.axisSet.axes;

    
    CPTXYAxis *yAxis = [axisArray objectAtIndex:1];
    yAxis.labelingPolicy = CPTAxisLabelingPolicyAutomatic;
    
    CPTXYPlotSpace *plotSpace  = (CPTXYPlotSpace *)martketGraph.defaultPlotSpace;
    plotSpace.delegate = self;
    
    [graph reloadData];

   }

Here is delegate method that i implemented.

@eskroch

**Comment by eskroch** [comment]
Did you ever figure out what the problem was? I suspect it's some interaction between the various delegates, but it's hard to know without seeing all of the code.

**Comment by declareerror** [comment]
Thanks @eskroch  i figure out.
