### ISSUE TITLE
Implicit conversion error

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#333]
I'm getting the following two build errors:

`/core-plot/framework/Source/CPTPieChart.m:736:14: Implicit conversion increases floating-point precision: 'CGFloat' (aka 'float') to 'double'`

`/core-plot/framework/Source/CPTPieChart.m:746:14: Implicit conversion increases floating-point precision: 'CGFloat' (aka 'float') to 'double'`

Changing the code to `if ( currentWidth >= CPTFloat(1.0) )` fixed the issue.

This is with Release 2.3 and Xcode 8.2.1

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
