### ISSUE TITLE
How to set a variable width for bar chart elements

### ISSUE THREAD

**Issue by surayashivji** [core-plot/core-plot#340]
Hi! Thanks for your fantastic open source project. I am currently working with a real time data set that will have each bar having a different width. I'm currently looking for ways to change the width of each bar dynamically but haven't gotten anything working. Any suggestions?

Suraya

**Comment by mbrennek** [comment]
afaik, barWidth is set per-plot object.  so what I've done is have a single CPTXYGraph object with a CPTBarPlot per width of bar I want to support on the graph. i.e. one for full-width, one for half-width, etc.  This works if you've got a small set of known widths, but obviously that doesn't scale very well if you want every bar to be a different width.

**Comment by surayashivji** [comment]
Hmm, I have a pretty dynamic data set updating in real time with all different widths, but thank you for your input. I wonder if it would be altering something in the CPTBarPlot delegate...?

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
