### ISSUE TITLE
Undefined symbols for architecture armv7 CorePlot 2.2

### ISSUE THREAD

**Issue by hesham-thirdwayv** [core-plot/core-plot#341]
Currently I'm using CorePlot version 2.2 as a cocoa pod, when I'm trying to use it in my objective-c project I get the linker error
`Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_CPTXYGraph", referenced from:
      objc-class-ref in ChartViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 `
mainly here's the statement that causes the problem
`CPTXYGraph *newGraph = [[CPTXYGraph alloc] init];`
Any help would be appreciated :)
Thanks in advance

**Comment by eskroch** [comment]
Can you post the relevant parts of the pod file? What version of Xcode are you using?

**Comment by hesham-thirdwayv** [comment]
Thanks @eskroch I've resolved the issue by dragging an example project for the coreplot in the project navigator for the xcode, then added libCorePlot-Cocoatouch.a into link binary with libraries, then everything went fine.
Thanks a lot :)
