### ISSUE TITLE
scatterPlot:plotSymbolWasSelectedAtRecordIndex: doesn't get called

### ISSUE THREAD

**Issue by guthook** [core-plot/core-plot#342]
I've been using the CPTScatterPlotDelegate method `scatterPlot:plotSymbolTouchDownAtRecordIndex:withEvent:` on my scatter plot for a while, and it works fine. I just tried removing that method and switching to `scatterPlot:plotSymbolWasSelectedAtRecordIndex:` but none of the code is ever called when trying to select a plot symbol. 

I experimented a bit and found that both `scatterPlot:plotSymbolWasSelectedAtRecordIndex:` and `scatterPlot:plotSymbolTouchUpAtRecordIndex:` do nothing, regardless of what code is contained in the methods. `scatterPlot:plotSymbolTouchDownAtRecordIndex:withEvent:` and `scatterPlot:plotSymbolTouchDownAtRecordIndex:` both work fine. Is this just me?

edit: oops-- forgot, using Core Plot 2.2, iOS 10.3 and 10.3.2

**Comment by eskroch** [comment]
The wasSelected events require that the down and up events be over the same plot point. Make sure you don't move your finger while touching the plot. If you do, it will start a drag operation rather than register the selection.

There are several working examples in the scatter plots in the *Plot Gallery* example app.

**Comment by guthook** [comment]
Thanks @eskroch. I tried being very careful with tapping on the plot point, but no luck. I also added some logging to `plotSpace:willChangePlotRangeTo:forCoordinate:` to see if I was accidentally scrolling just a little bit, but no luck there either. Otherwise, I'm trying to follow the SimpleScatterPlot example as best I can. Strange.

**Comment by Sreekanth001** [comment]
Hey, @guthook can u share code of ScatterChart....

I am getting trouble, my code and getting errors images Below,

import UIKit
import CorePlot

class ViewController: UIViewController , CPTScatterPlotDataSource, CPTScatterPlotDelegate {
    
    var userWorkout = String()
    var elapsedTime = String()
    var lastExpectedWorkoutLog = String()

    @IBOutlet weak var hostView: CPTGraphHostingView!
    private var scatterGraph : CPTXYGraph? = nil
    typealias plotDataType = [CPTScatterPlotField : Double]
    private var dataForPlot = [plotDataType]()

    override func viewDidLoad() {
        super.viewDidLoad()
        initPlot()
    }
    func initPlot() {
        configureHostView()
        configureGraph()
        configureChart()
        configureLegend()
    }
    func configureHostView() {
        hostView.allowPinchScaling = false
    }
    func configureGraph() {
        // 1 - Create and configure the graph
        let graph = CPTXYGraph(frame: hostView.bounds)
        hostView.hostedGraph = graph
        graph.paddingLeft = 0.0
        graph.paddingTop = 0.0
        graph.paddingRight = 0.0
        graph.paddingBottom = 0.0
        graph.axisSet = nil
        // 2 - Create text style
        let textStyle: CPTMutableTextStyle = CPTMutableTextStyle()
        textStyle.color = CPTColor(componentRed: 255.0, green: 255.0, blue: 255.0, alpha: 1.0)
        textStyle.fontName = "HelveticaNeue-Bold"
        textStyle.fontSize = 16.0
        textStyle.textAlignment = .center
        // 3 - Set graph title and text style
        graph.title = "Heart Rate vs Time"
        graph.title = "\(base.name) exchange rates\n\(rate.date)"
        graph.titleTextStyle = textStyle
        graph.titlePlotAreaFrameAnchor = CPTRectAnchor.top
        graph.apply(CPTTheme(named:CPTThemeName.stocksTheme))
        // SetUpThePlotSpace
        var plotSpace = graph.defaultPlotSpace as! CPTXYPlotSpace!
        var xRange = plotSpace?.xRange.mutableCopy() as! CPTMutablePlotRange
        var yRange = plotSpace?.yRange.mutableCopy() as! CPTMutablePlotRange
        xRange.setLocationFloat(Float(0))
        xRange.setLengthFloat(Float(self.userWorkout!.lastExpectedWorkoutLog()!.elapsedTime))
        yRange.setLocationFloat(Float(0))
        yRange.setLengthFloat(Float(150))
        plotSpace?.xRange = xRange
        plotSpace?.yRange = yRange
        // ConfigureAxes
        var xts: CPTMutableTextStyle = CPTMutableTextStyle()
        xts.color = CPTColor(componentRed: 255.0, green: 255.0, blue: 255.0, alpha: 1.0)
        var axisFormatter = NumberFormatter()
        axisFormatter.maximumFractionDigits = 0
        axisFormatter.minimumIntegerDigits = 1
        let axisSet = graph.axisSet as! CPTXYAxisSet!
        let xAxis = axisSet?.xAxis as CPTXYAxis!
        xAxis?.axisTitle = CPTAxisTitle(text: "Elapsed Time (seconds)", textStyle: xts)
        xAxis?.labelFormatter = axisFormatter
        let yAxis = axisSet?.yAxis as CPTXYAxis!
        yAxis?.axisTitle = CPTAxisTitle(text: "Heart Rate (BPM)", textStyle: xts)
        yAxis?.labelFormatter = axisFormatter
        yAxis?.titleOffset = 35.0
        xAxis.setMajorIntervalLength(Float((self.userWorkout!.lastExpectedWorkoutLog()!.elapsedTime)/self.numberOfTicks))
        yAxis.setMajorIntervalLength(20)
        self.hostView.hostedGraph = self.graph
        var plot = CPTScatterPlot()
        plot.dataSource = self
        plot.identifier = "actual" as NSCoding & NSCopying & NSObjectProtocol
        var actualPlotStyle = plot.dataLineStyle?.mutableCopy() as! CPTMutableLineStyle
        actualPlotStyle.lineWidth = 2.0
        actualPlotStyle.lineColor = CPTColor(CGColor: (UIColor.yellowColor.CGColor))
        plot.dataLineStyle = actualPlotStyle
        plot.interpolation = CPTScatterPlotInterpolationCurved
        self.graph.addPlot(plot)
    }
    func configureChart() {
        // 1 - Get a reference to the graph
        let graph = hostView.hostedGraph!
        // 2 - Create the chart
        let scatterChart = CPTScatterPlot()
        scatterChart.delegate = (self as CALayerDelegate)
        scatterChart.dataSource = (self as CPTPlotDataSource)
        scatterChart.scatt = (min(hostView.bounds.size.width, hostView.bounds.size.height) * 0.7) / 2
        scatterChart.identifier = NSString(string: graph.title!)
        scatterChart.startAngle = CGFloat(M_PI_4)
        scatterChart.sliceDirection = .clockwise
        scatterChart.labelOffset = -0.6 * pieChart.pieRadius
        // 3 - Configure border style
        let borderStyle = CPTMutableLineStyle()
        borderStyle.lineColor = CPTColor.white()
        borderStyle.lineWidth = 2.0
        scatterChart.borderLineStyle = borderStyle
        // 4 - Configure text style
        let textStyle = CPTMutableTextStyle()
        textStyle.color = CPTColor.white()
        textStyle.textAlignment = .center
        scatterChart.labelTextStyle = textStyle
        // 5 - Add chart to graph
        graph.add(scatterChart)
    }
    
    func configureLegend() {
        // 1 - Get graph instance
        guard let graph = hostView.hostedGraph else { return }
        // 2 - Create legend
        let theLegend = CPTLegend(graph: graph)
        // 3 - Configure legend
        theLegend.numberOfColumns = 1
        theLegend.fill = CPTFill(color: CPTColor.white())
        let textStyle = CPTMutableTextStyle()
        textStyle.fontSize = 18
        theLegend.textStyle = textStyle
        // 4 - Add legend to graph
        graph.legend = theLegend
        if view.bounds.width > view.bounds.height {
            graph.legendAnchor = .right
            graph.legendDisplacement = CGPoint(x: -20, y: 0.0)
        } else {
            graph.legendAnchor = .bottomRight
            graph.legendDisplacement = CGPoint(x: -8.0, y: 8.0)
        }
    }
    func numberOfRecords(for plot: CPTPlot) -> UInt {
        let count = 1;
        return UInt(count)
    }
    func numberForPlot(plot: CPTPlot!, field fieldEnum: UInt, recordIndex idx: UInt) -> NSNumber! {
        
        plot.identifier?.description == "expected"
            var workoutLog = self.userWorkout.expectedWorkoutLogAtIndexOrLast(idx)
            if workoutLog == nil {
        }
        return (fieldEnum == UInt(CPTScatterPlotFieldX.value)
                ? workoutLog!.elapsedTime : workoutLog!.bpm)
     }
}


<img width="908" alt="screen shot 2017-07-15 at 3 19 20 am" src="https://user-images.githubusercontent.com/25745802/28232122-b09d7fc4-690c-11e7-9d4e-d05774978b24.png">
<img width="897" alt="screen shot 2017-07-15 at 3 19 38 am" src="https://user-images.githubusercontent.com/25745802/28232134-be478e4e-690c-11e7-949c-31adfdbe609c.png">
<img width="895" alt="screen shot 2017-07-15 at 3 19 50 am" src="https://user-images.githubusercontent.com/25745802/28232146-cc0753de-690c-11e7-9521-08ce31dc4a57.png">

**Comment by guthook** [comment]
@eskroch  Problem solved! There was a tap gesture recognizer on the HostView that was blocking other delegate methods. Oops :-)
