### ISSUE TITLE
Core Plot is broken with Xcode 9’s new build system

### ISSUE THREAD

**Issue by LeoNatan** [core-plot/core-plot#343]
This is due to use of `USER_HEADER_SEARCH_PATHS` and `ALWAYS_SEARCH_USER_PATHS`.
The new build system has the following complaint:
> Traditional headermap style is no longer supported; please migrate to using separate headermaps and set ‘ALWAYS_SEARCH_USER_PATHS’ to NO. (in target 'CorePlot Mac')
For some reason, it includes the iOS header files.

**Comment by LeoNatan** [comment]
I am using the tip of the 2.3 branch. 
To test for this error, change the build system in File -> Project Settings.

**Comment by LeoNatan** [comment]
Here is a screenshot of how to enable:

<img width="536" alt="screen shot 2017-07-25 at 19 08 58" src="https://user-images.githubusercontent.com/2270433/28582136-03d5ec72-716d-11e7-98db-b98b1fa0c243.png">

**Comment by eskroch** [comment]
I'll make sure this is fixed for release 2.3.

**Comment by LeoNatan** [comment]
Thank you!

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.

**Comment by LeoNatan** [comment]
Thank you, that solved my issue!

**Comment by zx5000** [comment]
Has this branch been released? core-plot-master is still version 2.2 and is missing libCorePlot-CocoaTouch.a. I built the iOS app with branch-2.3 but it wants XCTest which missing on the simulator.

**Comment by albashahmad** [comment]
Rewrite lines causing the error as following :

    NSNumber *a = [self cachedNumberForField:CPTTradingRangePlotFieldOpen recordIndex:idx];
    NSNumber *b =  [self cachedNumberForField:CPTTradingRangePlotFieldClose recordIndex:idx];
    NSNumber *c = [self cachedNumberForField:CPTTradingRangePlotFieldHigh recordIndex:idx];
    NSNumber *d = [self cachedNumberForField:CPTTradingRangePlotFieldLow recordIndex:idx];
    CPTNumberArray *yValues = @ [a,
                               b,
                                c,
                                d];
it worked for me
