### ISSUE TITLE
How to get visible size and real size of plotspace 

### ISSUE THREAD

**Issue by PhamPhiPhuc** [core-plot/core-plot#354]
I set xRange and globalXRange by:

```objective-c
[plotSpace setXRange:[CPTPlotRange plotRangeWithLocation:[NSNumber numberWithInt:0] length:[NSNumber numberWithInt:5]]];
```
when I get xRange.lengthDouble, it returned 5.0.

How can I visible size and real size of plotspace. I tried to get distance between points, but I couldn't find way to do that.

Thank you.

**Comment by eskroch** [comment]
What do you mean by "visible size" and "real size"? Are you looking for a pixel distance between two points?

**Comment by eskroch** [comment]
The graph's `plotArea` (`graph.plotAreaFrame.plotArea`) is the `CALayer` that contains the plot. You can get the `size` of its `bounds` to see how much screen space it occupies. The plot ranges of the plot space (`xRange` and `yRange`) describe the mapping from plot data to the screen. The `length` of each range determines how much data is visible in each dimension.
