### ISSUE TITLE
Legend difference in behaviour between High Sierra and earlier versions

### ISSUE THREAD

**Issue by JoaoSantinha** [core-plot/core-plot#356]
Hi all,

I have found differences in behaviour between High Sierra and earlier versions. I am able to place and view the legend on a scatter plot in macOS Sierra or earlier but when in macOS High Sierra I cannot see the legend. 

Is this a known issue? Am I doing something wrong?

Let me know if you need something to check this.

Thanks

**Comment by eskroch** [comment]
There shouldn't be any difference between recent macOS versions. Please provide more detail and screenshots, if possible.

Are you running the same compiled binary on different OS versions or compiling separately on each system? Are you using a pre-built Core Plot binary or building from source? What versions of Core Plot and Xcode are you using?

**Comment by eskroch** [comment]
Those are obviously two different graphs. What happens when you run the same app binary on the different OS versions?

**Comment by JoaoSantinha** [comment]
I am sorry if the difference in examples lead you to understand it was a different app or that it I was running different app binaries for different OS versions. I am compiling my app with **Base SDK** = macOS 10.13 and **macOS Deployment Target** = macOS 10.10. In this application the user can see the different curves (corresponding to measures taken at different time points) of the distribution of data for a bunch of parameters that are the on the segmented control.  

Below you can find a new example take with macOS Sierra not for the same parameter but with the same number of time points.

<img width="776" alt="macos_sierra_new" src="https://user-images.githubusercontent.com/25960165/32541518-ce963136-c467-11e7-9ad4-927c36eec5be.png">

The code that I am using to do this is the following:
```objectivec
- (void) configureLegend
{
    if (! plotView.hostedGraph)
        return;
    
    CPTGraph *graph = plotView.hostedGraph;
    CPTLegend *legend = [CPTLegend legendWithGraph:graph];
    
    legend.numberOfColumns = 1;
    legend.fill = [CPTFill fillWithColor:[CPTColor whiteColor]];
    legend.borderLineStyle = [CPTLineStyle lineStyle];
    legend.cornerRadius = 5.0;
    
    graph.legend = legend;
    graph.legendAnchor = CPTRectAnchorTopRight;
    graph.legendDisplacement = CGPointMake(-10., -10.);

}
```

Hope this help make thing clear. Thank you

**Comment by eskroch** [comment]
Make sure the call to `-legendWithGraph:` is after the plots are added to the graph. It needs information about the plots to build the legend entries. You can add them to the legend later, but that's the more complicated way to do it.
