### ISSUE TITLE
CPTRangePlot indicate central value

### ISSUE THREAD

**Issue by TheTrueTom** [core-plot/core-plot#357]
Hi,

I'm currently using release-2.3.

For the moment I'm drawing a CPTRangePlot although the middle value is not indicated. Is it possible to draw a horizontal bar (same width as the top and bottom bars) on the central value without having to add a scatter plot on top of the range plot ?

Thanks for your answers

**Comment by eskroch** [comment]
Yes, you'll have to use another plot to draw a line through the middle. Which plot type you choose depends on the appearance you want.
