### ISSUE TITLE
Cyclic dependency in module 'Darwin': in XCode 9.2

### ISSUE THREAD

**Issue by ajayghodadra** [core-plot/core-plot#359]
Hi,

I am using[ Google Speech api](https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/speech/Swift/Speech-gRPC-Streaming) in Swift project and with core-plot it results in cyclic dependency. 

<img width="345" alt="screenshot at dec 27 20-38-51" src="https://user-images.githubusercontent.com/31757357/34401810-9f09042e-ebc3-11e7-9e76-297755e075c5.png">

@eskroch Could you please help me with this? It can be easily reproduced by installing Google speech and Core-plot via Cocoapods.

**Comment by eskroch** [comment]
Can you provide a sample podfile that demonstrates the problem?

**Comment by ajayghodadra** [comment]
@eskroch Sure, there are just two pods.

pod 'CorePlot', '~> 2.2' 
pod 'googleapis', :path => '.'

For googleapis, I think you will have to refer their documentation because it's not that straight forward.

**Comment by eskroch** [comment]
I saw the cyclic redundancy errors but they went away after I deleted the CocoaPods lock files and reinstalled the pods. Now all I see are compiler errors that say it can't find various header files.
