### ISSUE TITLE
使用coreplot如何让图跳到某一个index

### ISSUE THREAD

**Issue by MonekyHou** [core-plot/core-plot#361]
使用coreplot如何让图跳到某一个index  是哪个方法还是属性可以设置么 help

**Comment by eskroch** [comment]
This is what I get from Google Translate:
"How to use coreplot jump to a map index which method or property can be set Help"

I don't understand the question. Can you provide more detail, preferably in English?

**Comment by MonekyHou** [comment]
Thank you, I used to use coreplot want him to automatically move up, and now I have solved, best wishes

**Comment by antonio081014** [comment]
I think he might be asking:
How to have your graph move to specific index with/out animation?
Should I call some functions or update any properties to achieve this?

**Comment by eskroch** [comment]
What do you mean "move to a specific index"? Highlight some data point(s)? Change the data values? Take a look through the example apps, especially the *Plot Gallery*, and see if anything jumps out at you. A proper answer to this question really depends on the type of plot and what effect you're trying to achieve.

**Comment by antonio081014** [comment]
Let's say the plot is displaying very end values of a list, but would like to move the plot to display the very first few values instead, probably with animation.

**Comment by eskroch** [comment]
You can animate changes to the plot ranges on the plot space to move and/or resize the visible part of the data space.
