### ISSUE TITLE
Building with Xcode 9.2 on branch 'release-2.3' causes multiple build errors

### ISSUE THREAD

**Issue by boisy** [core-plot/core-plot#364]
Hello,

I'm trying to build Core Plot on the release-2.3 branch using Xcode 9.2. I've pulled down the code and checked out the 'release-2.3' branch, then opened the CorePlot.xcodeproj file in the framework directory.

Building the target 'CorePlot Mac' starts, but then fails with a litany of errors like these:

```
Showing All Issues
:-1: missing input '/Users/builder/core-plot/build/CorePlot.build/Debug/CorePlot Mac.build/Objects-normal/x86_64/CPTGraph.o' and no rule to build it
```

Can you advise what might be causing this?

**Comment by boisy** [comment]
Please close this issue. It was a system-specific problem that has been resolved.

**Comment by brunolemos** [comment]
@boisy what do you mean? How to fix this?
I don't use `core-plot` but I'm having this `missing input` `no rule to build it` error on a react-native project.

**Comment by boisy** [comment]
@brunolemos I don't recall what the issue was, but it seemed to go away after a full clean, as I recall.
