### ISSUE TITLE
iOS 9

### ISSUE THREAD

**Issue by AlexandreDerksen** [core-plot/core-plot#365]
Hello,

Have you plan to provide iOS 9.x deployment target for CorePlot ?
If yes, when ?

Regards

**Comment by tomvolek** [comment]
HI Eric :  Any chance of providing a recent build which works with xcode 9.2  ?  Highly appreciate it . 
Objective C of course :) 

Tom

**Comment by eskroch** [comment]
The iOS deployment target is iOS 8.0. Core Plot should work on any version higher than that. All recent development has been on the `release-2.3` branch. I keep it up-to-date with the latest Xcode release (currently 10.0) and upcoming beta versions. In most cases it will still work with recent prior Xcode versions, but no promises.
