### ISSUE TITLE
barFillForBarPlot get multiple legend

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#368]
I would like to set bar fill different color and show legend. but i get multiple lengend on graph.
How can i fix it. @eskroch

**Comment by eskroch** [comment]
Can you show your code and/or a screenshot? It's not clear what you're asking.

**Comment by declareerror** [comment]
I have only to plot in my graph bar chart and scatter plot and create legend
`CPTLegend *theLegend = [CPTLegend legendWithGraph:superChartGraph];
    theLegend.textStyle    = legendTextStyle;
    theLegend.numberOfColumns = self.viewModel.graphModel.chartList.count;
    theLegend.numberOfRows = 1;`

screen shot
[https://ibb.co/kHTa8S](url)

but when i implement delegate
`-(CPTFill *)barFillForBarPlot:(CPTBarPlot *)barPlot recordIndex:(NSUInteger)index {}`

There are number of legend equal array count
@eskroch

**Comment by declareerror** [comment]
Here is screen short after i implement delegate barFillForBarPlot

[https://tppr.me/UrRBm](url)

Threre are duplication legend

**Comment by declareerror** [comment]
@eskroch  Do you have any ideas how to fix it.

**Comment by eskroch** [comment]
The screenshot links are broken.

**Comment by declareerror** [comment]
Here is url  https://tppr.me/UrRBm

**Comment by eskroch** [comment]
Sorry this took so long to answer. This is the default behavior. The assumption is that if you're using individual bar fills, the different fills have meaning that you want reflected in the legend.
