### ISSUE TITLE
Offset for ScatterPlot

### ISSUE THREAD

**Issue by sebids** [core-plot/core-plot#369]
I have a CPTBarPlot and a CPTScatterPlot in ohne Graph.

I set the barOffset of the barPlot, so that the bars aren't glued to the border.

Now my scatter plot is no longer aligned with the bar plot.
Is there a way to set an offset for a scatter plot, too?

**Comment by eskroch** [comment]
Adjust the plot ranges on the plot space to inset the data from the edges instead of using the `barOffset`.

**Comment by sebids** [comment]
Thank you. That helped!
