### ISSUE TITLE
NSDecimal  issue

### ISSUE THREAD

**Issue by caolonghan** [core-plot/core-plot#371]
after updating version 2.2,this function"plotRangeWithLocation"where used in old version running error with " Sending 'NSDecimal' to parameter of incompatible type 'NSNumber * _Nonnull'"

**Comment by eskroch** [comment]
There were some significant API changes between 1.x and 2.0. See the [Release 2.0 API Changes](https://github.com/core-plot/core-plot/blob/master/documentation/changelog.markdown) wiki page for a detailed list.
