### ISSUE TITLE
CPTGraphHostingView and printing, Xcode editor reports error

### ISSUE THREAD

**Issue by Dirk-** [core-plot/core-plot#373]
I am using CorePlot on macOS, and I implemented graph printing. For that, I need to access the `printRect` property of `CPTGraphHostingView`. It compiles and works fine, but Xcode always shows me the error `Property 'printRect' not found on object of type 'CPTGraphHostingView *'` when it is not compiling. It flags the error on the line
      `self.myCPTView.printRect = thePrintRect;`
Xcode even finds `printRect` when I select "Jump To Definition", but still complains.

I added a similar line to `PlotGalleryController.m` in the Plot Gallery example project where `CPTGraphHostingView` is used and Xcode shows the same error.

Is there a way to silence this?

**Comment by eskroch** [comment]
I see similar errors in some of the Core Plot example apps. Xcode sometimes finds the iOS headers when compiling a Mac app. I've been looking, but I haven't found the root cause yet.

**Comment by Dirk-** [comment]
So it is not only me. I think I will file a bug report for Xcode.
