### ISSUE TITLE
Error on application build 

### ISSUE THREAD

**Issue by tomvolek** [core-plot/core-plot#374]
HI : 

 I recently upgraded to xcode : Version 9.2 (9C40b) .  I am using coreplot in one of my applications and Now I am getting errors on build.  Not sure if this is coming from coreplot or from something else.  I Appreciate any hints.  

<img width="543" alt="screen shot 2018-04-09 at 12 47 07 pm" src="https://user-images.githubusercontent.com/359429/38519454-c0b2645e-3bf4-11e8-9d88-5f45f3d422bf.png">

<img width="722" alt="screen shot 2018-04-09 at 12 49 04 pm" src="https://user-images.githubusercontent.com/359429/38519467-cc4c08ec-3bf4-11e8-8a66-d00f8a95cf06.png">

Thanks
Tom

**Comment by eskroch** [comment]
What version of Core Plot are you using?

**Comment by eskroch** [comment]
What version of Core Plot are you using? Try the `release-2.3` branch if you're not already using that.

**Comment by tomvolek** [comment]
Thanks Eric , I downloaded the latest 2.3 release and it fixed the issues I had. I am closing this issue.
