### ISSUE TITLE
Y Axis squashed before data arrives

### ISSUE THREAD

**Issue by DaneMcGowan** [core-plot/core-plot#375]
I am building a histogram and want the plot area to be viewable before data arrives. I have two arrays of Doubles that will hold my x and y data. Before data arrives I configure them both to hold dummy values.

```
var x_vals = [0.0, 200.0]
var y_als = [0.0, 0.0]
```

The x_vals represent a typical range, but the y vals are set to 0 to ensure the dummy data doesn't appear as part of the histogram. Before data arrives, the x-axis looks fine but the y-axis is squashed. The only value visible is 0.0 and the Y axis title is smushed down to the bottom and cut off:

<img width="488" alt="screen shot 2018-04-11 at 3 52 12 pm" src="https://user-images.githubusercontent.com/18543017/38637178-c36e444e-3da0-11e8-8a4a-90f13e308b19.png">

The cutoff y-title there is not from the image cropping, it is how the graph appears on screen. What I am looking for is to have the following axis configuration (approximately) before the bars appear:

<img width="490" alt="screen shot 2018-04-11 at 3 56 26 pm" src="https://user-images.githubusercontent.com/18543017/38637241-ee7a9b88-3da0-11e8-9b8a-5aeddb1497f0.png">

I have tried adding tick marks and labels and setting the plot area. I am at a loss as to what to do.

**Comment by eskroch** [comment]
I'm assuming you're using `-scaleToFitPlots:` to fit the dummy data, which gives a `yRange` with length zero (0). Initialize the `yRange` of the plot space to something with a non-zero length, e.g., [0.0, 0.2].

**Comment by DaneMcGowan** [comment]
Perfect, this resolved it. Thank you!
