### ISSUE TITLE
How to add Annotation on Y Axis?

### ISSUE THREAD

**Issue by pradipiphone** [core-plot/core-plot#376]
I want to add annotation on y -axis and move it based on y value. I tried with CPTPlotSpaceAnnotation but I don't want to scroll horizontally.I want it move only vertically. Pls see attached screenshot
<img width="487" alt="screen shot 2018-04-12 at 2 35 13 pm" src="https://user-images.githubusercontent.com/38314989/38668067-e367a874-3e60-11e8-843f-7919c10d2d4a.png">

**Comment by eskroch** [comment]
Use a layer annotation instead and use a plot space delegate to monitor changes to the plot space. Adjust the position of the annotation as needed in response to changes to the plot space.

**Comment by eskroch** [comment]
On second thought, it might be easier to stay with the plot space annotation and adjust the x-coordinate as the plot space changes to keep it fixed in one spot.
