### ISSUE TITLE
Unable to build iOS docset on Xcode 9.3

### ISSUE THREAD

**Issue by Kush131** [core-plot/core-plot#378]
Hello,

It appears as of pretty recently Apple has stopped including docsetutil in Xcode (I am getting that from this thread here: https://github.com/tomaz/appledoc/issues/628).

Here is the error I get now when trying to build a docset for iOS:

`/bin/sh: /Applications/Xcode.app/Contents/Developer/usr/bin/docsetutil: No such file or directory
make: *** [docset] Error 127
find: /Users/*/Library/Developer/Shared/Documentation/DocSets/com.CorePlotTouch.Framework.docset/Contents/: Not a directory
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure`

I am not super familiar with docsets - Would there be a way to remove this dependency? Or will downloading an old Xcode be the only path forward? 

Thanks!

**Comment by eskroch** [comment]
I'll remove the docset generation sections of the documentation and release build scripts.

**Comment by Kush131** [comment]
Thanks Eric! Appreciate it!

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
