### ISSUE TITLE
Errors trying to compile Mac framework.

### ISSUE THREAD

**Issue by jandyman** [core-plot/core-plot#382]
I get the following when trying to build the framework with the latest commit (ba05b045) from the master branch:

/Users/Andy/Dropbox/Developer/core_plot/framework/Source/CPTTradingRangePlot.m:1226:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
    CPTNumberArray *yValues = @[[self cachedNumberForField:CPTTradingRangePlotFieldOpen recordIndex:idx],
                                ^
/Users/Andy/Dropbox/Developer/core_plot/framework/Source/CPTTradingRangePlot.m:1227:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
                                [self cachedNumberForField:CPTTradingRangePlotFieldClose recordIndex:idx],
                                ^
/Users/Andy/Dropbox/Developer/core_plot/framework/Source/CPTTradingRangePlot.m:1228:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
                                [self cachedNumberForField:CPTTradingRangePlotFieldHigh recordIndex:idx],
                                ^
/Users/Andy/Dropbox/Developer/core_plot/framework/Source/CPTTradingRangePlot.m:1229:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
                                [self cachedNumberForField:CPTTradingRangePlotFieldLow recordIndex:idx]];
                                ^

**Comment by macserv** [comment]
@eskroch What's the timeline for an actual 2.3 release?

**Comment by eskroch** [comment]
There are a handful of outstanding issues that I’m trying to resolve before finalizing release 2.3. I haven’t had a lot of time to work on it lately. Hopefully, I’ll have it done soon, but no guarantees.

**Comment by eskroch** [comment]
Release 2.3 was released 10 January 2020.
