### ISSUE TITLE
-Weverything causes a flood of "messaging unqualified id" warnings in Xcode 10

### ISSUE THREAD

**Issue by LeoNatan** [core-plot/core-plot#384]
Please disable `-Weverything` or add `-Wno-messaging-id` to the linker flag to disable this behavior.

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.

**Comment by LeoNatan** [comment]
Thank you for the quick fix!

**Comment by hugovanderlei** [comment]
there is no release-2.3 branch

**Comment by LeoNatan** [comment]
https://github.com/core-plot/core-plot/tree/release-2.3

**Comment by hugovanderlei** [comment]
thanks!

**Comment by bikeracer** [comment]
Just tested CorePlot with the new XC 10.2 betas and this warning seems to be now a dead-stop error! Although couldn't find any hints in related XC release notes...
