### ISSUE TITLE
Location of graph title is misplaced on decode

### ISSUE THREAD

**Issue by boisy** [core-plot/core-plot#385]
OS: macOS
Core Plot branch: release-2.3

Issue: I am loading a previously created graph that was encoded in an NSDocument based subclass. Upon reloading, sometimes but not always, the title of the graph is misplaced (see attachment).

This feels like a race condition given its unpredictability.

![screen shot 2018-07-09 at 6 23 19 am](https://user-images.githubusercontent.com/719845/42447834-d2e4ac3e-8340-11e8-8d16-dc34eac94c74.png)

**Comment by eskroch** [comment]
Can you provide more detail about how the graph is being saved and reloaded? Code excerpts would be helpful.

**Comment by boisy** [comment]
Sure. I have a subclass of CPTGraphHostingView declared this way:

@interface WS4PlotView : CPTGraphHostingView <WS4WidgetHostViewDelegate, CALayerDelegate, CPTPlotDataSource>

I then have the initWithCoder/encodeWithCoder methods implemented in that subclass:

- (id)initWithCoder:(NSCoder *)coder;
{
    if (self = [super initWithCoder:coder])
    {
        self.updateInterval = [coder decodeIntegerForKey:@"updateInterval"];
        self.archiveManager = [coder decodeObjectForKey:@"archiveManager"];
        self.from = [coder decodeObjectForKey:@"from"];
        self.to = [coder decodeObjectForKey:@"to"];
        
        _period = [coder decodeObjectForKey:@"period"];
        _selectedTheme = [coder decodeObjectForKey:@"selectedTheme"];
        
        self.property = [coder decodeObjectForKey:@"property"];
        [self setFrame:self.frame];
    }
    
    return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder;
{
    [super encodeWithCoder:aCoder];
    [aCoder encodeInteger:self.updateInterval forKey:@"updateInterval"];
    [aCoder encodeObject:self.archiveManager forKey:@"archiveManager"];
    [aCoder encodeObject:self.from forKey:@"from"];
    [aCoder encodeObject:self.to forKey:@"to"];
    [aCoder encodeObject:self.period forKey:@"period"];
    [aCoder encodeObject:self.property forKey:@"property"];
    [aCoder encodeObject:self.selectedTheme forKey:@"selectedTheme"];
}

Ignoring most of the properties of the WS4PlotView, the salient portion is the call to the super’s initWithCoder and encodeWithCoder, which calls into the CPTGraphHostingView’s implementation of those methods.

I’ll try to pull together a small demo that demonstrates the behavior.
--
Boisy G. Pitre
 <http://www.tee-boy.com/>
confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company. <http://htmlsig.com/www.linkedin.com/boisypitre>

**Comment by boisy** [comment]
Hi,

I've put together a short macOS app (in Swift) that demonstrates the problem. Use CocoaPods to pull CorePlot first, then open the CPT_TITLE_TEST.xcworkspace and build.

When you first run the program, the graph will be created in code with a title of VAX and the title appears correctly.

When you quit the app, the graph is encoded and saved to a file. Re-run the app and the graph will be retrieved from the encoded file and unarchived. Then the title appears at the lower left corner of the graph.

[CPT_TITLE_TEST.zip](https://github.com/core-plot/core-plot/files/2180037/CPT_TITLE_TEST.zip)

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
