### ISSUE TITLE
Refactor `UIGraphicsBeginImageContextWithOptions` usage to utilize `UIGraphicsImageRenderer`

### ISSUE THREAD

**Issue by remypanicker** [core-plot/core-plot#387]
`UIGraphicsImageRenderer` was introduced in iOS 10 and in iOS 12 it will automatically pick the best graphics format; optimizing memory usage when working with images.

https://developer.apple.com/videos/play/wwdc2018/416/ (20:00)

**Comment by eskroch** [comment]
I tried to make this change but the new rendering model is incompatible with some of the Core Graphics rendering commands used by Core Plot.
