### ISSUE TITLE
iOS Xcode 10 - Build errors with carthage

### ISSUE THREAD

**Issue by VicZhang1** [core-plot/core-plot#388]
Hi, 

I am trying to reference core-plot via **carthage** like `github "core-plot/core-plot" ~> 2.2`, when I run `carthage update --platform iOS` command, I get below error:

> Build Failed
> 	Task failed with exit code 65

Looking at build log, I see:

> /Users/VZ/WorkSpace/MyProject/Carthage/Checkouts/core-plot/framework/Source/CPTTradingRangePlot.m:1226:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
>     CPTNumberArray *yValues = @[[self cachedNumberForField:CPTTradingRangePlotFieldOpen recordIndex:idx],
>                                 ^
> /Users/VZ/WorkSpace/MyProject/Carthage/Checkouts/core-plot/framework/Source/CPTTradingRangePlot.m:1227:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
>                                 [self cachedNumberForField:CPTTradingRangePlotFieldClose recordIndex:idx],
>                                 ^
> /Users/VZ/WorkSpace/MyProject/Carthage/Checkouts/core-plot/framework/Source/CPTTradingRangePlot.m:1228:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
>                                 [self cachedNumberForField:CPTTradingRangePlotFieldHigh recordIndex:idx],
>                                 ^
> /Users/VZ/WorkSpace/MyProject/Carthage/Checkouts/core-plot/framework/Source/CPTTradingRangePlot.m:1229:33: error: implicit conversion from nullable pointer 'NSNumber * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id') [-Werror,-Wnullable-to-nonnull-conversion]
>                                 [self cachedNumberForField:CPTTradingRangePlotFieldLow recordIndex:idx]];
>                                 ^
> 5 warnings and 4 errors generated.

Any ideas for this?

Thanks,
-
Vic

**Comment by eskroch** [comment]
Try using the release 2.3 branch. Release 2.2 doesn't work with newer versions of Xcode.

    github "core-plot/core-plot" "release-2.3"

**Comment by benzado** [comment]
I just encountered the same build problem with a Cartfile like

    github "core-plot/core-plot"

With no version specified, Carthage fetches 2.2, which I assume is because that's the [latest of the Releases](https://github.com/core-plot/core-plot/releases) on this repository, even though there is a newer 2.3 branch.

Explicitly naming the "release-2.3" branch (as in the previous comment) works; Carthage fetches and builds the framework successfully.
