### ISSUE TITLE
Support for NSColor in CPTColor

### ISSUE THREAD

**Issue by pascalfribi** [core-plot/core-plot#389]
With macOS Mojave Apple introduces dark mode. It would make sense to have a support for the dynamic colors and Catalog colors that adapt to the dark mode. This would be easy if CPTColor would allow initialisers with NSColor. To support the current NSAppearance and proper color rendering a minimal change would also be needed to CPTLayer and CPTGraph.

I could create a Pull request if you find this worthwhile as well. The changes are quite straightforward.

**Comment by eskroch** [comment]
Please create a pull request. This sounds like a worthwhile update.

**Comment by pascalfribi** [comment]
Done. Needed quite some #if and #pragma to make it work.

**Comment by eskroch** [comment]
Merged pull request #390 on the `release-2.3` branch.

**Comment by pascalfribi** [comment]
Thanks for the merge and also for improving the code to your style. I am not that used to be that backwards compatible as you are with your framework :-)
