### ISSUE TITLE
Crash when trying to return CPTFill with gradient

### ISSUE THREAD

**Issue by IuliAndrisan** [core-plot/core-plot#395]
Hello!
Tried to return CPTFill for legend using the following delegate method:
```objective-c
- (CPTFill *)legend:(CPTLegend *)legend fillForSwatchAtIndex:(NSUInteger)idx forPlot:(CPTPlot *)plot{}
```
If I try it in this way it works:
```objective-c
- (CPTFill *)legend:(CPTLegend *)legend fillForSwatchAtIndex:(NSUInteger)idx forPlot:(CPTPlot *)plot {   
    return [CPTFill fillWithColor:[CPTColor blueColor]];
}
```
but if I try to use it with gradient it crashes
```objective-c
- (CPTFill *)legend:(CPTLegend *)legend fillForSwatchAtIndex:(NSUInteger)idx forPlot:(CPTPlot *)plot {
     return [CPTFill fillWithGradient:[CPTGradient gradientWithBeginningColor:[CPTColor redColor]
                                                                  endingColor:[CPTColor yellowColor]]];
}
```
<img width="867" alt="crash_fillwithgradient" src="https://user-images.githubusercontent.com/20574060/49502793-8b36eb00-f87e-11e8-87cc-528841025c4a.png">

Xcode 10.1
CorePlot version 2.2 
iOS version 12.1

Thank you!

**Comment by eskroch** [comment]
I haven't investigated the crash yet, but one hint to simplify your code is that `CPTColor` has the same color class methods, e.g., `[CPTColor blueColor]` as `UIColor` so you can eliminate the `CGColor` gymnastics when creating colors.

**Comment by IuliAndrisan** [comment]
Thanks! :)

**Comment by IuliAndrisan** [comment]
Small update: the crash does not happen for iOS version 11.4.1.

**Comment by eskroch** [comment]
Unable to reproduce the crash with the latest Core Plot (`release-2.3` branch) and iOS 13.
