### ISSUE TITLE
Retain cycle in CPTPlot.h

### ISSUE THREAD

**Issue by mkubista** [core-plot/core-plot#398]
I have rather large module for printing plots in my project and have a `CPTXYPlotSpace` subclasses in it.
In the `CPTXYPlotSpace` subclass i have an array which references several plots inserted into the plotspace.

I have a problem, that there is a retain cycle between my `CPTXYPlotSpace` subclass and `CPTPlot`

I have found out, that when I change this property in `CPTPlot` to weak, everything is running fine.
But I have no idea, if this change can break the basic behaviour of CorePlot.

```
/// @name Plot Space
/// @{
@property (nonatomic, readwrite, strong, nullable) CPTPlotSpace *plotSpace;
```

**Comment by mkubista** [comment]
This is the memory graph of the leak.

![image](https://user-images.githubusercontent.com/21294149/54201986-4f3fa180-44cf-11e9-80e6-7be90feb7a3a.png)

**Comment by eskroch** [comment]
If that works for you, then do it. You should only have a problem if Core Plot tries to draw the plot after the plot space was nulled out.

I know it's difficult to make an array of weak pointers in Objective-C but that might be a better solution than modifying Core Plot. I saw several suggestions on how to do that after a quick search on https://stackoverflow.com/.

It's hard to offer other solutions without knowing why you need the array of plots or what it's used for. Perhaps the array could be attached to a different object that wouldn't cause a retain cycle. I'm also curious why you need to subclass `CPTXYPlotSpace`. Is it just to track the plots or are you doing other things as well?

**Comment by mkubista** [comment]
> If that works for you, then do it. You should only have a problem if Core Plot tries to draw the plot after the plot space was nulled out.
> 
> I know it's difficult to make an array of weak pointers in Objective-C but that might be a better solution than modifying Core Plot. I saw several suggestions on how to do that after a quick search on https://stackoverflow.com/.
> 
> It's hard to offer other solutions without knowing why you need the array of plots or what it's used for. Perhaps the array could be attached to a different object that wouldn't cause a retain cycle. I'm also curious why you need to subclass `CPTXYPlotSpace`. Is it just to track the plots or are you doing other things as well?

@eskroch 
Subclassing is used because we are using quite complicated logic - custom labeling, multiple synchronized plots, dynamic data loading from remote API. 
May be it could be done another way, but its few years old component which works well and it would be very complicated to rewrite it.

As for the array with weak references. We have some custom classes for this in swift, but when I used it, charts were not plotted - it looks like the reference was lost somewhere.

Array is used to be able to manipulate with plots in realtime - append loaded data, change visualisation in landscape transitions and many more.

**Comment by mkubista** [comment]
Hopefully I have found an other solution :)
