### ISSUE TITLE
Cursor does not adjust over CPTGraphHostingView

### ISSUE THREAD

**Issue by Dirk-** [core-plot/core-plot#399]
I use Core Plot in two macOS apps (first one is old, second one ist new). Each of them has a CPTGraphHostingView where some plots are displayed. I can click, hold and drag to change the visible area.

In the first app, when I hoover over the plot, the cursor changes to an open hand. It also changes to a closed hand when I drag. This is what I want, and this is the behavior of all the sample apps of Core Plot.

In the second app, the cursor always stays the same (arrow).

I was not able to find any difference between my two apps (or the second app and the example apps) that could cause this. Both apps compile with Xcode 10.1 and Core Plot release-2.3 branch.

What should I look for?

**Comment by eskroch** [comment]
Answered on [StackOverflow.com](https://stackoverflow.com/questions/55088598/core-plot-cursor-does-not-adjust-over-cptgraphhostingview/55132474#55132474).
