### ISSUE TITLE
Is git force push being used?

### ISSUE THREAD

**Issue by LeoNatan** [core-plot/core-plot#400]
Hello,

I have core-plot as a git submodule, and from time to time, commits disappear for me on the `release-2.3` branch. Is force push being used? This is really disruptive.

**Comment by eskroch** [comment]
No, once I push a commit to Github, it stays. I'll do a new commit when somethings changes.

**Comment by LeoNatan** [comment]
For some reason, my submodule loses commits or they change somehow. Thanks
