### ISSUE TITLE
Compile error with Xcode 10.2 (10E125) and Core-Plot 2.2

### ISSUE THREAD

**Issue by AlainHsu** [core-plot/core-plot#402]
<img width="1233" alt="Screen Shot 2019-03-28 at 10 38 58 AM" src="https://user-images.githubusercontent.com/13879077/55125779-b737ee00-5145-11e9-9f55-0c995c391fef.png">

**Comment by eskroch** [comment]
You need to use the `release-2.3` branch with Xcode 9.x and 10.x.
