### ISSUE TITLE
Lots of wrong nullability annotations (in initializers)

### ISSUE THREAD

**Issue by hwiesmann** [core-plot/core-plot#403]
Especially initializers use very often the wrong nullability annotation. An example (CPTBarPlot::initWithFrame:):

```
-(nonnull instancetype)initWithFrame:(CGRect)newFrame
{
    if ( (self = [super initWithFrame:newFrame]) ) {
...
    }
    return self;
}
```

The initializer claims that the return value is "nonnull" but internally it checks whether the object is not nil. And it does nothing if the object is nil but returning the nil value.

Of course, this is the normal way how initializers should work but they should not claim "nonnull".

**Comment by eskroch** [comment]
Many Core Plot classes are derived from `CALayer`. Apple's header file is wrapped with `NS_ASSUME_NONNULL_BEGIN` and `NS_ASSUME_NONNULL_END` and Core Plot classes use nullability annotations that match the superclass. It uses the same pattern with certain `NSObject` subclasses just to continue the pattern. In most cases, if you actually get a `nil` result from the initializer, you've got bigger problems.
