### ISSUE TITLE
Inf/NaN data causing infinite loop in `autoGenerateMajorTickLocations`, or, NSAsserts in code?

### ISSUE THREAD

**Issue by demitri** [core-plot/core-plot#404]
I ran into an infinite loop (which took me a while to track down!). It is in `CPTAxis.m`, in `autoGenerateMajorTickLocations`. My data contained `-inf` values; the array began with several of them, has some finite values, and then ended with more.

The infinite loop is this one (line 1121):

```
for ( NSDecimal i = initialIndex; CPTDecimalLessThanOrEqualTo(i, finalIndex); i = CPTDecimalAdd(i, one) ) {
```

In my case, `minLimit` and `initialIndex` are `NaN`, causing the infinite loop. 

I noticed this is very similar to issue #262. I don't know the best way to handle this. I would be ok with adding NSAssert statements to make sure at least `minLimit` and `maxLimit` are finite. I know I should be checking that I am passing good values to Core Plot, but having a statement saying "hey, this is evaluating to `inf`, that's there reason for the infinite loop" or "you're about to go into an infinite loop!" would be very helpful to debug this issue. Alternatively, a counter in the loop could check that it hasn't gone beyond a certain (insane) value since `CPTDecimalLessThanOrEqualTo` and/or `CPTDecimalAdd` can be tripped up. Many ways to deal with this.

Stupid messy scientific data.

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
