### ISSUE TITLE
Deprecations in NSCoderExtensions.m

### ISSUE THREAD

**Issue by bkopinski96** [core-plot/core-plot#406]
CGColorSpaceCopyICCProfile and CGColorSpaceCreateWithICCProfile have been deprecated as of macOS 10.13.

It seems that these can be simply substituted with CGColorSpaceCopyICCData and CGColorSpaceCreateWithICCData, respectively.  

I'm currently working from the release-2.3 branch.

**Comment by eskroch** [comment]
Fixed on the `release-2.3` branch.
