### ISSUE TITLE
How to correctly use reloadData for dynamic plotting?

### ISSUE THREAD

**Issue by bkopinski96** [core-plot/core-plot#407]
So I'm trying to create a bar graph that will dynamically plot data that it receives from another thread, about every 4 seconds or so. Every interval, the thread sends a notification that the view controller implementing the bar graph observes. Once this happens, I append the new value received to the array of values contained in the class (that I want to use as the data source), and then call reloadData on the graph. My understanding is that this call should redraw the graph (or at least draw the new record) instantly. However, nothing seems to happen. Though when I resize the window, the bars appear (and all the labels disappear). Obviously I'm doing something wrong, I've looked at many of the questions on this very same topic and haven't been able to figure out what I'm doing wrong here. 

One thing I did notice is that the numberOfRecordsforplot function gets called when I explicitly call reloadData.  

Also, I'm not trying to update the values that the bars represent, but rather add another bar (record) that will be plotted at the next index, along with its appropriate label.

**Comment by eskroch** [comment]
1. Be sure to call `-reloadData` and all Core Plot methods from the main thread.

2. `-reloadData` will force the graph (or individual plot) to reload all plot data from the datasource and redraw the plot(s). Without knowing more about the structure of your app, I don't know why the labels would be affected. Can you post some code and/or screenshots?

**Comment by bkopinski96** [comment]
(1) fixed the issue. I didn't realize the notification could be observed on any thread, and it must've been getting caught on the background thread I spawned to send me new data. Once I forced the notification to get posted on the main thread queue, everything worked how it was supposed to.

Thank you for your help!
