### ISSUE TITLE
Implicit Conversion errors with Xcode 10.2.1 

### ISSUE THREAD

**Issue by vkrmchowdary** [core-plot/core-plot#408]
I am integrating `core-plot release 2.3` using Carthage into my project but it failed due to implicit conversion errors in `CPTLegend.m`. Please find the error log below

`Carthage/Checkouts/core-plot/framework/Source/CPTLegend.m:589:153: error: implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
            columnPositions[col + 1] = columnPositions[col] + padLeft + width + padRight + (isHorizontalLayout ? theOffset + theSwatchSize.width : 0.0) + theColumnMargin;`

I have also tried building `Core Plot` with Xcode 10.2.1 choosing the device target as `Generic iOS Device` and it gave the same set of errors. 

Any help would be appreciated.

Thanks in Advance.

**Comment by eskroch** [comment]
Others have reported similar problems using Cocoapods, too. It has something to do with the Core Plot `.xcconfig` files not being used by Carthage or Cocoapods builds.

**Comment by vkrmchowdary** [comment]
@eskroch Alright. Is there any alternate way that we can integrate core plot using Carthage?

**Comment by vkrmchowdary** [comment]
I think I found the issue. The issue lies with the 32-bit arch support, I have removed `armv7` from `VALID_ARCHS[sdk=iphoneos*]` and `i386` from `VALID_ARCHS[sdk=appletvsimulator*]` and the Carthage build was successful. So basically, the build was failing for 32-bit arch

**Comment by eskroch** [comment]
This issue was fixed by PR #410.
