### ISSUE TITLE
Xcode 11 build failed: Value Conversion Issue

### ISSUE THREAD

**Issue by AlainHsu** [core-plot/core-plot#412]
![Screen Shot 2019-09-16 at 4 44 31 PM](https://user-images.githubusercontent.com/13879077/64944707-87baa080-d8a1-11e9-8edb-273ef45dd4cb.png)

I am using `core-plot release 2.3`.

**Comment by swainwri** [comment]
For temp fix I tried (NSUInteger)((CGColorRenderingIntent)CGImageGetRenderingIntent(selfCGImage))

in CPTGradient.m also need (NSUInteger)((CPTGradientBlendingMode)self.blendingMode) + (NSUInteger)((CPTGradientType)self.gradientType);

**Comment by eskroch** [comment]
I don't see any build errors for `release-2.3` using the Xcode 11 GM. Can you provide more details about which target you were building and which line(s) triggered the error?

**Comment by swainwri** [comment]
version of release-2.3 I had :

CPTImage.m

-(NSUInteger)hash
{
    // Equal objects must hash the same.
    CGImageRef selfCGImage = self.image;

    return (CGImageGetWidth(selfCGImage) * CGImageGetHeight(selfCGImage) ) +
           CGImageGetBitsPerComponent(selfCGImage) +
           CGImageGetBitsPerPixel(selfCGImage) +
           CGImageGetBytesPerRow(selfCGImage) +
           CGImageGetBitmapInfo(selfCGImage) +
           CGImageGetShouldInterpolate(selfCGImage) +
           CGImageGetRenderingIntent(selfCGImage) * (NSUInteger)self.scale;
}

and 
in CPTGradient.m

-(NSUInteger)hash
{
    // Equal objects must hash the same.
    CGFloat theHash    = CPTFloat(0.0);
    CGFloat multiplier = CPTFloat(256.0);

    CPTGradientElement *curElement = self.elementList;

    if ( curElement ) {
        CPTRGBAColor color = curElement->color;

        theHash    += multiplier * color.red;
        multiplier *= CPTFloat(256.0);
        theHash    += multiplier * color.green;
        multiplier *= CPTFloat(256.0);
        theHash    += multiplier * color.blue;
        multiplier *= CPTFloat(256.0);
        theHash    += multiplier * color.alpha;

        return (NSUInteger)theHash;
    }
    else {
        return self.blendingMode + self.gradientType;
    }
}

hadn’t noticed you had updated 4 months ago

I suppose the original issue writer did the the same

there were a couple of more encodeInts I changed to encodeInteger also
