### ISSUE TITLE
Can't bild demo in Xcode 11

### ISSUE THREAD

**Issue by Marioliniya** [core-plot/core-plot#415]
Can't bild demo in Xcode 11

.../Downloads/core-plot-master/framework/Source/CPTPlotRange.m:136:13: Messaging unqualified id

**Comment by eskroch** [comment]
Make sure you're using the code on the [`release-2.3`](https://github.com/core-plot/core-plot/tree/release-2.3) branch. I just checked all of the example apps and didn't see any compile errors.
