### ISSUE TITLE
CPTAnimation call from a swift CPTPieChart based UIViewController crashes

### ISSUE THREAD

**Issue by swainwri** [core-plot/core-plot#420]
I'm trying to incorporate a PieChart slice animation much like in Plot_Gallery project, in a CPTPieChart based UIViewController. The CPTAnimation call is basically the same as the example but in Swift: 
```swift
@objc func doAnimation(_ sender: Any) {
        if let _currentPieChart = currentPieChart {
            CPTAnimation.animate(_currentPieChart, property: "sliceOffset", from: (currentIndex == offsetIndex ? CGFloat.nan : CGFloat(0.0)), to: (currentIndex == offsetIndex ? CGFloat(0.0) : CGFloat(35.0)), duration: 0.5, animationCurve: .cubicInOut, delegate: self)
            offsetIndex = currentIndex
        }
    }
```
yet crashes in _CPTAnimationCGFloatPeriod.m at
```objective-c
CGFloat CPTCurrentFloatValue(id __nonnull boundObject, SEL __nonnull boundGetter)
{
    NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[boundObject methodSignatureForSelector:boundGetter]];

   \\
   \\
}
```
the selection function in swift:

```swift
    // MARK:  -
    // MARK: CPTAnimation Accessors

    @objc public func setSliceOffset(_ newOffset: CGFloat) {
        if newOffset != _sliceOffset {
            _sliceOffset = newOffset
            hostingView.hostedGraph?.reloadData()
            if newOffset == CGFloat(0.0) {
                offsetIndex = NSNotFound
            }
        }
    }

    @objc func getSliceOffset() -> CGFloat {
        return _sliceOffset
    }
```

`[boundObject methodSignatureForSelector:boundGetter]` is nil and hence the crash.

Coreplot is included as a framework to the project.

How do I get the objective c code to see the swift selection "setSliceOffset:"?
Would I have to incorporate Coreplot as a static embedded library i.e. coreplot.a and include my project  `#import "MyProject-swift.h"` into the coreplot.h?

**Comment by eskroch** [comment]
In the example referenced in the question, `sliceOffset` is a property of the controller object, not the plot.
```objective-c
@property (nonatomic, readwrite) CGFloat sliceOffset;
```
The first parameter to `animate()` should be `self`, not the plot.

**Comment by swainwri** [comment]
Apologies for wasting your time, although I had that code for  couple of years and just revisited it, don’t think I would have noticed the error.

Merry Christmas and happy New Year
