### ISSUE TITLE
CTPieChart with start angle 0 and no end angle does not plot single value segment

### ISSUE THREAD

**Issue by nikolayds** [core-plot/core-plot#421]
using pod 'CorePlot'

Hi, 
I have a CTPieChart with only one segment (slice). The CTPieChart plots the Labels and Data Values correctly, but does not plot the Slice at all. 

Workaround -> set startAngle to 1 instead of 0

Possible fix:
I have debugged the code and issue seems to be in the following method 
CPTPieChart
-(CGFloat)radiansForPieSliceValue:(CGFloat)pieSliceValue
line: 
 `return fmod( angle, CPTFloat(2.0 * M_PI) ); `

For a single value -> angle is exactly the negative (for Clockwise) value - (2.0 * M_PI) and fmod returns '0'. Then the plot finishing angle is 0, like the plot starting angle. 

Fix could be something like:

//Testing fix: when angle is equal to 2 * M_PI, return angle. 
`return (ABS(angle) == CPTFloat(2.0 * M_PI)) ? angle : fmod( angle, CPTFloat(2.0 * M_PI) );
`

Before:
![IMG_0010](https://user-images.githubusercontent.com/8965125/72846022-9a305680-3c54-11ea-83bb-6cad8d813708.png)

After:
![IMG_0009](https://user-images.githubusercontent.com/8965125/72845490-95b76e00-3c53-11ea-9e44-2bd3c6e88e73.png)

**Comment by hwiesmann** [comment]
Yeah, this is a bug in CorePlot. Your fix is not correct as the angle itself is correctly calculated. Only CGPathAddArc does not to like it.  Change in CPTPieChart.m the lines within addSliceToPath:CenterPoint:startingAngle:finishingAngle:width:

`
CGPathAddArc(slicePath, NULL, center.x, center.y, outerRadius, startingAngle, startingAngle + CPTFloat(2.0 * M_PI), direction);
CGPathAddArc(slicePath, NULL, center.x, center.y, innerRadius, startingAngle + CPTFloat(2.0 * M_PI), startingAngle, !direction);
`
to
`CGPathAddArc(slicePath, NULL, center.x, center.y, outerRadius, 0.0, CPTFloat(2.0 * M_PI), NO);
CGPathAddArc(slicePath, NULL, center.x, center.y, innerRadius, CPTFloat(2.0 * M_PI), 0.0, YES);
`
and everything works fine again.

PS: For complete circles all the calculations in these two original lines are superfluous anyway.

**Comment by eskroch** [comment]
Fixed on the `release-2.4` branch.
