### ISSUE TITLE
Slice fill colors not displayed on Pie Chart after update to v.2.3.

### ISSUE THREAD

**Issue by sergiughiran** [core-plot/core-plot#423]
Updating the pod to version 2.3 caused the slice fill colors to not be displayed anymore in the pie chart. I can confirm that no change was made on my side, and just downgrading the pod to version 2.2 fixes the problem. I use the `sliceFillForPieChart(...)` method from the delegate in order to set these colors like this:

```
- (CPTFill *)sliceFillForPieChart:(CPTPieChart *)pieChart recordIndex:(NSUInteger)idx {
    if (self.segmentsColors != nil) {
        return [CPTFill fillWithColor:[CPTColor colorWithCGColor:((UIColor*)[self.segmentsColors objectAtIndex:idx]).CGColor]];
    }

    switch (idx) {
        case GCMGaugeSectionRedFirsHalf:
        case GCMGaugeSectionRedSecondHalf:
            return [CPTFill fillWithColor:[CPTColor colorWithCGColor:[UIColor ruby2].CGColor]];
        case GCMGaugeSectionYellow:
            return [CPTFill fillWithColor:[CPTColor colorWithCGColor:[UIColor mango2].CGColor]];
        case GCMGaugeSectionGreen:
            return [CPTFill fillWithColor:[CPTColor colorWithCGColor:[UIColor swagger1].CGColor]];
        case GCMGaugeSectionBlue:
            return [CPTFill fillWithColor:[CPTColor colorWithCGColor:[UIColor delta1].CGColor]];
        case GCMGaugeSectionPurple:
            return [CPTFill fillWithColor:[CPTColor colorWithCGColor:[UIColor berry2].CGColor]];
        default:
            return [CPTFill fillWithColor:[CPTColor colorWithCGColor:[UIColor berry2].CGColor]];
    }
}
```
The above results in the slices being black or clear (the background is black as well).

I saw in the release description that some changes were made to colors handling, could you tell me if those could have affected the slice color logic?

Thanks!

**Comment by eskroch** [comment]
Try it without the `CGColor` dance, e.g., `[CPTColor colorWithUIColor:[UIColor ruby2]]`.

**Comment by sergiughiran** [comment]
@eskroch Tried it, but the result is the same, none of the colors show up in the pie chart. Were there any changes made in chart setup or color setting in 2.3?

**Comment by eskroch** [comment]
Most of the changes to `CPTColor` in release 2.3 were new properties and methods related to handling native colors (`NSColor` and `UIColor`) directly. No changes to the pie chart, either.

Does your slice fill method and other datasource methods get called? Is the datasource object being released anywhere? I had that problem in some of the example apps in newer versions where the datasource would go away since the plot only holds a weak reference to it and something changed in Xcode or the underlying system.

**Comment by sergiughiran** [comment]
@eskroch I managed to fix the issue by explicitly forcing the graph to be setup in the main dispatch queue. This was not necessary in v2.2 .

**Comment by eskroch** [comment]
Maybe you were just lucky, then. Core Plot is built on Core Animation which has always required every interaction to be done on the main thread.
