### ISSUE TITLE
Coreplot: Changing the zPosition of an individual element in a CPTBarPlot

### ISSUE THREAD

**Issue by swainwri** [core-plot/core-plot#425]
As suggested in order to create this zPosition effect, I inserted a copy of the second Barchart to front of the graph.allPlots() array and added it's identifier the suffix of "in front".

``` swift
func number(for plot: CPTPlot, field fieldEnum: UInt, record idx: UInt) -> Any? {
        var num: Any? = nil
        
        if thisplot.chartType == SWBarChartTypes.simple.rawValue && plots.count > 1 {
            var index: Int = barcharts.count
            for i in 0..<plotDetails.count {
                let svycell = plotDetails[i]
                if (plot.identifier as! String).hasPrefix(svycell.identifier) && svycell.show {
                    index = i
                    break
                }
            }
            if index < barcharts.count {
                let svycell = plotDetails[index]
                let allplots = graph.allPlots()
                let middleIndex = plots.count / 2
                let indices = allplots.indices.filter({
                    (allplots[$0].identifier as! String).hasPrefix(svycell.identifier)
                })
                if indices.count > 1 {
                    let dataForPlot = dataForPlots[indices[1] - middleIndex]
                    if fieldEnum == CPTBarPlotField.barTip.rawValue {
                        let yvalue = dataForPlot[Int(idx)]["y"] as! Double
                        var controlYDataPointForPlot = dataForPlots[0][Int(idx)]["y"] as! Double
                        if let axisSet = graph.axisSet,
                            let axes = axisSet.axes {
                            let yDataRange = axes[1].visibleRange!.lengthDouble
                            var yRange: Double = yDataRange
                            if let axisIndex = axes.firstIndex(where: { $0.plotSpace === plot.plotSpace && $0.coordinate == CPTCoordinate.Y }) {
                                yRange = axes[axisIndex].visibleRange!.lengthDouble
                            }
                            if yRange != yDataRange {
                                controlYDataPointForPlot = controlYDataPointForPlot / yRange * yDataRange
                            }
                        }
                        if ((plot.identifier as! String).hasSuffix(" in front") && yvalue <= controlYDataPointForPlot) || (!(plot.identifier as! String).hasSuffix(" in front") && yvalue > controlYDataPointForPlot) {
                            num = NSNumber(value: yvalue)
                        }
                        else {
                            num = nil //NSNumber(0)
                        }
                        print("Plot: \(plot.identifier as! String), index: \(idx), yValue: \(num == nil ? 0 : num as! Double)")
                    }
                    else {
                        num = NSNumber(value: dataForPlot[Int(idx)]["x"] as! Double)
                    }
                }
                else {
                    dataForPlot = dataForPlots[0]
                    if fieldEnum == CPTBarPlotField.barTip.rawValue {
                        num = NSNumber(value: dataForPlot[Int(idx)]["y"] as! Double)
                        print("Plot: \(plot.identifier as! String), index: \(idx), yValue: \(num == nil ? 0 : num as! Double)")
                    }
                    else {
                        num = NSNumber(value: dataForPlot[Int(idx)]["x"] as! Double)
                    }
                }
            }
            else {
                num = nil
            }
        }
        else {
            var index: Int = barcharts.count
            for i in 0..<plotDetails.count {
                let svycell = plotDetails[i]
                if (plot.identifier as! String) == svycell.identifier && svycell.show {
                    index = i
                    break
                }
            }
            if index < barcharts.count {
                dataForPlot = dataForPlots[index]
                if fieldEnum == CPTBarPlotField.barLocation.rawValue {
    //                if let category = dataForPlot[Int(idx)]["category"] as? String {
    //                    num = category
    //                }
    //                else {
                        num = NSNumber(value: dataForPlot[Int(idx)]["x"] as! Double)
    //                }
                }
                else {
                    var offset: Double = 0
                    if (plot as! CPTBarPlot).barBasesVary {
                        for k in 0..<index {
                            let data = dataForPlots[k]
                            offset += (data[Int(idx)]["y"] as! Double)
                        }
                    }
                    if fieldEnum == CPTBarPlotField.barTip.rawValue {
                        num = NSNumber(value: (dataForPlot[Int(idx)]["y"] as! Double) + offset)
                    }
                    else {
                        num = NSNumber(value: offset)
                    }
                }
            }
        }
        return num
    }
```

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-03 at 13 12 52](https://user-images.githubusercontent.com/20568264/75748576-69166c00-5d52-11ea-8646-dd5f3f0ee91f.png)
Plot: 1: Nationality in front, index: 0, yValue: 60.0
Plot: 1: Nationality in front, index: 1, yValue: 57.5
Plot: 1: Nationality in front, index: 2, yValue: 62.5
Plot: 1: Nationality in front, index: 3, yValue: 42.5
Plot: 0: Subjects, index: 0, yValue: 70.0
Plot: 0: Subjects, index: 1, yValue: 65.0
Plot: 0: Subjects, index: 2, yValue: 67.5
Plot: 0: Subjects, index: 3, yValue: 45.0
Plot: 1: Nationality, index: 0, yValue: 0.0
Plot: 1: Nationality, index: 1, yValue: 0.0
Plot: 1: Nationality, index: 2, yValue: 0.0
Plot: 1: Nationality, index: 3, yValue: 0.0

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-03 at 13 13 03](https://user-images.githubusercontent.com/20568264/75748596-77fd1e80-5d52-11ea-9782-95c57419bf97.png)
Plot: 1: Nationality in front, index: 0, yValue: 60.0
Plot: 1: Nationality in front, index: 1, yValue: 57.5
Plot: 1: Nationality in front, index: 2, yValue: 62.5
Plot: 1: Nationality in front, index: 3, yValue: 45.0
Plot: 0: Subjects, index: 0, yValue: 70.0
Plot: 0: Subjects, index: 1, yValue: 65.0
Plot: 0: Subjects, index: 2, yValue: 67.5
Plot: 0: Subjects, index: 3, yValue: 45.0
Plot: 1: Nationality, index: 0, yValue: 0.0
Plot: 1: Nationality, index: 1, yValue: 0.0
Plot: 1: Nationality, index: 2, yValue: 0.0
Plot: 1: Nationality, index: 3, yValue: 0.0

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-03-03 at 13 13 11](https://user-images.githubusercontent.com/20568264/75748614-83504a00-5d52-11ea-8db5-8cac2dcb29b9.png)
Plot: 1: Nationality in front, index: 0, yValue: 60.0
Plot: 1: Nationality in front, index: 1, yValue: 57.5
Plot: 1: Nationality in front, index: 2, yValue: 62.5
Plot: 1: Nationality in front, index: 3, yValue: 0.0
Plot: 0: Subjects, index: 0, yValue: 70.0
Plot: 0: Subjects, index: 1, yValue: 65.0
Plot: 0: Subjects, index: 2, yValue: 67.5
Plot: 0: Subjects, index: 3, yValue: 45.0
Plot: 1: Nationality, index: 0, yValue: 0.0
Plot: 1: Nationality, index: 1, yValue: 0.0
Plot: 1: Nationality, index: 2, yValue: 0.0
Plot: 1: Nationality, index: 3, yValue: 47.5

I had to change the opacity to 0.5 for "plot 1" and "plot 1 in front", opacity of 1.0 just blocks out the plot 0.

What could I be doing wrong?

This Barchart is interactive, I find I have to reload all elements of the barplot, as calling the range version causes updates in reverse order. ie moving element 3 will cause update in element 0

``` swift
internal func plotSpace(_ space: CPTPlotSpace, shouldHandlePointingDeviceDraggedEvent event: UIEvent, at point: CGPoint) -> Bool {
        if symbolDraggable {
            if let xySpace = plotSpace {
                let detail = PLOT[barChartBeingDraggedIndex]
                let plotPoint: [Double] = [0.0, 0.0]
                let ptrPlotPoint: UnsafeMutablePointer<Double> = UnsafeMutablePointer(mutating: plotPoint)
                xySpace.doublePrecisionPlotPoint(ptrPlotPoint, numberOfCoordinates: 2, forPlotAreaViewPoint: point)
                
                var data = dataForPlots[barChartBeingDraggedIndex]
                let dictData = data[barChartBeingDraggedDataIndex]
                var newDict = dictData
                var resolutionedValue: Double
                if thisplot.chartOrientation == SWBarChartOrientations.vertical {
                    let axis = detail[kYAxisKey] as! CPTXYAxis
                    let minorTickInterval = axis.majorIntervalLength!.doubleValue / Double(axis.minorTicksPerInterval)
                    resolutionedValue = (plotPoint[CPTCoordinate.Y.rawValue] / minorTickInterval).rounded(.toNearestOrAwayFromZero) * minorTickInterval
                }
                else {
                    let axis = detail[kXAxisKey] as! CPTXYAxis
                    let minorTickInterval = axis.majorIntervalLength!.doubleValue / Double(axis.minorTicksPerInterval)
                    resolutionedValue = (plotPoint[CPTCoordinate.X.rawValue] / minorTickInterval).rounded(.toNearestOrAwayFromZero) * minorTickInterval
                    
                }
                if thisplot.chartType == SWBarChartTypes.stacked.rawValue {
                    newDict["y"] = resolutionedValue + StackedOffset
                }
                else {
                    newDict["y"] = resolutionedValue
                }
                data[barChartBeingDraggedDataIndex] = newDict
                dataForPlots[barChartBeingDraggedIndex] = data
                let barPlot: CPTBarPlot = barcharts[barChartBeingDraggedIndex]
                //let range = NSMakeRange(barChartBeingDraggedDataIndex, 1)
                if thisplot.chartType == SWBarChartTypes.stacked.rawValue {
                    for barPlot in barcharts {
                        barPlot.reloadData()//inIndexRange: range)
                    }
                }
                else if thisplot.chartType == SWBarChartTypes.simple.rawValue && plots.count > 1 {
                    var index: Int = 0
                    for i in 0..<plotDetails.count {
                        let svycell = plotDetails[i]
                        if (barPlot.identifier as! String).hasPrefix(svycell.identifier) && svycell.show {
                            index = i
                            break
                        }
                    }
                    if index < barcharts.count {
    //                    let svycell = plotDetails[index]
                        let allplots = graph.allPlots() as! [CPTBarPlot]
                        //let middleIndex = allplots.count / 2
    //                    let indices = allplots.indices.filter({
    //                        (allplots[$0].identifier as! String).hasPrefix(svycell.identifier)
    //                        })
                        //indices.insert(middleIndex, at: <#T##Int#>)
                        //for index in indices {
                        print("Movement")
                        for index in 0..<allplots.count {
                            allplots[index].reloadData()//inIndexRange: range)
                        }
                        //allplots[middleIndex].reloadData()
                    }
                }
                else {
                    barPlot.reloadData()//inIndexRange: range)
                }
                originalSymbolPoint = point
                hasSymbolBeenDragged = true
            }
            
        }
        .....
        
        
        return true
    }
```

**Comment by eskroch** [comment]
I'm having trouble understanding the question. Is the issue with the layering of the plots and the desired appearance, or more with the interactive features?

**Comment by swainwri** [comment]
Check out the graphics, at index 3 I want the blue element to show on top of the red element, when the red element has a larger Y value. If I use opacity of 1.0 on red, the blue element will not be seen.
The individual graphics come with a print log of the Y values for each bar plot, as I increase the y Value of the red element. It was suggested that the z-position of the bar plots in the graphics.allPlots(), is determined by its location in this array, viz index 0 will have a higher z-position than index 1 and so on. hoover this doesn’t seem to be the case.

The interactive part was simply to point out reloadDataAtRange might have a bug, as if I interact on element 3, the element then draws on top of element 0. element 1 on 2, element 2 on 1, element 0 on 3.
perhaps it should be in a separate issue.

**Comment by eskroch** [comment]
It's not clear why you need two nationality plots. Don't you always want the blue subject plot in front?

You have the layer order backwards—the plot with the lowest index is on the bottom and the highest index is in front.

For the index issue, double-check your datasource and make sure it is using the index parameter to look up the correct data values each time it's called.

**Comment by swainwri** [comment]
> It's not clear why you need two nationality plots. Don't you always want the blue subject plot in front?
> 
This got me thinking, so I decided just use Subjects as Plot 0 & Nationality as Plot 1, get rid of my in front copy.  I  made the barwidth of 
the Plot 0 the widest, and subsequent barwidths decreased….this worked as I want. With barwidth from Plot 0 increasing, Plot 0 is overlayed with Plot 1 if Y value is larger.
> You have the layer order backwards—the plot with the lowest index is on the bottom and the highest index is in front.
> 
My error
> For the index issue, double-check your datasource and make sure it is using the index parameter to look up the correct data values each time it's called.
> 
No I checked that on a range call to func number(for plot: CPTPlot, field fieldEnum: UInt, record idx: UInt) -> Any? an idx for fieldEnum == CPTBarPlotField.barLocation.rawValue generates an NSNumber of that index.

**Comment by eskroch** [comment]
I'm going to close this issue since the zPosition issue is resolved. If you're still having problems with `reloadDataInIndexRange:`, please open a new issue with more details about that specific problem.
