### ISSUE TITLE
CPTGraph Dealloc called as soon as initWithFrame is called.

### ISSUE THREAD

**Issue by SwiftKayAndroid** [core-plot/core-plot#428]
I don't even get an actual crash for this. I call 
`self = [[DanaGraph alloc] initWithFrame:frame];`

and the application crashes stating EXC_BAD_ACCESS from CPTGraph dealloc. A breakpoint immediately after the line of code above doesn't get hit so somewhere within the initWithFrame function the app crashes. 

No stacktrace because its never logged out, just hangs forever with above access message.
<img width="1126" alt="Screen Shot 2020-04-14 at 3 36 09 PM" src="https://user-images.githubusercontent.com/14276643/79266617-d9420280-7e65-11ea-981e-51c62ab47406.png">

DanaGraph extends CPTXYGraph

**Comment by koenvanderdrift** [comment]
Error message in the right bottom panel suggests you have an autolayout issue.

**Comment by SwiftKayAndroid** [comment]
The constraint issue isn't what is causing the crash. That is logged out prior to the action taken to cause the crash.

**Comment by SwiftKayAndroid** [comment]
@eskroch can this be reopened as the issue is not resolved.

**Comment by eskroch** [comment]
I don't know why `dealloc` is getting called, but your initialization method should include:

    self = [super initWithFrame:newFrame];

since it's a subclass.

If this doesn't solve the problem, please post your code here. The stack trace doesn't tell the whole story.
