### ISSUE TITLE
Y-axis of CPTScatterPlot not showing

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#430]
The y-axis of a `CPTScatterPlot` I am implementing represents 0-100 %. The plot shows up as expected, but I am not seeing the y-axis, no line, no labels, no tickmarks, no title.

Below is the code for my y-axis:
```
let axisSet = graph?.axisSet // graph is a property of the VC
if let yAxis = axisSet?.axis(for: CPTCoordinate.Y, at: 0) {
   yAxis.labelingPolicy = .automatic
   yAxis.labelOffset = CGFloat(0)
   yAxis.title = "%"
   yAxis.titleOffset = CGFloat(25)
}
```
And for the plotRange:
```
plotSpace.yRange = CPTPlotRange(locationDecimal: CPTDecimalFromCGFloat(0), lengthDecimal: CPTDecimalFromCGFloat(100))
plotSpace.globalYRange = CPTPlotRange(locationDecimal: CPTDecimalFromCGFloat(0), lengthDecimal: CPTDecimalFromCGFloat(100))
```
I do the same for the x-axis, and that one shows up just fine.

What am I missing here?

**Comment by eskroch** [comment]
How are you positioning the y-axis? The default `orthogonalPosition` is zero (0) so if that's outside the `xRange` on the plot space, it will be hidden. You can change the `orthogonalPosition` or use the `axisConstraints` to lock it in position so it doesn't move outside the visible plot area.

**Comment by koenvanderdrift** [comment]
Setting `axisConstraints` did the trick. I did have to cast the axis as `CPTXYAxis`, otherwise the compiler didn't know about `axisConstraints`.
