### ISSUE TITLE
CPTNumberArray in Swift

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#431]
Trying to convert the DropPlot zooming code to Swift and I am stuck at the anchorPoint part. In Objective-C it looks like:

```
double start[2];
[self.graph.defaultPlotSpace doublePrecisionPlotPoint:start numberOfCoordinates:2 forPlotAreaViewPoint:dragStartInPlotArea];
CPTNumberArray *anchorPoint = @[@(start[CPTCoordinateX]),
                                            @(start[CPTCoordinateY])];
```

For the first two lines I have:

```
var start = [Double(2)]
space.doublePrecisionPlotPoint(&start, numberOfCoordinates: 2, forPlotAreaViewPoint: dragStartInPlotArea)
```

But I get an `Use of undeclared type 'CPTNumberArray'` error in Swift why I try to declare the anchorPoint.  How can I do this in Swift?

I'm on release 2.3, Swift 4.2 and Xcode 10.1.

**Comment by eskroch** [comment]
The typedef gets lost in the Swift translation. It's just an array of `NSNumber` objects. This is what I came up with for that line:

    let anchorPoint = start.map{$0 as NSNumber}

**Comment by koenvanderdrift** [comment]
Hmm, that gives me an `*** Assertion failure in -[CPTXYPlotSpace plotAreaViewPointForPlotPoint:numberOfCoordinates:]` error.

After some more trial and error, this seems to work: `let anchorPoint = [start.first, start.last] as? [NSNumber]`.

**Comment by koenvanderdrift** [comment]
Ah, found the issue. I should have used `var start = [Double(), Double()]`, not `var start = [Double(2)]`.
