### ISSUE TITLE
ARM support for MacOS ?

### ISSUE THREAD

**Issue by bendermh** [core-plot/core-plot#434]
Framework target is only enabled for intel based Macs. First test of universal apps are not compiling because CorePlot has not ARM target for Mac version.

**Comment by eskroch** [comment]
You should be able to build the Mac version of Core Plot for ARM using the `release-2.4` branch. Build the "Universal XCFramework" target to create an XCFramework if you don't want to build Core Plot from source every time.

**Comment by bendermh** [comment]
Thank you very much, I test with 2.4 branch and ARM compiling is available for macOS for both Intel and Apple Silicon architectures, also I was able to compile my app with Core Plot 2.4 in "any mac" target with no errors.

Let me use this opportunity to congratulate you about your huge framework. Thank you very much for all.
