### ISSUE TITLE
core-plot in swift

### ISSUE THREAD

**Issue by thierryH91200** [core-plot/core-plot#438]
core-plot in swift

it is not a question but an information

https://github.com/thierryH91200/corePlot-SwIft

I got into something crazy
convert core plot in swift

I started at the beginning of December

there are a lot of things lost and others that are going well

Nota bene: I don't know if I'll get there but I continue

do you have an example of a swift demo for the piechart or bar chart

**Comment by eskroch** [comment]
The iPhone version of the *CPTTestApp* example app is written in Swift and includes a scatter plot, bar chart, and pie chart.
