### ISSUE TITLE
scaleToFitEntirePlots / scaleToFitPlots

### ISSUE THREAD

**Issue by thierryH91200** [core-plot/core-plot#439]
in class CPTXYPlotSpace 
func scaleToFitEntirePlots and func scaleToFitPlots 

it is the same thing 
the same code 

it is just a question

**Comment by eskroch** [comment]
They're not exactly the same. `-scaleToFitPlots:` uses `-plotRangeForCoordinate:` to compute the plot ranges while `-scaleToFitEntirePlots:` uses `-plotRangeEnclosingCoordinate:`. This means `-scaleToFitPlots:` will always only fit the plot data, while `-scaleToFitEntirePlots:` will expand the computed ranges to encompass parts of the plot that extend beyond those ranges. For example, a scatterplot with a curved line may curve beyond the minimum or maximum data value. Scaling to the entire plot ensure the whole line is still visible.
