### ISSUE TITLE
Can I draw AGP graph use core-plot 

### ISSUE THREAD

**Issue by result0924** [core-plot/core-plot#444]
The graph is like this
<img width="207" alt="截圖 2021-04-20 下午2 45 14" src="https://user-images.githubusercontent.com/822363/115350040-29754280-a1e7-11eb-93a8-569c48bd1225.png">
http://www.agpreport.org/agp/about

**Comment by eskroch** [comment]
Core Plot cannot fill between two scatter plots right now. Depending on the format, you may be able to simulate the appearance using several plots overlaid on each other. See issue #99 for one idea on how to do that.

**Comment by result0924** [comment]
got it. thanks for your reply.
