### ISSUE TITLE
For architecture arm64

### ISSUE THREAD

**Issue by SuCong** [core-plot/core-plot#449]
In libcurl-ios-dist/lib/libcurl.a(libcurl_la-file.o), building for iOS Simulator, but linking in object file built for iOS, file 'libcurl-ios-dist/lib/libcurl.a' for architecture arm64

Xcode:12.5.1
Simulator: 14.5

Any help would be appreciated :)
Thanks in advance

**Comment by eskroch** [comment]
Duplicate of #448
