### ISSUE TITLE
Xcode 12.5.1 build issue

### ISSUE THREAD

**Issue by kevint727** [core-plot/core-plot#450]
Get the following error when trying to build the example project. 

`incompatible operand types ('Class' and 'NSNull * _Nonnull') [-Werror]`

for the following line of code 

`CPTAnimationValueClassKey: valueClass ? valueClass : [NSNull null]`

Which is online 339 in CPTAnimation.m file

I do not seem to be the only one experiencing this based on some quick googling but seems to still be an issue in this project. Thanks

**Comment by ddaddy** [comment]
https://github.com/core-plot/core-plot/issues/446

**Comment by eskroch** [comment]
Duplicate of issue #446.
