### ISSUE TITLE
Can use different color in bar

### ISSUE THREAD

**Issue by result0924** [core-plot/core-plot#451]
For example

![ZxvWe](https://user-images.githubusercontent.com/822363/131098259-49e773db-70fc-4c88-9981-24c19f05d8d5.png)

have three color in one bar

My solution is add three CPTBarPlot to show three color, but i don't know have other good idea

thanks

**Comment by eskroch** [comment]
You'll need three bar plots to do this. If you want them to look like one bar, don't round the corners (`barCornerRadius = 0.0`) on the blue and green ones. If you want to use partially-transparent fill colors, set `barBasesVary` on the green and red plots and have the datasource provide base values for each bar that correspond to the top of the bar below. This will eliminate the overlap between the bars.

**Comment by result0924** [comment]
got it. thanks for your reply

**Comment by result0924** [comment]
I have another question.
Can I set more than one border color in one CPTBarPlot

Example 
white border color in January
red border color in february
blue border color in march

i only think solution is use three CPTBarPlot to do this

**Comment by eskroch** [comment]
Implement one of the `- barLineStylesForBarPlot:recordIndexRange:` or `- barLineStyleForBarPlot:recordIndex:` methods in your datasource. See the [`<CPTBarPlotDataSource>`  Protocol Reference](https://core-plot.github.io/iOS/protocol_c_p_t_bar_plot_data_source-p.html) for details.

**Comment by result0924** [comment]
got it. thanks for your reply.
