### ISSUE TITLE
Is CorePlot still working for Xcode 13?

### ISSUE THREAD

**Issue by timclei** [core-plot/core-plot#461]
I was wondering if CorePlot is still maintained? I tried to recompile an iPhone App I wrote previously with the latest CorePlot on Xcode 13. It seems like I cannot even get the framework compiled and give me the following error. 

CPTAnimationValueClassKey: valueClass ? valueClass : [NSNull null],

ncompatible operand types ('Class' and 'NSNull * _Nonnull')

for the CPTAnimation.m

**Comment by altimac** [comment]
I definitely can use CorePlot 2.4 from my iOS project (Xcode  13.2.1)

**Comment by gilcel** [comment]
This bug was fixed here: https://github.com/core-plot/core-plot/commit/b4cf7a7b468c9601e2d4ae9f3a355ee26269978d
