### ISSUE TITLE
Class missing issue 

### ISSUE THREAD

**Issue by arunmahask** [core-plot/core-plot#463]
-(nullable id)debugQuickLookObject
{
    const CGFloat screenScale = 1.0;

    CGSize layerSize = [self layerSizeForScale:screenScale];

    CGRect rect = CGRectMake(0.0, 0.0, layerSize.width, layerSize.height);

    **return CPTQuickLookImage(rect, ^(CGContextRef context, CGFloat scale, CGRect bounds)**
    {
        CGPoint symbolAnchor = self.anchorPoint;

        self.anchorPoint = CPTPointMake(0.5, 0.5);

        [self renderAsVectorInContext:context atPoint:CGPointMake(CGRectGetMidX(bounds), CGRectGetMidY(bounds)) scale:scale];

        self.anchorPoint = symbolAnchor;
    });
}

error messages:

Implicit declaration of function 'CPTQuickLookImage' is invalid in C99
Incompatible integer to pointer conversion returning 'int' from a function with result type 'id _Nullable'

Please explain about the CPTQuickLookImage class not available in side the framework/source/ path

**Comment by eskroch** [comment]
The `CPTQuickLookImage()` function is defined in the platform-specific functions file. The compiler can't find the right header file.

What version of Core Plot are you using? How is it imported in your project (dependent build, dependency manager, Swift PM, etc.)?

**Comment by arunmahask** [comment]
i am using core plot version 2.3.

i have imported by using pod. i am using this version for objective C project, not swift project.

now i am having issue, i.e "ld: framework not found CorePlot
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

When i am trying to archive the project to upload in testflight.

**Comment by eskroch** [comment]
This should be fixed on the `release-2.4` branch. Let me know if anyone is still seeing this issue with the latest code.
