### ISSUE TITLE
How to associate a plot with a specific plot space

### ISSUE THREAD

**Issue by kkaiser41** [core-plot/core-plot#464]
I have a graph with two CPTScatter plots, this graph also has two y axis, and two plot spaces. The problem is that it seems like no matter what I do both line plots are associated with the default plot space. I have assigned the second CPTScatter plot to the second plot space like this.

linePlot2.plotSpace = plotSpace2

I get both y axis to display exactly how I want it just seems I am not connecting the plotspace to the plot properly.
Is this the correct way?

**Comment by eskroch** [comment]
Call `-setNeedsDisplay` on the plot after setting the plot space. If that works, it's a Core Plot bug and we'll fix the oversight.

You can also use `-addPlot:toPlotSpace:` to add the plot to the graph and assign the right plot space from the start.

**Comment by kkaiser41** [comment]
Thanks for responding back. Your suggestion did not solve the problem. However after some more debug I don't think the problem is in core plot. I am doing this in SwiftUI and I think I am making a mistake there.
