### ISSUE TITLE
Xcode 14 giving error about `+load` in theme classes

### ISSUE THREAD

**Issue by drewmccormack** [core-plot/core-plot#465]
Seems Xcode 14 (beta) is more strict about using the `load` class method. It gives an error:

    '+load' is called at app startup and can increase launch time; consider using '+initialize' instead

Not clear why this is an error, not a warning. I suspect that is due to build settings in Core Plot.

**Comment by msimms** [comment]
There doesn't appear to be any adverse consequences in change `load` to `initialize`. Looks like it appears in just 5 different places, so I created a pull request if anyone wants to go that route, instead of just suppressing the error.

**Comment by eskroch** [comment]
+initialize is only called if you use the class in some way. I found a way to enumerate the themes without using +load to register the theme classes. Fixed on the `release-2.4` branch. I also fixed the plot item enumeration in the *Plot Gallery* example app.
