### ISSUE TITLE
Coreplot macOS 10.13+ CGColorSpaceCopyICCProfile() deprecated issue

### ISSUE THREAD

**Issue by gilcel** [core-plot/core-plot#472]
Hi,

I tried to compile an old project with Coreplot Release 2.3 on macOS Monterey 12.6.1 and Xcode 14.1.

Aside a few issues (+load to replace with +initialize) I couldn't find how to fix the error:
`'CGColorSpaceCopyICCProfile()' is deprecated: first deprecated in macOS 10.13 - No longer supported`

Does someone know how to replace this ?

Thanks and cheers

**Comment by eskroch** [comment]
That release is woefully out of date at this point. Use the code on the `release-2.4` branch.

**Comment by gilcel** [comment]
Ah yes thanks! Didn't see the Release-2.4 branch! Selecting it Xcode 14.x succesfully compiles the Coreplot-Framework.
When does the 2.4 release come out ?
Thanks again for all your effort! 
gilles
