### ISSUE TITLE
Xcode 14.3 compilation error (simulator vs arm64)

### ISSUE THREAD

**Issue by myoung959** [core-plot/core-plot#476]
In /libCorePlot-CocoaTouch.a(_CPTConstraintsRelative.o), building for iOS Simulator, but linking in object file built for iOS, file /libCorePlot-CocoaTouch.a' for architecture arm64

also

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by eskroch** [comment]
Use the code on the `release-2.4` branch. You'll need to shift over to using the framework build. The static library has been removed as part of the move to be compatible with newer versions of Xcode.

**Comment by myoung959** [comment]
Sure, I'd be happy to "switch over to using the framework build" but I haven't a clue how to do that. I've tried every which way to install from cocoapods and have read every post I can find on the Internet but can't build without errors. A step-by-step guide that was up-to-date would be appreciated as the one written here out of date and impossible to execute. Thanks.
