### ISSUE TITLE
No longer compiles on macOS

### ISSUE THREAD

**Issue by Mike4U** [core-plot/core-plot#479]
I wonder if you realize that most folks can't get CorePlot to build for MacOS since ~Catalina?. I come back to it every once in a while and no changes. I'm using your release-2.4 as downloaded with GitHub desktop.

I'm on a MacBook Air M2 with Sonoma 14.0, but this problem arose way back.
CorePlot Mac builds with Any Mac(Apple Silicon, Intel) if I set macOS to 10.15. Unfortunately it only specifies a minimum OS and uses the 14.0sdk so I get issues: example
NSToolbarSeparatorItem is deprecated since macOS 11.0

While this normally wouldn't matter, Apples security stuff is such that I don't think it will work with a framework that has issues.

When I try compile  Plot Gallery-Mac I get 27 errors that boil down to
~/core-plot/examples/CorePlotGallery/src/shared/PlotItem.h:8:9: 'CorePlot/CorePlot.h' file not found

Perhaps its something to do with using sdk14.0 even though that would result in lots of errors which are eliminated setting to 10.15

I've tried to follow some of your suggestions to others (who also gave up as far as I know) but can't get it to go.  Seems like the example problems as downloaded using GitHub desktop should work but no go.  I can't run the old Xcode versions that used to work.  I have a feeling this is an Xcode issue with all its great documentation but it's really frustrating.

Sure would like to get this to work, I'm getting tired of resorting to pyplot.

**Comment by eskroch** [comment]
I always build the example apps from the workspace instead of opening the individual projects so I hadn't noticed the "file not found" build errors. Those are fixed on the `release-2.4` branch now. I'll work on the SDK issues soon.

**Comment by Mike4U** [comment]
Hi, thanks for still supporting this !

I'm using the 2.4 branch and the file not found errors persist.

 I'm not completely sure if the SDK issue was real as I can not seem to duplicate it.  It's not completely clear what I'm getting messages about when compiling with Xcode when it fails and dependencies are involved.  The only way as far as I know is to click the "Show report Navigator" button as shown below and open the little content horizontal lines on the far right of each issue when highlighted..
<img width="712" alt="Plot-Gallery showing errors" src="https://github.com/core-plot/core-plot/assets/9957897/ee73877b-c827-4fc6-894a-cd6bb6692d59">

I'm curious if you're using Xcode 15.0.1 or something else.  I know that Apple has a habit of changing the way things work without mentioning the issues that might follow.  I can't recall if the current issues started on an Xcode change many years ago or an update to your code or an update to the code signing requirements.  I think it was OS10.15 that it last worked on macOS for me. I was updating a lot of the functions Apple was changing that you hadn't yet updated.  I went to a newer core-plot version in hopes of less effort and never was able to run again.  

 I was able to compile Plot Gallery for iPhone12 early this year but can't get it working for anything with Xcode 15.0.1.

I don't use anything but objective -C for my programming unless you are including swift or something else I'm not aware of.

**Comment by Mike4U** [comment]
What does building from the workspace mean?  Does that mean using commands in terminal?

thanks

**Comment by eskroch** [comment]
Instead opening individual project files in Xcode, open the `.xcworkspace` file in the [Examples](https://github.com/core-plot/core-plot/tree/release-2.4/examples) folder. You'll see all of the example projects in the sidebar and every available build scheme combined in the list at the top of the window.

**Comment by Mike4U** [comment]
Wow, thanks.  Entering through the .xcworkspace works, don't know why but it does ya.

What should I do next to get my project to work, normally I would do as your GitHub intro shows.  Is there some way to make it work like that or do I need to figure how to tie it into the . xcworkspace or change something in the core plot project and my project to make it work.  I take it the workspace is changing stuff the projects are not.

**Comment by eskroch** [comment]
It has to do with where Xcode puts the `build` directory. With the workspace, all of the projects share one build location so the example apps can find the CorePlot framework after it's built. When you open the individual projects, the build location is the same as the project folder. That's why I had to add the framework search path setting so the examples could find the CorePlot framework when they were built separately. For your app, you'll have to figure out where the CorePlot framework is being built and point the framework search path to that location if it's not already in the default locations.

**Comment by Mike4U** [comment]
Thanks for the great explanation.  After I realized I needed to have GitHub fetch your changes I'm now seeing what you have changed.  I can now build from the workspace or the individual projects.  Successfully tried most of the macOS combinations and all is well.  Haven't tried the iOS or my projects yet.

**Comment by Mike4U** [comment]
Thanks for all the help.  Here's a shot of my favorite plot using your framework.
<img width="956" alt="Sunrise, Set and Duration" src="https://github.com/core-plot/core-plot/assets/9957897/87660512-7e1a-40f6-b638-d3da9773a465">
Mostly self explanatory but your framework allows interesting details:
  The horizontal tick marks are weeks with todays date in the horizontal center.
  The vertical tick marks are hours, either for time of day or duration of daylight.
There is a separate  window to set your location or let the OS do it automatically.  It also allows to increment time by day week month or year so you can see the effects quickly.

Thanks again.
