### ISSUE TITLE
How to let X-axis line extends beyond the Y-axis at zero with a specified offset?

### ISSUE THREAD

**Issue by result0924** [core-plot/core-plot#480]
### Question 1:
For example, I want the labels on the X-axis to be right-aligned, and there should be lines extending down from the top on the left side.
Can I achieve this using Core Plot?

Ps. i know I can align the labels to the right, but I'm not sure how to make the line extend downward from the top on the left side.

<img width="413" alt="Screenshot 2023-12-06 at 10 18 50 AM" src="https://github.com/core-plot/core-plot/assets/822363/b2c811f4-ed89-4f9b-91cf-55533421961c">

### Question 2: can I set x axis's majorGridLineStyle when i set labelingPolicy = .none?

Thank you.

**Comment by eskroch** [comment]
**Question 1**: Use the [labelAlignment](https://core-plot.github.io/iOS/interface_c_p_t_axis.html#ab254c313a2b0ce382179d1723714bddf) to position the labels relative to the location. For the lines, have the axis draw tick marks. You can set the line style, length, and direction (above, below, and crossing the axis). See the [CPTAxis](https://core-plot.github.io/iOS/interface_c_p_t_axis.html) documentation for details.

**Question 2**: You can always set the formatting properties, they will be ignored if the element that they apply to is not visible. The `.none` labeling policy requires you to set the locations and labels yourself. As long as you provide some major tick locations, the grid lines in visible locations will be drawn using the provided line style.

**Comment by result0924** [comment]
Thank you, I will follow your advice and test it.

**Comment by result0924** [comment]
Sorry to bother you again. I tried to set up the major ticket label to be similar to Question 1, but it failed. I'm not sure where the issue is. Here is the test code.

[test code](https://github.com/result0924/iosLearning/blob/master/corePlotTest/corePlotTest/LabResultDetailChartView.swift)
in 282L try to set major ticket
```
xAxis.majorTickLocations = xMajorLocations
xAxis.majorTickLength = 10
xAxis.majorTickLineStyle = dashStyle
xAxis.tickDirection = .negative
```
but still not let line extending down from the top on the left side.
<img width="301" alt="截圖 2023-12-09 晚上10 59 15" src="https://github.com/core-plot/core-plot/assets/822363/beca1ea5-9b87-4ac6-abe5-72aa5ced867c">

**Comment by eskroch** [comment]
The `dashStyle` has a dashed style. You might just be unlucky in how the dash pattern lines up with the axis so nothing shows up. Try using a solid line.

**Comment by result0924** [comment]
I understand, thank you for your reply.

I command majorGridLineStyle
```
//            xAxis.majorGridLineStyle = axisLineStyle
```
so,  I can directly observe the ticket line
when i set
```
xAxis.tickDirection = .positive
```
i can get ticket line like thit
<img width="297" alt="截圖 2023-12-10 晚上10 04 04" src="https://github.com/core-plot/core-plot/assets/822363/58454965-156d-4725-8b9c-c565249dec93">

but when i set 
```
xAxis.tickDirection = .negative
```
ticket line will dissmiss
<img width="307" alt="截圖 2023-12-10 晚上10 11 24" src="https://github.com/core-plot/core-plot/assets/822363/99e4162c-6d9f-4609-9701-992c2a15d741">

It's really strange, so I was wondering if I did something wrong on my end.

**Comment by eskroch** [comment]
The tick marks are getting clipped at the edge of the plot area frame layer. You can see that in the iOS simulator by turning on the "Color Blended Layers" option in the Debug menu. Try setting the outer padding on the graph on the plot area frame instead of the graph itself in `configureGraph()`:

``` Swift
        if let plotAreaFrame = graph.plotAreaFrame {
            plotAreaFrame.masksToBorder = false
            plotAreaFrame.paddingTop = 25
            plotAreaFrame.paddingBottom = 35
            plotAreaFrame.paddingLeft = 40
            plotAreaFrame.paddingRight = 0
        }
```

**Comment by result0924** [comment]
"Oh, I see. When I configure it this way, it indeed works. Thank you so much!"

<img width="267" alt="截圖 2023-12-11 清晨7 19 13" src="https://github.com/core-plot/core-plot/assets/822363/b9ca49fa-b32f-4baf-a71c-1c40dfaf0dcb">
