### ISSUE TITLE
Scatterplot interpolation issue

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#68]
I recently noticed that my plots have a weird 'gap' at the base, see the picture attached. My code hasn't changed in ages, which is why I wonder if a recent change in CorePlot (release 2.0) could be causing this? The plot uses the CPTScatterPlotInterpolationCurved interpolation.

The datapoints are:

873.928162, 0.000000
888.578162, 0.002114
888.628162, 0.036571
888.678162, 0.408108
888.728162, 2.937174
888.778162, 13.633432
888.828162, 40.813324
888.878162, 78.798878
888.928162, 98.120418
888.978162, 78.798878

Note that I add the first point so that the plotline extends all the way to the Y-axis even though it is not visible. Interestingly if I remove that point, the plot looks as expected. 

![photo copy](https://f.cloud.github.com/assets/89622/2302111/1d2acc3a-a16c-11e3-94a0-3988a806a3ea.png)

**Comment by Calvin-wang** [comment]
I also met this problem, so, i want to know how to get the point as for the high ground.or Smooth transition between two points.
<img width="586" alt="screen shot 2015-07-29 at 10 28 05" src="https://cloud.githubusercontent.com/assets/7258218/8948706/95108e14-35dc-11e5-8411-57e30c575912.png">

**Comment by keehun** [comment]
@eskroch, couldn't there be a mode where it's basically linear except at each joint was rounded? I think the biggest problem with using a one-size-fits-all Bezier algorithm is that it doesn't maintain the fidelity of the data (i.e. by placing the local max/min not at the data point but before/after it). That's the biggest reason why Curved doesn't work for many instances. If we could just have Linear with curvy joints (while keeping most of the lines between data points linear), that would be GREAT!

**Comment by qalyo** [comment]
To fix this interpolation issue, we created this pull request: https://github.com/core-plot/core-plot/pull/264.
