### ISSUE TITLE
Build Fails on 64-bit Targets w/ Undefined Symbols

### ISSUE THREAD

**Issue by HunterHillegas** [core-plot/core-plot#76]
I'm using the release-2.0 branch and trying to build for 64-bit iOS but seeing the below. Is 64-bit currently broken?

Undefined symbols for architecture x86_64:
  "_vDSP_maxvD", referenced from:
      -[CPTPlot plotRangeForField:] in libCorePlot-CocoaTouch.a(CPTPlot.o)
  "_vDSP_minvD", referenced from:
      -[CPTPlot plotRangeForField:] in libCorePlot-CocoaTouch.a(CPTPlot.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pradipatgit** [comment]
I am getting the same error in release 2.2

**Comment by eskroch** [comment]
@pradipatgit Add the Accelerate framework to your app.

**Comment by pradipatgit** [comment]
I have Accelerate framework in my project. Was able to build the app for release but can't get it to work for debugging in the Simulator (10.1)
Also did a clean build of CorePlot-CocoaTouch target for iOS 10.1, still no luck.
I can't seem to change the architecture of coreplot project too.

Should I use older release? Will try it anyway and let you know if that solves the issue.

**Comment by eskroch** [comment]
The `vDSP` symbols are from the Accelerate framework. If you're still getting that error, double check that the Accelerate framework is being linked to the app in all build configurations.

**Comment by pradipatgit** [comment]
thanks @eskroch the core-plot source project was somehow missing the references to Accelerate.framework, CoreGraphics.framework, QuartzCore.framework, and UIKit.framework

Built it again after adding the frameworks and is working like a charm

**Comment by Praveend437** [comment]
Thanks@HunterHillegas, it is worked
