### ISSUE TITLE
Can core-plot be used with Swift?

### ISSUE THREAD

**Issue by marklivingstone** [core-plot/core-plot#96]
I am wondering if anyone has successfully used core-plot with Swift yet? Are there any tutorials or sample code available?

**Comment by veronicaTsao** [comment]
i am trying to use the core-plot with swift. But I have trouble to set the title location. From what I debugged, it seems that the interfaces in the CPTUtilities.h are still using the NSDecimal, and other interfaces to position the ticks and legend are still using NSDecimal. I have a hard time to use core-plot as the library in swift. Can you help?

**Comment by veronicaTsao** [comment]
For instance, the viewCoordinateForViewLength in the CPTXYPlotSpace still takes the NSDecimal as the input parameters which cannot plot the title locations correctly. Or I misunderstood something here. Can you give an example in swift to plot a scattered plot with title, ticks, legend, etc?

**Comment by eskroch** [comment]
The viewCoordinateForViewLength methods are internal to the `CPTXYPlotSpace` class and shouldn't be called by clients. Two of the example apps (*DatePlot* and the iPhone version of *CPTTestApp*) have been converted to Swift.

**Comment by veronicaTsao** [comment]
Thanks. The problem was that I was trying to use plotAreaViewPointForDoublePrecisionPlotPoint which in term calls the viewCoordinateForViewLength. 
I do not know if it makes sense, can you make the internal APIs only visible to the package itself, so that when using it as an library, those APIs will not be visible to the caller.

Thanks for all the examples. They are very helpful.

**Comment by eskroch** [comment]
The viewCoordinateForViewLength methods are not declared in the public headers, so you shouldn't see them when importing the Core Plot library or framework.

**Comment by veronicaTsao** [comment]
In order to position the popover at the selected bar, we need to call plotAreaViewPointForPlotPoint to convert the data points to view coordinates, it does not work in swift since the first argument is NSDecimal. Is there any work around? What i am trying to do is to achieve "when a bar is selected, we show a tip of the value and other information". Thanks so much for your guidance.

**Comment by eskroch** [comment]
There's another version that takes an array of doubles (`-plotAreaViewPointForDoublePrecisionPlotPoint:numberOfCoordinates:`).

I'll add point conversion methods (both directions) that use `NSArray` that will be easier to use in Swift.

**Comment by veronicaTsao** [comment]
Thanks so much. Can you update when the NSArray version is ready?

**Comment by veronicaTsao** [comment]
quick guidance to use -(CGPoint)plotAreaViewPointForDoublePrecisionPlotPoint:(double *)plotPoint numberOfCoordinates:(NSUInteger)count
in swift, should the double* mapped to Double[] or UnsafeMutablePointe<CDDouble>

Can you share a simple example to call the API in swift? 
Also plotAreaViewPointForDoublePrecisionPlotPoint internally calls the viewCoordinateForViewLength, as discussed above, it uses NSDecimal in the parameter list. Somehow the returned value is always 0. 
Can you help?

**Comment by gaming-hacker** [comment]
i'd like to see just a barebones example in swift as well.

**Comment by eskroch** [comment]
@gaming-hacker A couple of the included example apps (*DatePlot* on the Mac and the iPhone version of *CPTTestApp*) have been converted to Swift on the release-2.0 branch.

**Comment by eskroch** [comment]
I just added three plot space methods that take an `NSArray` of coordinate values on the release-2.0 branch.

    -(CGPoint)plotAreaViewPointForPlotPoint:(NSArray *)plotPoint;
    -(NSArray *)plotPointForPlotAreaViewPoint:(CGPoint)point;
    -(NSArray *)plotPointForEvent:(CPTNativeEvent *)event;

**Comment by gaming-hacker** [comment]
thanks.
dateplot only runs on mac.  i don't see one for iOS

**Comment by gaming-hacker** [comment]
i can't get it to build for iOS 8.2

core-plot-release-2.0/examples/CPTTestApp-iPad/Classes/CPTTestApp_iPadViewController.m:79:1: Implementing deprecated method


/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIViewController.h:366:1: Method 'didRotateFromInterfaceOrientation:' declared here

**Comment by gaming-hacker** [comment]
since i'm in landscape mode on my iPad, i just commented out this section and put the frames in viewDidLoad

**Comment by gaming-hacker** [comment]
where does it put/build the framework for iPad?  i want to do a simple example that uses a framework.
thanks

**Comment by eskroch** [comment]
The framework will be in build folder inside the Core Plot folder. If the framework built completely, it will include the headers.

    #import <CorePlot_iOS/CorePlot.h>

**Comment by bertranddelvaux** [comment]
Hello,
I am new to both swift and CorePlot. I have followed instructions as in this tutorial http://blog.alwold.com/2014/08/07/using-coreplot-with-swift-in-ios/#comment-1397
but for some reason, when I type 'install pod', I have this error message:

> set -e
> dtrace -h -s framework/TestResources/CorePlotProbes.d -o framework/Source/CorePlotProbes.h
> 
> sh: line 2: dtrace: command not found

Would it be possible that this issue can be solved by pointing to the release-2.0 instead? If yes, how to proceed?

Thank you!

**Comment by eskroch** [comment]
[Release 2.0](https://github.com/core-plot/core-plot/releases/tag/release_2.0) is out now. There is a [wiki page] that discusses the API changes for this version.
